### ISSUE TITLE
[map_server] load_map and save_map interfaces

### ISSUE THREAD

**Issue by PaulVerhoeckx** [ros-planning/navigation#1001]
Is there interest for a PR with a load_map service interface for the `map_server` (similar to [nav2_map_server](https://github.com/ros-planning/navigation2/tree/master/nav2_map_server#changes-from-ros1-navigation-map-server)) and a save_map service interface for the `map_saver`? 

I've read several issues pointing to such functionalities (#279, #635) and found some (abandoned) PR's (#461, #575). So I am curious what the current insights are.  

If there's interest, which of the following approaches is preferred for the save_map interface?
a) Create a new node with the same interface as `map_saver` in [nav2_map_server](https://github.com/ros-planning/navigation2/tree/master/nav2_map_server#services)? 
b) Add an argument to the existing `map_saver` node to allow it to run continuously and pass the OccupancyGrid using the service rather than pointing to a `map_topic` (as nav2_map_server does).

**Comment by Rayman** [comment]
I've found a discussion to include `LoadMap.srv` to `common_msgs` here: https://github.com/ros/common_msgs/pull/152
