### ISSUE TITLE
error move_base #981: make_plan_clear_costmap;make_plan_add_unreachable_goal

### ISSUE THREAD

**Issue by MiPa12** [ros-planning/navigation#1003]
Hi,
I get the following error during catkin_make with the navigation package.
I found this issue here https://github.com/ros-planning/navigation/issues/980. But still don't know how to solve it

`catkin_ws/src/navigation/move_base/src/move_base.cpp:267:39: error: ‘class move_base::MoveBaseConfig’ has no member named ‘make_plan_clear_costmap’
     make_plan_clear_costmap_ = config.make_plan_clear_costmap;
                                       ^~~~~~~~~~~~~~~~~~~~~~~
catkin_ws/src/navigation/move_base/src/move_base.cpp:268:46: error: ‘class move_base::MoveBaseConfig’ has no member named ‘make_plan_add_unreachable_goal’
     make_plan_add_unreachable_goal_ = config.make_plan_add_unreachable_goal;`

`navigation/move_base/CMakeFiles/move_base.dir/build.make:62: recipe for target 'navigation/move_base/CMakeFiles/move_base.dir/src/move_base.cpp.o' failed
make[2]: *** [navigation/move_base/CMakeFiles/move_base.dir/src/move_base.cpp.o] Error 1
CMakeFiles/Makefile2:11278: recipe for target 'navigation/move_base/CMakeFiles/move_base.dir/all' failed
make[1]: *** [navigation/move_base/CMakeFiles/move_base.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed`
any tip will be appreciated, thank you

**Comment by mikeferguson** [comment]
Gonna need some more info: what ROS Distro are you building under? What OS? What branch/commit are you building? Since our CI is passing on all branches, I'm guessing this is an issue with your config.

**Comment by MiPa12** [comment]
Hi, I use melodic and Ubuntu 18. I cloned the melodic-devel branch. It is only working when I remove the change which is done in #981.

**Comment by mikeferguson** [comment]
So, perhaps trying sourcing your workspace setup.bash? Maybe catkin is finding the headers installed in /opt/ros (which would not have this change, since we apparently haven't cut a new release in a while)?

**Comment by pepeRossRobotics** [comment]
This is how the costmap looks like after a while, this is similar to a bug that was patched some months (or two ago)
![image](https://user-images.githubusercontent.com/66112254/86260467-3a4fbb80-bbb5-11ea-9473-52b797e6ba2c.png)

**Comment by DLu** [comment]
@pepeRossRobotics I'm unclear how your picture is related to the above compilation bug.

**Comment by LordonCN** [comment]
After you catkin_make you can find  ../devel/include/move_base/MoveBaseConfig.h in your navigation package,Then
use this file to `REPLACE` the same file in /opt/ros/melodic/include/move_base/MoveBaseConfig.h

Hope it can help u~

**Comment by LordonCN** [comment]
I made it , try it pls.

**Comment by MiPa12** [comment]
Yes that worked, thanks.
