### ISSUE TITLE
Extrapolation error in  base_local_planner goal_functions

### ISSUE THREAD

**Issue by randoms** [ros-planning/navigation#1009]
I got an `Extrapolation error` when using navigation package. The error message shows  it is a tf timestamp issue. So I printed related time stamps.

```
[ WARN] [1594261882.397903742]: *******************
[ WARN] [1594261882.397991937]: now: 1594261882.397984788
[ WARN] [1594261882.398024288]: plan_pose.header.stamp: 1594261882.228748798
[ERROR] [1594261882.398107915]: Extrapolation Error: Lookup would require extrapolation into the future.
Requested time 1594261882.388890266 but the latest data is at time 1594261882.268743992, 
when looking up transform from frame [odom] to frame [map]
```

The source 

```c++
geometry_msgs::TransformStamped plan_to_global_transform = tf.lookupTransform(global_frame, ros::Time(),
          plan_pose.header.frame_id, plan_pose.header.stamp, plan_pose.header.frame_id, ros::Duration(0.5));
```

shows it will wait the tf data for 0.5s. But actually it didn't. But if I change `ros::Time()` to `ros::Time::now()` everything works as expected.

**Comment by SteveMacenski** [comment]
Please ask in ROS Answers / review existing questions on ROS Answers - this is almost without doubt a result of your configuration / upstream package configurations.
