### ISSUE TITLE
no stageros executable for rosrun in stage in hydro

### ISSUE THREAD

**Issue by tkruse** [ros-planning/navigation#101]
in groovy, one can 

rosrun stage stageros

in hydro, that is

rosrun stage_ros stageros

This breaks launch files using stage (ROS tutorials and such). It would be nicer to have tick-tock deprecation of stage/stageros if that was intentional, meaning an executable in the stage package that reports an warning that launch files have to be migrated an such, one distro before the old executable is removed.

If this was not intentional, undo.

**Comment by tkruse** [comment]
If intentional, create issue tickets instead for all launchfiles in hydro still pointing to stage/stageros, e.g. the files in https://github.com/ros-planning/navigation_tutorials/tree/groovy-devel/navigation_stage/launch

**Comment by hershwg** [comment]
Issue reported on incorrect package.  Moved to navigation_tutorials package: https://github.com/ros-planning/navigation_tutorials/issues/2
