### ISSUE TITLE
Update AMCL wiki with Selective Resampling

### ISSUE THREAD

**Issue by MatthijsBurgh** [ros-planning/navigation#1015]
Selective Resampling is introduced in #921 and #971 by @adi-vardi , but not added to the wiki. For completeness, please update the wiki for Kinetic, Melodic and Noetic.

**Comment by SteveMacenski** [comment]
Anyone can edit the wiki, you're welcome to make those changes yourself @MatthijsBurgh

**Comment by adivardi** [comment]
Sorry it took so long, I added a description of the change under the parameters @MatthijsBurgh

**Comment by MatthijsBurgh** [comment]
@adivardi thanks
