### ISSUE TITLE
catkin_make error in costmap_2d

### ISSUE THREAD

**Issue by yangyou95** [ros-planning/navigation#1016]
I'm using Deepin V20 (Based on Debian 10 Buster) and have successfully installed ROS from source by following http://wiki.ros.org/melodic/Installation/Source#Installing_from_source. Then I created my own ROS workspace and git cloned this navigation package (melodic-devel branch) into my own workspace/src. But when I did catkin_make, it showed errors like this:

```
Scanning dependencies of target costmap_2d_markers
[ 81%] Building CXX object navigation/costmap_2d/CMakeFiles/costmap_2d_markers.dir/src/costmap_2d_markers.cpp.o
[ 81%] Linking CXX executable /home/yang/catkin_ws/devel/lib/costmap_2d/costmap_2d_markers
/usr/bin/ld: /home/yang/ros_catkin_ws/install_isolated/lib/libtf.so: undefined reference to `tf2_ros::TransformListener::TransformListener(tf2::BufferCore&, ros::NodeHandle const&, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** 
```
I have the geometry2 package installed which included tf2_ros, so it should be able to find the tf2_ros resources.
I saw some people said this is a problem linked to the cmakelist that you need to add "tf2_ros" in the "find_package(catkin...)".
But it is already in the default cmakelists in the costmap_2d package. 

Thanks for the help.

**Comment by DLu** [comment]
Please specify what Ubuntu (presumably) distro you are using and what branch of costmap_2d you have checked out.

**Comment by yangyou95** [comment]
> Please specify what Ubuntu (presumably) distro you are using and what branch of costmap_2d you have checked out.

Thank u, I updated my issue to give full information. I'm using DeepinV20(Based on Debian 10 buster) and melodic-devel branch.

**Comment by yangyou95** [comment]
I solve this problem! When I git cloned the geometry2 package, the default version is not melodic-devel, that's why there is a problem.

Thanks anyway!
