### ISSUE TITLE
recipe for target 'navigation/fake_localization/CMakeFiles/fake_localization.dir/all' failed

### ISSUE THREAD

**Issue by YouShaoze** [ros-planning/navigation#1018]
[ 36%] Built target laser_scan_publisher
Scanning dependencies of target cirkit_waypoint_server
[ 36%] Linking CXX shared library /home/cumt/cumt_navigation/devel/lib/libslam_gmapping_nodelet.so
[ 37%] Building CXX object slam_gmapping/gmapping/CMakeFiles/slam_gmapping_replay.dir/src/slam_gmapping.cpp.o
[ 38%] Building CXX object cirkit_waypoint_manager/cirkit_waypoint_generator/CMakeFiles/cirkit_waypoint_server.dir/src/cirkit_waypoint_server.cpp.o
CMakeFiles/Makefile2:11257: recipe for target 'navigation/fake_localization/CMakeFiles/fake_localization.dir/all' failed
make[1]: *** [navigation/fake_localization/CMakeFiles/fake_localization.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by mikeferguson** [comment]
There is likely more information further up in your trace - and this is almost certainly a missing dependency, because the code is building just fine in CI.
