### ISSUE TITLE
Fundamental question about robot footprint

### ISSUE THREAD

**Issue by rsr152** [ros-planning/navigation#1021]
Assuming I have a turtlebot-like with a radius of 1m, my footprint is a circle of radius 1m (not accounting for any "padding"). 

Now, if I were to place a rectangular tray (say 1m long by 0.5m wide) such the the tray width is perpendicular to the direction of travel when the robot travels straight, will the footprint change at all? My understanding is that the robot periphery still extends beyond the tray width, so the footprint will be the same as before. 

Am I missing anything?

Thanks in advance!

**Comment by mikeferguson** [comment]
This seems better suited to answers.ros.org (I'd suggest adding a picture of the tray/robot as well).
