### ISSUE TITLE
move_base  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jacy-darker** [ros-planning/navigation#1024]
I use  common `rosrun move_base move_base`,
but it shows Segmentation fault (core dumped).
What happend[](url)
![Screenshot from 2020-09-05 21-01-16](https://user-images.githubusercontent.com/46134696/92305561-0466f300-efbb-11ea-8d22-bbe4eadc47ac.png)

**Comment by mikeferguson** [comment]
You can't just "rosrun move_base", you'll need a launch file with a bunch of configurations. See http://wiki.ros.org/navigation/Tutorials/RobotSetup
