### ISSUE TITLE
navfn_node missing in hydro install

### ISSUE THREAD

**Issue by tkruse** [ros-planning/navigation#103]
This might be intentional or an oversight during catkinization. The navfn_node executable is not installed.

**Comment by jonbinney** [comment]
What does the navfn_node do? Is it for testing the navfn planner?

**Comment by tkruse** [comment]
I think that may have been its only purpose. But it looks stripped down
now, maybe it has no use at all anymore. It's hard to tell for me without
looking into the details.

**Comment by tkruse** [comment]
The purpose might also have been to offer global planning for anyone not
wishing to use move_base.
