### ISSUE TITLE
costmap2d-plugin-obstacle_layer.cpp expect for help to build how to create update obstacle in real time

### ISSUE THREAD

**Issue by wesigj** [ros-planning/navigation#1034]
I want to add an obstacle plug-in, which can add fixed point, line or polygon obstacles. At present, I have read the following code:

https://github.com/wesigj/costmap_ prohibition_ layer

https://github.com/ros-planning/navigation/blob/kinetic-devel/costmap_ 2d/plugins/obstacle_ layer.cpp

But I want to know how to get costmap_ prohibition_ Layer reads yaml repeatedly and updates obstacles in real time

Or I'll post a topic and ask costmap_ prohibition_ Layer reads coordinates and updates obstacles

In general, I want to add obstacles, which can be updated according to the topics I post, or as I modify yaml

WORK IN kinetic

i have know

For the obstacle layer, in the reset function, the sensor topic will be unsubscribed first, then the map will be reset, and then the sensor topic will be re subscribed, so as to ensure that the whole layer starts again.

**What is the principle of reset function**

**I want to know about obstacle_ layer.cpp How to update obstacles in real time**

thank you very much for you response

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers
