### ISSUE TITLE
Discussion: Noetic API/ABI Freeze

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/navigation#1038]
Normally, we'd freeze the API/ABI a short time after the original release (June or so) - but since this is our last ROS release, we don't have another release to push things off to. There are a number of PRs opened that break API/ABI - and that we should probably get in.

With the MoveIt project, we've decided that API/ABI breaking changes are allowed through at least the end of the year - to give developers time to get those changes in. I'm going to propose the same for Navigation. Thoughts? @DLu @aaronhoy

**Comment by aaronhoy** [comment]
This makes sense to me.

**Comment by DLu** [comment]
Works for me.

**Comment by mikeferguson** [comment]
I'll leave this open for comment for a week (until next Monday) - and if we don't see any compelling reason not to, I'll start making my way through a bunch of PRs.

**Comment by mikeferguson** [comment]
No objections - we'll move forward with this
