### ISSUE TITLE
move_base node in hydro not killed by Ctrl-C

### ISSUE THREAD

**Issue by tkruse** [ros-planning/navigation#104]
To reproduce, in hydro:

```
roscore
rosrun move_base move_base
# press Ctrl-C
```

This should make the node die, but instead it goes into a loop eating 100% cpu power. Not nice.

**Comment by tkruse** [comment]
Hm, 20 seconds later i have trouble reproducing this myself. Now I often get:
^CTrace/breakpoint trap (core dumped)

Not sure what is going on. Then i can again reliably reproduce this with by running and killing:

```
roslaunch navigation_stage move_base_fake_localization_10cm.launch
```

and then again a rosrunned move_base does not die. 

The same happens when running the move_base executable without rosrun/roslaunch.

I can still force quite using Ctrl-\ , but still I think move_base should be easier than that to kill.

**Comment by DLu** [comment]
I have replicated the "^CTrace/breakpoint trap (core dumped)" message.

**Comment by mikeferguson** [comment]
I can no longer reproduce this, and hydro is long since dead
