### ISSUE TITLE
How to update the particle weights based on reference location?

### ISSUE THREAD

**Issue by Oyssster** [ros-planning/navigation#1042]
I want to update the particle weights based on the location that calculated by ICP instead of the distance between the scan points and the nearest obstacle. Could somebody give me some advice?

**Comment by mikeferguson** [comment]
Unfortunately this isn't a supported feature of AMCL - and in general I wouldn't recommend really hacking in AMCL (the codebase is 20+ years old, and has been ported too many times). You probably want to look for an alternate localization system.
