### ISSUE TITLE
No path found, high potential

### ISSUE THREAD

**Issue by nguyentuanHUST** [ros-planning/navigation#1045]
Hi all,
I encountered this error however I don't know what caused this issue. I guess the goal is out of bound but I could not find how?
Here is example log: 
[DEBUG] [1603796911.505105768, 9433.536000000]: [NavFn] Used 237 cycles, 13248 cells visited (135%), priority buf max 334
[DEBUG] [1603796911.505135209, 9433.536000000]: [Path] Pot fn boundary, following grid (10000000000.0/1)
[DEBUG] [1603796911.505146701, 9433.536000000]: [Path] Pot: 10000000000.0  pos: 1915.0,2061.0
[DEBUG] [1603796911.505155103, 9433.536000000]: [PathCalc] No path found, high potential
[DEBUG] [1603796911.505162187, 9433.536000000]: [NavFn] No path found
[DEBUG] [1603796911.505185952, 9433.536000000]: Failed to find a  plan to point (-4.23, 3.10)

**Comment by mikeferguson** [comment]
Unfortunately, I don't think there is enough information here for someone to even help out. If you can create a reproducible example that shows a potential bug, please reopen.
