### ISSUE TITLE
costmap_2d_ros: movementCB is unneeded

### ISSUE THREAD

**Issue by aditi741997** [ros-planning/navigation#1046]
Hello

I was going through the costmap_2d_ros.cpp file, and there is a timer with 0.1 duration, that calls movementCB function, which updates the parameters robot_stopped_ and old_pose.
On searching for these two params int he whole navigation code, I didnt find anything that uses the values of these parameters.

I was wondering what is movementCB and these parameters for?

**Comment by mikeferguson** [comment]
Hmm, looks like that is unused (and private, so nothing downstream could be using it). I'm guessing that got left behind during a refactor at some point.
