### ISSUE TITLE
ReconfigureCB does not recognise additional variable defined in .cfg file

### ISSUE THREAD

**Issue by limjizhengshawn** [ros-planning/navigation#1053]
Ubuntu 20.04
ROS Noetic (installed from Debian)

Our use case requires us to modify the innards of costmap_2d. We require adding dynamic reconfigure parameters into the VoxelPlugin in costmap_2d.

After adding a parameter to cfg, I try to access the variable in the reconfigureCB portion. But compilation throws an error. I suspect that catkin_make still references to the debian include rather than the source include. Below are the steps to replicate.

- Install Ubuntu 20.04 and ROS Noetic Desktop Full
- Create workspace and clone the navigation repo.
- Delete every package except the costmap_2d.
- Try compiling. It should succeed.
- Open navigation/costmap_2d/cfg/VoxelPlugin.cfg
- Add another variable e.g. 
`gen.add("test", int_t, 0, 'The maximum number of marked cells allowed in a column considered to be free', 0, 0, 16)`
- Open navigation/costmap_2d/plugins/voxel_layer.cpp
- Access the new variable in reconfigureCB function e.g. 
`int test = config.test;`
- Try compiling. Compiler will throw an error.

> /home/ubuntufocal/UnderDev/test_ws/src/navigation/costmap_2d/plugins/voxel_layer.cpp: In member function ‘void costmap_2d::VoxelLayer::reconfigureCB(costmap_2d::VoxelPluginConfig&, uint32_t)’:
/home/ubuntufocal/UnderDev/test_ws/src/navigation/costmap_2d/plugins/voxel_layer.cpp:92:21: error: ‘class costmap_2d::VoxelPluginConfig’ has no member named ‘test’
   92 |   int test = config.test;

Double checked that the devel folder's include file of VoxelPluginConfig.h reflects the creation of the new variable.
Sourcing the workspace devel/setup.bash does not help too.
I'm able to compile successfully in ROS Melodic.

**Comment by mikeferguson** [comment]
If it works on Melodic, but not Noetic, I imagine that either your workspace/install is different (do you not have ros-melodic-navigation packages installed perhaps?) or that this is an upstream issue in catkin_make. Either way, I don't think there is anything inherently wrong with the code from this repo that would prevent you doing an overlay, so I don't think we can fix this here.
