### ISSUE TITLE
No local costmap 

### ISSUE THREAD

**Issue by lslabon** [ros-planning/navigation#1059]
I am a little confused with the costmaps and pre hydro paramters, plugins etc...

I am using move base for my navigation and have a prebuild static map included.
When launching the navigation there is **no local_costmap visible**. The global costmap looks like everything is working fine. 
I did not have this problem a few days ago. I do not remember changing anything... but this makes no sense so I must.

![Costmap](https://user-images.githubusercontent.com/70685909/100750690-b0678100-33e6-11eb-87c1-1d2e88814a85.png)
(Ignore the not matching laser scan with the map - the robot is standing somewhere else in the office atm ) 

These are my .yaml files:

**Costmap_common_params.yaml**
max_obstacle_height: 0.60

footprint: [[-0.29, -0.26], [-0.29, 0.26], [0.29, 0.26], [0.29, -0.26]]
#robot_radius: 0.3

obstacle_layer:
  enabled:              true
  max_obstacle_height:  0.6
  combination_method:   1
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources:  scan_filtered
  scan_filtered:
    data_type: LaserScan
    topic: /scan_filtered
    marking: true
    clearing: true
    min_obstacle_height: 1
    max_obstacle_height: 5

inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true

**Local_costmap_params.yaml**
local_costmap:
  global_frame: "odom"
  robot_base_frame: "base_footprint"

  update_frequency: 10.0
  publish_frequency: 10.0
  always_send_full_costmap: true
  transform_tolerance: 0.5

  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0

  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

**Global_costmap_params.yaml**
global_costmap:
  global_frame: "map"
  robot_base_frame: "base_footprint"

  update_frequency: 10.0
  publish_frequency: 10.0
  always_send_full_costmap: true
  transform_tolerance: 0.5
  
  width: 100
  height: 100
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

I thought I did build the yaml. files correctly without using pre-hydro parameters but I use to get the WARNINGS 'Pre Hydro parameter static_map / map_type unused since plugins is provided... Can anybody tell me why this is? 

I hope somebody can help me with this issue. Thank you!
Laura

**Comment by mikeferguson** [comment]
Please post questions like this on answers.ros.org - the issue tracker here is really only for bugs/etc (also, answers.ros.org is far more searchable for people who might later experience the same issue). Thanks!
