### ISSUE TITLE
[Help me, please] The value of topic /robot_pose_ekf/odom_combined is updated very slowly after about 5s

### ISSUE THREAD

**Issue by phamhoanganhbk** [ros-planning/navigation#1063]
Hi everyone,

I have a data from IMU and Camera (x,y,z, roll, pitch, yaw). And I would like to use EKF to have a position of robot.
But my problem is the data is updated very slowly (about 5s). I have tried changing the frequency but it is not working.

May you help me please or give me some advice ? 
Many thanks,

`header: 
  seq: 7
  stamp: 
    secs: 1607012387
    nsecs: 894536972
  frame_id: "odom_combined"
pose: 
  pose: 
    position: 
      x: 0.833737413502
      y: -0.106431418372
      z: -0.00762944485808
    orientation: 
      x: -0.0390308254477
      y: 0.0617719494511
      z: -0.0388283789727
      w: 0.996570708938
  covariance: [0.3061640397645533, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3061640397645533, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3061640397645533, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1466007.5857820164, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1466007.5857820164, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1466007.5857820164]`

`header:
  seq: 8
  stamp: 
    secs: 1607012392
    nsecs: 495126962
  frame_id: "odom_combined"
pose: 
  pose: 
    position: 
      x: 0.761013804274
      y: -0.0816010701522
      z: -0.00170279411871
    orientation: 
      x: -0.0500488354215
      y: 0.0702702235365
      z: -0.0676093798755
      w: 0.993974940081
  covariance: [0.21165423782076687, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.21165423782076687, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.21165423782076687, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1138968.9381853295, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1138968.9381853295, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1138968.9381853295]
`

**Comment by mikeferguson** [comment]
Please post questions to answers.ros.org. Please also note that robot_pose_ekf is no longer maintained by this team - I personally recommend looking at robot_localization package.
