### ISSUE TITLE
default recovery behaviors forget insert names

### ISSUE THREAD

**Issue by ZJUTongYang** [ros-planning/navigation#1076]
Hello, 
    I noticed that when move_base runs the `loadDefaultRecoveryBehaviors` function, it inserts behaviors into `recovery_behaviors_`, but does not insert their names into `recovery_behavior_names_` at the same time. So move_base will crash at such as the line 961 in noetic-devel. (In my case, the line 955 shows that there are four elements in the `recovery_behaviors_` and `recovery_index_` is currently 0, but the `recovery_behavior_names_` has size 0 so move_base will die. ) The problem also exists in other version such as the melodic-devel. 
    A simple solution should be adding a line of code `recovery_behavior_names_.push_back("xxx");` after line 1116, 1122, 1128, 1132.  
Thanks

**Comment by mikeferguson** [comment]
There is a PR already here: https://github.com/ros-planning/navigation/pull/1071
