### ISSUE TITLE
dwa_local_planner Robot kinematic model

### ISSUE THREAD

**Issue by kizilkayabayram** [ros-planning/navigation#1083]
I've browsed through dwa_local_planner source code to get information about the kinematic model of mobile robot. However I haven't seen it anywhere. Can anyone tell me which kinematic model used to compute the velocity commands(cmd_vel) ?. I would like the modify that kinematic model in the source code and introduce some new constraints that fits my mobile robot to get more feasible velocity commands.

This way I could integrate it with my low level controller. I would really appreciate if someone points me out that part. Thanks.

**Comment by mikeferguson** [comment]
There really isn't a "kinematic model" in DWA. It basically just searches the space of possible commands (x,y,theta). (See also, the [original paper for DWA](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.379.1170&rep=rep1&type=pdf))
