### ISSUE TITLE
[melodic] subscirbe pointcloud

### ISSUE THREAD

**Issue by zhanggaojian** [ros-planning/navigation#1084]
Hi, i am sorry to bother you, i have somequestion about subscring the pointcloud. When to subscribe the pointcloud? Should the pointCloud be subscried after subscribing to the pose of the robot? Why is it subscribed when the obstacle layer is initialized in the code on the ObstacleLayer::Oninitialize function?

**Comment by mikeferguson** [comment]
This issue tracker is for bugs and feature requests. Please ask questions on answers.ros.org. Thank you.
