### ISSUE TITLE
pluginlib::LibraryLoadException

### ISSUE THREAD

**Issue by ryleymcc** [ros-planning/navigation#1094]
when launching move_base with this launch file
`<launch>
   
   <remap from="map" to="/rtabmap/grid_map" />

   <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">

    <rosparam file="$(find my_mower)/params/costmap_common_params.yaml" command="load" ns="global_costmap" /> 
    <rosparam file="$(find my_mower)/params/costmap_common_params.yaml" command="load" ns="local_costmap" />
    <rosparam file="$(find my_mower)/params/local_costmap_params.yaml" command="load" />
    <rosparam file="$(find my_mower)/params/global_costmap_params.yaml" command="load" /> 
    <rosparam file="$(find my_mower)/params/base_local_planner_params.yaml" command="load" />
    <param name="base_local_planner" value="teb_local_planner/TebLocalPlannerROS" />
    <param name="controller_frequency" value="10.0" />
 
 </node>

 <node pkg="tf" type="static_transform_publisher" name="base_link_broadcaster" args="-1.22 -.10 0 0 0 0 1 t265_link base_link 100" />
 

</launch> `

i get the error ( note the double slash in the library path "Failed to load library /opt/ros/noetic/lib//librtabmap_costmap_plugins.so.")
```

NODES
  /
    base_link_broadcaster (tf/static_transform_publisher)
    move_base (move_base/move_base)

ROS_MASTER_URI=http://localhost:11311

process[move_base-1]: started with pid [597522]
process[base_link_broadcaster-2]: started with pid [597523]
[ WARN] [1611326077.799032511]: global_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ INFO] [1611326077.800315838]: global_costmap: Using plugin "static_layer"
terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  Failed to load library /home/ryley/catkin_ws/devel/lib//librtabmap_costmap_plugins.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/ryley/catkin_ws/devel/lib//librtabmap_costmap_plugins.so: undefined symbol: _ZN10costmap_2d12CostmapLayer9clearAreaEiiii)
[move_base-1] process has died [pid 597522, exit code -6, cmd /home/ryley/catkin_ws/devel/lib/move_base/move_base map:=/rtabmap/grid_map __name:=move_base __log:=/home/ryley/.ros/log/8c7f8d68-5cbe-11eb-8387-5d9d9960bf48/move_base-1.log].
log file: /home/ryley/.ros/log/8c7f8d68-5cbe-11eb-8387-5d9d9960bf48/move_base-1*.log

**Comment by ryleymcc** [comment]
I tried installing navigation from source but that didn't work. I tried running catkin clean and catkin make but still the same error.
I tried following this fix https://www.youtube.com/watch?v=4xZKflNlJho&feature=youtu.be but when I run the command ~/catkin_ws/src$ grep "clearArea(int, int, int, int)" . -rnw
I get nothing returned

when I run catkin_make I noticed this message

-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "pvtk" references the file
   "/usr/bin/pvtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

**Comment by DLu** [comment]
Which branch of `rtabmap_costmap_plugins` do you have checked out?

**Comment by ryleymcc** [comment]
To solve the issue I uninstalled and reinstalled ros and all my package dependencies.

**Comment by DLu** [comment]
Okay, please reopen this issue if you have additional troubles.
