### ISSUE TITLE
Resizing Costmap

### ISSUE THREAD

**Issue by HosseinSheikhi** [ros-planning/navigation#1098]
Hello,

I am going to add a costmap layer that gives ceiling images as input, and after segmenting images, generates a costmap. lets call this layer, `ceiling_costmap`. This `ceiling_costmap` has a bigger size than other layers, so the (minimal) layers are as follow:  
![my_layerd](https://user-images.githubusercontent.com/64957461/107608010-940a7080-6bef-11eb-994f-10bfb503bbc2.jpg)

**Step 1**
The following depicts the costmap I get before applying any change to the code:
![Screenshot from 2021-02-10 22-05-32](https://user-images.githubusercontent.com/64957461/107607173-560c4d00-6bed-11eb-964a-4137d0b549d7.png)

**Step2**
For the sake of efficiency, I want to just resize the `master_grid` to be in the same size as `ceiling_costmap`. 
Here is the code:
in `CeilingCostmap::UpdateCosts(...)`
![Screenshot from 2021-02-10 22-15-48](https://user-images.githubusercontent.com/64957461/107607286-aa173180-6bed-11eb-99fe-3864e075f33c.png)

and the result costmap (`plugins: ["static_layer", "ceiling_layer"]`):
![Screenshot from 2021-02-10 22-03-44](https://user-images.githubusercontent.com/64957461/107607351-d9c63980-6bed-11eb-9d49-dd6bf405fff5.png)

**Step3**
I was playing with code to get better view, so in `static_layer.cpp`, in `processMap()`, tried to resize the `layered_costmap_` double size of `static_map`:
![Screenshot from 2021-02-10 21-26-34](https://user-images.githubusercontent.com/64957461/107607530-5eb15300-6bee-11eb-8804-ffe4e7b2cbf4.png)

I expected the result costmap to be as same as the first image, except having a bigger unknown part, but here it is the costmap:
![Screenshot from 2021-02-10 21-28-18](https://user-images.githubusercontent.com/64957461/107607609-91f3e200-6bee-11eb-8457-56981d503ae0.png)

and after set a navigation goal, and updating the map:
![Screenshot from 2021-02-10 21-29-22](https://user-images.githubusercontent.com/64957461/107607642-a6d07580-6bee-11eb-871f-dbb28cd14d38.png)

How I can resize the `master_grid`?

**Comment by HosseinSheikhi** [comment]
The issue has been produced in the ROS2 nav stack, so moved [here](https://github.com/ros-planning/navigation2/issues/2177#issue-806150309)

**Comment by mikeferguson** [comment]
Looks resolved in nav2
