### ISSUE TITLE
costmap_2d　　navigation　compile　error

### ISSUE THREAD

**Issue by feng123a** [ros-planning/navigation#1105]
When I compile the navigation, it shows ‘noexcept’ only available with -std=c++11 or -std=gnu++11, I added set(CMAKE_CXX_FLAGS "-std=c++11") to the cmakelist, and it still does. Hope someone can tell me how to solve it.The following is the error message.

/navigation/src/navigation/costmap_2d/include/costmap_2d/layer.h:111:27: error: expected ‘;’ at end of member declaration
   inline bool isEnabled() const noexcept
                           ^
/navigation/src/navigation/costmap_2d/include/costmap_2d/layer.h:111:33: error: ‘noexcept’ does not name a type
   inline bool isEnabled() const noexcept
                                 ^
navigation/src/navigation/costmap_2d/include/costmap_2d/layer.h:111:33: note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11

**Comment by mikeferguson** [comment]
Need way more information:
 * What version of ROS?
 * What branch of navigation?
 * What operating system and version?

Since CI is passing on all branches, you likely are using the wrong branch for the wrong operating system / ROS version

**Comment by mikeferguson** [comment]
No response - closing
