### ISSUE TITLE
Slowdown in performance between Installation via Binaries vs Source

### ISSUE THREAD

**Issue by derektan95** [ros-planning/navigation#1111]
Hi @mikeferguson  & @DLu , 

I noticed something strange with the performance of the Navigation Stack. Earlier, I **installed the Navigation Stack via Binaries** in **ROS kinetic**. I performed `sudo apt-get install ros-kinetic-navigation`. **Control Updates to the robot via DWA local planner reaches around 5hz.**

Due to some other issues I've faced, I decided to install this **package via source instead**. After compiling this git repository at the **kinetic-devel** branch in my catkin workspace, I ran the navigation stack with the exact same configuration. **Control Updates to the robot via DWA planner reaches only about 1hz.** 

Any insights to why this might be so? Much thanks.

**Comment by mikeferguson** [comment]
When building locally, I recommend building in release mode: "catkin_make -DCMAKE_BUILD_TYPE=Release". This is more of an issue in melodic and later (where the performance of the point cloud iterator is 300x difference in release vs non-release).

As a note, in general, we recommend asking these sort of questions on answers.ros.org - which has far better search ability for future users to benefit from the answers.
