### ISSUE TITLE
calculating obstacle cost using ray-traced line, why divide 2 in 'num_ = deltax_ / 2;' in file line_iterator.h?

### ISSUE THREAD

**Issue by noone3001** [ros-planning/navigation#1115]
`    if( deltax_ >= deltay_ )         // There is at least one x-value for every y-value
    {
      xinc1_ = 0;                  // Don't change the x when numerator >= denominator
      yinc2_ = 0;                  // Don't change the y for every iteration
      den_ = deltax_;
      num_ = deltax_ / 2;    //???
      numadd_ = deltay_;
      numpixels_ = deltax_;         // There are more x-values than y-values
    }`

**Comment by DLu** [comment]
Referring to https://github.com/ros-planning/navigation/blob/00fa9d110ed29c911270bf8eafcf607615dffca1/base_local_planner/include/base_local_planner/line_iterator.h#L74-L82

**Comment by DLu** [comment]
This is an implementation of Bresenhan's line algorithm, specifically the [algorithm using integer arithmetic](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm#Algorithm_for_integer_arithmetic). Using a combination of terminology from the code and wikipedia page, the main calculation is looking at the quantity `D` which is `A + B/2`, where `A=delta y` and `B=-delta x`. There are optimizations in the code to avoid doing repeated division, but the division by 2 ensures a proper difference calculation.
