### ISSUE TITLE
How to use Costmap2DROS?

### ISSUE THREAD

**Issue by Nurullahdmrly** [ros-planning/navigation#1134]
I have done some search online and I can't find any tutorials on how to utilize the costmaps to write an obstacle avoidance method for replanning. If someone knows something, please let me know if there are any examples that I should start looking at that would help me understand the application?

exactly what I want to do here; When the robot comes within a certain distance of the obstacle, it stops and waits for the new global path to come again. There is a global_planner that I developed myself for this. How can I add this, where should I start?

Thank you.

**Comment by mikeferguson** [comment]
The best examples would be the planners themselves that are included inside the navigation stack. Costmap2d also has API documentation here: http://docs.ros.org/en/noetic/api/costmap_2d/html/index.html

For more detailed advice, please use answers.ros.org
