### ISSUE TITLE
fatal error: nav_msgs/LoadMap.h no such file

### ISSUE THREAD

**Issue by xhding1997** [ros-planning/navigation#1139]
Failed to build
It shows :

/home/fy/ros_ws/STDR_CN/src/navigation/map_server/test/rtest.cpp:39:30: fatal error: nav_msgs/LoadMap.h: no such file.

I check my nav_msgs in : opt/ros/kinetic/include/nav_msgs/, here is the file list :

fy@fy:/opt/ros/kinetic/include/nav_msgs$ ls
GetMapActionFeedback.h  GetMapFeedback.h  GetMapResponse.h  GetPlanResponse.h  Odometry.h       SetMapResponse.h
GetMapActionGoal.h      GetMapGoal.h      GetMapResult.h    GridCells.h        Path.h
GetMapAction.h          GetMap.h          GetPlan.h         MapMetaData.h      SetMap.h
GetMapActionResult.h    GetMapRequest.h   GetPlanRequest.h  OccupancyGrid.h    SetMapRequest.h

I can't find LoadMap.h in anywhere.

**Comment by mikeferguson** [comment]
It would appear you are trying to build the wrong branch on Kinetic - make sure you are using the kinetic-devel branch of navigation.
