### ISSUE TITLE
Significance of the fixed_frame parameter in lookupTransform function

### ISSUE THREAD

**Issue by skpro19** [ros-planning/navigation#1141]
I was going through the [implementation](http://docs.ros.org/en/jade/api/tf2_ros/html/c++/classtf2__ros_1_1Buffer.html#a01a57848abda3ddeb617655cb88f37d2) of the `lookupTransform` function defined inside the [base_local_planner::getGoalPose()](http://docs.ros.org/en/jade/api/base_local_planner/html/namespacebase__local__planner.html#aa0e40cef653b1dd1f828e2090c22b5b8) function.

What is the significance of the `fixed_frame` parameter in `tf2_ros::Buffer::lookupTransform (target_frame, target_time, source_frame, source_time, fixed_frame, timeout) ` function ?

The documentation mentions the following - Get the transform between two frames by frame ID assuming fixed frame.
 
What's preventing us to always go for the other [implementation](http://docs.ros.org/en/jade/api/tf2_ros/html/c++/classtf2__ros_1_1Buffer.html#acabbd72cae8f49fb3b6ede3be7e34c55) of `the lookupTransform` function -   `tf2_ros::Buffer::lookupTransform (target_frame, source_frame, time, timeout)` ?

**Comment by mikeferguson** [comment]
I think this is really a better question for the tf2_ros repo, or answers.ros.org
