### ISSUE TITLE
Map_server does not work properly after being killed and launched again

### ISSUE THREAD

**Issue by Ducanor** [ros-planning/navigation#1142]
Hi,
Im working with the melodic rosdistro and rosversion 1.14.11.
What Im trying to do is killing the map server. Changing the png file from which the map is loaded and restart the map server.
This is my launch file:
```
<launch>

  <arg name="map_path" default="$(find simulator_setup)/maps/random_map/map.yaml" />

  <!-- map server-->
  <node name="map_server" pkg="map_server" type="map_server" args="$(arg map_path)"/>

</launch>
```
In the first launch the map server gets launched properly. Map is being published and the static_map service can be accessed.
But when killing the node with `rosnode kill map_server` and launching it again no map gets published and the service is unavailable as well.
`ERROR: Service [/static_map] is not available.`

**Comment by DLu** [comment]
It seems like something is wrong with how you are bringing it back up. Please post the question with more details about how it is brought back up on answers.ros.org
