### ISSUE TITLE
Properly import 2D map from Google map to Navigation stack?

### ISSUE THREAD

**Issue by Chuong1996** [ros-planning/navigation#1144]
Hi all!
So i used:
- Turtlebot 3 simulation for navigation using standard [Navigation stack](http://wiki.ros.org/navigation). 
- Matlab + gimp to create a pgm map and imported it into map_server. 
- Created a 3D world according to my GG map in Gazebo. 

So firstly, i tried to navigate using the pgm map. However, the performance is very bad since the reading from laser sensor drifted more and more compared to the wall of the map and thus the particles of AMCL scatter more and more. As shown [here](https://youtu.be/Z52ri5LXndI) 
 
After that, i tried to build a small section of the map using SLAM from 3D model in Gazebo, saved the map, and run navigation with it. The performance is great! Readings from laser sensor matched with 2D maps and particles of AMCL always converge. As shown [here](https://youtu.be/JrMijqZN8Gk).

Thus, i wanna ask, what is the proper way/steps to convert from Google map to a static 2D map that can perform well in Navigation stack? Because, again, i can imported it but the performance is not good and i'm not sure why. Thank you so much!

**Comment by mikeferguson** [comment]
There isn't a tool within this repo for manipulating google maps - I'd suggest asking on answers.ros.org
