### ISSUE TITLE
fatal error: ros/package.h: No such file or directory

### ISSUE THREAD

**Issue by wrmichaelmak** [ros-planning/navigation#1145]
I had this issue while building `navigation` from source using `catkin build`. I had fixed it but thought that it will be good to put out the fix for it. I edited the `CMakLists.txt` and added `roslib` under `find_package()` and `catkin_package(... CATKIN_DEPEND ... roslib)` Add it to the `package.xml` as well.

**Comment by DLu** [comment]
Can you please provide the specific error that you saw and what version you encountered it.

**Comment by wrmichaelmak** [comment]
Hi, the specific error I faced is exactly as stated on the issue title. I encountered the problem while using ROS Noetic

**Comment by DLu** [comment]
But on which package?

**Comment by wrmichaelmak** [comment]
Sorry for the lack of information, I was having problems with the map_server package

**Comment by mikeferguson** [comment]
Seeing as all branches are passing CI without this extra dependency, I'm thinking this is a local configuration issue. If the problem persists, please post to answers.ros.org

**Comment by alfanrizaldy** [comment]
Hello, how you solve this problem? @wrmichaelmak i'm facing this problem too and still can't found the answer
thank you
