### ISSUE TITLE
Move_base dies on giving RVIZ goal

### ISSUE THREAD

**Issue by kanishkanarch** [ros-planning/navigation#1167]
Hi, I am making a global planner but as soon as I am setting an RVIZ goal, move_base dies with `exit code -11`.
I am using ROS Melodic and a custom base_global_planner that I made (which was by the way working just fine before, no changes).
[This is the output of GDB debugger](https://github.com/Kanishk598/nav_stack/blob/Straight-line/gdb.txt), and [this is the output of Valgrind debugger](https://github.com/Kanishk598/nav_stack/blob/Straight-line/valgrind.txt). I am not able to check the mistake in the [planner that I've made](https://github.com/Kanishk598/nav_stack/tree/Straight-line).
Any hints?

**Comment by mikeferguson** [comment]
The GDB output clearly shows the crash is inside your planner (not the code of this repo). Please post to ROS answers for help in debugging your code.
