### ISSUE TITLE
Dynamically switch global/local planner?

### ISSUE THREAD

**Issue by badaolaziang** [ros-planning/navigation#1169]
We choose specific global and local planners while launching move_base, I wondered whether we can dynamically switch global or local planners during motion, or is it already given by Navigation stack 1 or navigation stack 2?

**Comment by mikeferguson** [comment]
In theory, you can use dynamic reconfigure to select a different planner - although I'm not sure how well tested/used this portion of code is. If you need additional assistance in how to implement that, I suggest visiting answers.ros.org - there are a lot more eyes over there.
