### ISSUE TITLE
DWA gives the opposite orientation at the start

### ISSUE THREAD

**Issue by yst1** [ros-planning/navigation#1170]
i meet the problem when i use DWA_local_planner, the DWA_gloabl_planner gives the orientation forward, the actual orientation we expect is forward, but DWA_local_planner gives the orientation backward, anyone meet this issue can give the solution?

**Comment by mxpfeng** [comment]
Try to increase acc_lim_x, acc_lim_theta.

**Comment by mikeferguson** [comment]
Closing due to lack of response - perhaps try answers.ros.org to debug your configuration with a larger number of contributors.

**Comment by Walkerxrc** [comment]
hello guy, can you solve this problem? Need you reply?
