### ISSUE TITLE
using move_base with other localization methods

### ISSUE THREAD

**Issue by 2019new** [ros-planning/navigation#1171]
Good afternoon, nowadays i am using move_base with another localization method, which also provides transform from [map] to [odom], i have checked my tf_tree and it works well with average rate of 68.07Hz. However, the move_base node cannot work with errors listed:

[ WARN] [1635227276.440263452, 94.150000000]: Could not transform the global plan to the frame of the controller
[ERROR] [1635227276.476144040, 94.190000000]: Extrapolation Error: Lookup would require extrapolation into the future.  Requested time 94.190000000 but the latest data is at time 94.180000000, when looking up transform from frame [odom] to frame [map]

[ERROR] [1635227276.476318093, 94.190000000]: Global Frame: odom Plan Frame size 82: map

it seems the required tf message is too old? can anybody tell me why did it happen,Thanks.
![terminal](https://user-images.githubusercontent.com/47342072/138836565-8b4171c8-b911-4b76-a838-035fbc701264.png)

**Comment by 2019new** [comment]
![tf](https://user-images.githubusercontent.com/47342072/138995212-6f833dc6-dcc6-4f9b-a5c4-d286482b7725.png)
my tf tree using cartographer for localization

**Comment by mikeferguson** [comment]
By default, AMCL adds the "transform_tolerance" parameter to the laser scan timestamp when publishing the localization position (this can have some interesting side effects if trying to look backwards in time or interpolate, but negates the issues with localization running behind since most navigation things are looking for just the "latest" transform). You might see if cartographer has a similar parameter.

**Comment by mikeferguson** [comment]
Also, I'd suggest asking questions like these on answers.ros.org - since there will be more folks looking at that, and maybe even some that are familiar with cartographer.

**Comment by mgrallos** [comment]
> By default, AMCL adds the "transform_tolerance" parameter to the laser scan timestamp when publishing the localization position (this can have some interesting side effects if trying to look backwards in time or interpolate, but negates the issues with localization running behind since most navigation things are looking for just the "latest" transform). You might see if cartographer has a similar parameter.

what's the ideal value of transform_tolerance?
