### ISSUE TITLE
move_base and amcl make release on raspberry ubuntu20.04, run error something

### ISSUE THREAD

**Issue by 3shao** [ros-planning/navigation#1174]
![171921s9r21741b9e2wzw9](https://user-images.githubusercontent.com/13852283/139777792-0fd68949-8d61-4a53-8c8e-5cd7e4a44030.png)
![171940oa0z0u0zafuazahu](https://user-images.githubusercontent.com/13852283/139777818-96645155-58e8-4c4d-b1a2-1a6e60caeaf7.png)
how to fix?

**Comment by mikeferguson** [comment]
There is no way anyone can help you with this amount of information - you need to run your nodes inside gdb to get some sort of trace. If running from Debians, also make sure that all your packages are up to date (in case there is an ABI issue). Please re-open this ticket if you are able to provide more information
