### ISSUE TITLE
Forget to fix bug in ROS kinetic version?

### ISSUE THREAD

**Issue by qlibp** [ros-planning/navigation#1175]
https://github.com/ros-planning/navigation/blob/e2e9482695f11d8d30326480e3283967d94d83f5/amcl/src/amcl/sensors/amcl_odom.cpp#L231

compared with the commit in 31c8e94 for later ROS version.

**Comment by mikeferguson** [comment]
We did not forget Kinetic - this changes behavior and so it went into Melodic and later (most users would be upset if their parameters changed behavior mid-release cycle, so the bug remains in older releases, which are also no longer maintained).
