### ISSUE TITLE
Implementing constraint for each wheel velocity

### ISSUE THREAD

**Issue by AlperenKosem** [ros-planning/navigation#1176]
Hi,

I am using DWA local planner. Is it possible to implement minimum and maximum constraint for wheel velocity for each wheel. Because in my project, motor of wheels cannot apply some velocities. When i tried to constrain in linear and angular velocity. I cannot estimate constraint of wheel velocities because it is related with current linear and angular velocity directly. If wheel velocity in upper or lower bound of capability of motors, robot stuck this location and cannot move unless i give new path. How can implement wheel velocity constraints in optimization process?

Best regards and thanks for the great work!

**Comment by mikeferguson** [comment]
DWA is unaware of the robot kinematics - it only takes linear and angular limits of the robot. Typically one would set the linear limit lower than the true linear limit to account for the required angular component.

I'm not aware of any available open-source local planner that would take differential drive wheel constraints - you might try asking on answers.ros.org
