### ISSUE TITLE
Aborting because a valid plan could not be found. Even after executing all recovery behaviors

### ISSUE THREAD

**Issue by Geonhee-LEE** [ros-planning/navigation#1178]
Hi, I have a question for `move_base` node.
I have used `move_base` node for navigation and works well usually. But, I detected some strange situations with "Aborting because a valid plan could not be found. Even after executing all recovery behaviors".
 
As I explained this issue, it occurred `Aborted` after once `Active` for move_base status.
I wonder what this problem is.

Regards

**Comment by mikeferguson** [comment]
This means that the global planner could not find a path from your current position to the goal position - even after running all of your recovery behaviors. If there is a path in the real world, then you likely have sensor noise in your costmap that is telling the robot it cannot get to the goal.
