### ISSUE TITLE
How to transform navigation to follow me?

### ISSUE THREAD

**Issue by AlessandroMelino** [ros-planning/navigation#1179]
Hello.

I have a whole system working with ROS1 navigation (global_planner and teb_local_planner) and now I would like to make a follow me. I have the person position all the time but I don't know how to approach to the problem, maybe modifying the goal every some time? There is any existing approach to this problem? Maybe something like turtlebot_follower?

Any ideas would be useful. Thank in advance.

Best regards. Alessandro

**Comment by mikeferguson** [comment]
I see that you've also posted this on answers.ros.org - which is the right place for a discussion like this.
