### ISSUE TITLE
What is the meaning of “plan_to_global_transform * tf_pose” operation

### ISSUE THREAD

**Issue by Theyearling** [ros-planning/navigation#1182]
Why execute “plan_to_global_transform * tf_pose operation” operation in line 143 of goal_functions.cpp under the kinetic-level branch.

The link is https://github.com/ros-planning/navigation/blob/kinetic-devel/base_local_planner/src/goal_functions.cpp#L143

**Comment by mikeferguson** [comment]
The plan is possibly in a different frame than the global frame - so we transform it to the global frame before publishing it in the global frame (in theory, that global frame, such as "map" is also the fixed frame that most people are visualizing in RVIZ)
