### ISSUE TITLE
Error while trying  cuts the plan off (reduces it to local window)

### ISSUE THREAD

**Issue by RodrigoFBernardo** [ros-planning/navigation#1184]
I want to reduce my global plan to the local window, using this function:

```
// transform global plan to the map frame we are working in
		// this also cuts the plan off (reduces it to local window)
		std::vector<int> start_end_counts (2, (int) global_plan_.size()); // counts from the end() of the plan
		if(!MPC4wdPlannerROS::transformGlobalPlan(*tf_, global_plan_, *costmap_ros_, costmap_ros_->getGlobalFrameID(), transformed_plan_, start_end_counts))

```

But I have this error:

`/opt/ros/melodic/lib/move_base/move_base: symbol lookup error: /home/euroage/catkin_ws/devel/lib//libmpc_4wd_local_planner.so: undefined symbol: _ZN21mpc_4wd_local_planner16MPC4wdPlannerROS19transformGlobalPlanERKN7tf2_ros6BufferERKSt6vectorIN13geometry_msgs12PoseStamped_ISaIvEEESaIS9_EERN10costmap_2d12Costmap2DROSERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSB_RS5_IiSaIiEE`

Thank you in advance for your help

**Comment by mikeferguson** [comment]
c++filt says this is:
```
mpc_4wd_local_planner::MPC4wdPlannerROS::transformGlobalPlan(tf2_ros::Buffer const&, std::vector<geometry_msgs::PoseStamped_<std::allocator<void> >, std::allocator<geometry_msgs::PoseStamped_<std::allocator<void> > > > const&, costmap_2d::Costmap2DROS&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<geometry_msgs::PoseStamped_<std::allocator<void> >, std::allocator<geometry_msgs::PoseStamped_<std::allocator<void> > > >&, std::vector<int, std::allocator<int> >&)
```

So this looks to be entirely an issue in your derived code and not with this repository - please post to answers.ros.org if you're still trying to debug this.
