### ISSUE TITLE
AMCL: What's the point of laser_z_rand for likelihood field?

### ISSUE THREAD

**Issue by marcelino-pensa** [ros-planning/navigation#1185]
Hi,

I've been reading through the `likelihood_field` code of AMCL and I was confused about the part in [this line](https://github.com/ros-planning/navigation/blob/6e9de3f16c76329fc8d218189d90e4ebe51d61c2/amcl/src/amcl/sensors/amcl_laser.cpp#L286).

As it turns out, `z_rand` is a constant (coming from the launch file), and `z_rand_mult` is also a constant (it's `1/max_range`, where I think that `max_range` is the maximum range of the laser sensor).

Hence, we always add a constant value to `pz` (which is supposed to be a probability variable, but acts more like a weight variable) given by `z_rand / max_range`, for all particles and laser measurements.
What is the point in that? Why is it helpful to add a constant weight to all particles multiple times?

I could not find a reference to this in Thrun's book, so I don't know if I'm missing something crucial to understand this.

I'm also puzzled by [this line](https://github.com/ros-planning/navigation/blob/6e9de3f16c76329fc8d218189d90e4ebe51d61c2/amcl/src/amcl/sensors/amcl_laser.cpp#L295), which basically computes the `pz` weight cubed. Why should we compute the weight cubed? Any theoretical motivation for that? Based on the code comments, it seems like it was copied from the beam model, but no further explanation is provided

This code was written more than two decades ago, so I'm not sure if anyone has any answers to any of those questions, but I'm thankful to discuss it with anyone who might have some insights into this...

**Comment by mikeferguson** [comment]
The idea behind z_rand is that there are things which are "unexplained by the underlying map" - for instance, a box left in the middle of the room, or a person walking through. This actually does exist in the Thrun book - see figure 6.2 - there are 4 parts to the sensor model, and the last part is a uniform distribution they call pRAND.

As for the cubed value - I don't think anybody knows exactly how it was arrived at (it does diverge from the literature) - but it appears to be essential to actual operation in the real world (I know of at least one other system that was implemented from scratch based on the Thrun book, and they had to add the cubed value to make it actually work)
