### ISSUE TITLE
Map_server: new debian release

### ISSUE THREAD

**Issue by btertoolen** [ros-planning/navigation#1186]
Hello!

We are using the map_server in our project and are currently looking to implement multi-map support for our robot.

After doing some looking around I found that the functionality to load new maps has been added in the map_server with #1029 . However there has been no release since, and we would like to be able to use the feature without having to compile everything from source.

Are there any plans on creating a new release soon?

Thanks!

**Comment by jmeyer-diligent** [comment]
Bump: similar needs here.

**Comment by mikeferguson** [comment]
New release going out later today (just getting a few more things merged first)
