### ISSUE TITLE
How to publish/advertise the make_plan service?

### ISSUE THREAD

**Issue by jingtianweidizzf** [ros-planning/navigation#1187]
Hi all, 
I am trying to use the planner from the `move_base/make_plan` service. But I don't know how to start the service and the client script get stuck at the `ros::service::waitForService(service_name, ros::Duration(3.0)`, and reporting "waitForService: Service [/move_base_node/make_plan] has not been advertised, waiting...".

I tried to run `rosrun move_base move_base` since there's no direct 'move_base_node'. But after I ran the move_base, there's no `make_plan` service if I list all the active services via `rosservice list`. There's only `get_loggers` and `set_logger_level` active.

Could any guy please tell me how to get a make_plan service working? Thanks in advance :)

**Comment by mikeferguson** [comment]
You really can't just "run move_base" - it requires some configuration. Please take a look at http://wiki.ros.org/navigation - in particular the section titled "Navigation Stack Setup" for how to configure for your robot.
