### ISSUE TITLE
 Does ROS Navstack use the Twist part of the Odom message?

### ISSUE THREAD

**Issue by adbidwai** [ros-planning/navigation#1189]
The `nav_msgs/Odometry` message type contains the `Twist` as well as the `Pose` message types. Generally odometry only means the `Pose` i.e. the position and the orientation of the robot. Does ROS NavStack (`move_base` to be precise) use this `Twist` in the `nav_msgs/Odometry` message to control the velocities? Or does it just refer to the `Pose` part of the `Odom` message?

Does ROS Navstack also have the feature of high level velocity control? Does it actually make sure that the robot is moving with the velocity it published?

**Comment by DLu** [comment]
I believe it depends on which planner you are using, but some of the local planners [use the odometry](https://github.com/ros-planning/navigation/blob/4a3d261daa4e7eafa40bf7e4505f8aa8678d7bd7/base_local_planner/src/odometry_helper_ros.cpp#L48) to calculate the current speed and DWA (for instance) will only command velocities that are in a dynamic window around that velocity.
