### ISSUE TITLE
AMCL's pose drift to wrong place at some scenes during the navigation

### ISSUE THREAD

**Issue by yst1** [ros-planning/navigation#1191]
I use robot_pose_ekf to fuse imu and odom, output the tf from base_link to odom.
when the above phenomenon happened, the amcl particles are also convergent, the path output from odom also consequent，but the pose(tf from base_link to map) drift the wrong place, is that mean the amcl outputs the wrong tf from odom to map, if so what can cause this problem? Thanks for your advise!

**Comment by yst1** [comment]
I use robot_pose_ekf to fuse imu and odom, output the tf from base_link to odom. 
when the above phenomenon happened, the amcl particles are also convergent, the path output from odom also consequent，but the pose(tf from base_link to map) drift the wrong place, is that mean the amcl outputs the wrong tf from odom to map, if so what can cause this problem? Thanks for your advise!

**Comment by yst1** [comment]
it will happen in two situations: one is that the lidar observation has only 100 degree by obstacle occlude  when 270 degree in normal, another is the car rotate too fast at 360 degree/s

**Comment by mikeferguson** [comment]
This sounds like more of a configuration issue than an actual bug in AMCL - I'd suggest posting to answers.ros.org - and including some videos and details of your configurations to have any hope of getting help with the issues.
