### ISSUE TITLE
DWA can not add parameter 

### ISSUE THREAD

**Issue by LGK199408** [ros-planning/navigation#1195]
I had added a parameter into DWAPlanner.cfg in line 30

`gen.add("target_occupied", double_t, 0, "when target was occupied there is another xy_goal_tolerance", 0.5, 0.0, 1.0)`

and then  invoked the parameter in dwa_planner_ros.cpp in line 67

`double target_occupied_xy1 = config.target_occupied;`

and then catkin_make 
error was occured...

`home/lgk/catkin_ws/src/navigation/dwa_local_planner/src/dwa_planner_ros.cpp: In member function ‘void dwa_local_planner::DWAPlannerROS::reconfigureCB(dwa_local_planner::DWAPlannerConfig&, uint32_t)’:
/home/lgk/catkin_ws/src/navigation/dwa_local_planner/src/dwa_planner_ros.cpp:67:43: error: ‘class dwa_local_planner::DWAPlannerConfig’ has no member named ‘target_occupied’
   67 |       double target_occupied_xy1 = config.target_occupied;
      |                                           ^~~~~~~~~~~~~~~
`

**Comment by DLu** [comment]
Does the error persist if you try building again?

**Comment by LGK199408** [comment]
Yes @DLu

**Comment by LGK199408** [comment]
![微信图片_20220412093406](https://user-images.githubusercontent.com/47169575/162861030-c96d2dfb-b307-47fd-aeb0-4e66f6ca432d.png)
![微信图片_20220412093450](https://user-images.githubusercontent.com/47169575/162861086-dd515f4c-ce58-4fa5-9e1f-3526f21247d2.png)

**Comment by mikeferguson** [comment]
This appears to be some issue with your local workspace - not a bug in the navigation stack (this repo). Please post to answers.ros.org as there are many more folks over there to help out with debugging.
