### ISSUE TITLE
map and control loop missed its desired frequency

### ISSUE THREAD

**Issue by QipiaoZhou** [ros-planning/navigation#1196]
map and control loop missed its desired frequency，is there any solution for this?

**Comment by mikeferguson** [comment]
Usually this is related to your robot computer not having enough CPU. Possible fixes are reducing/downsampling the inputs to costmaps, changing the desired rates of controllers/costmaps, or shutting down other parts of your ROS system (i.e. lazy subscribers). I'd suggest posting a question to answers.ros.org with more details about your particular robot setup
