### ISSUE TITLE
Release to Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-planning/navigation#1199]
Hello maintainers!

I notice you have a `noetic-devel` branch, but there's not yet been a release to Noetic. Would you be willing to make one? It [doesn't appear to be blocked by other ROS packages](http://repositories.ros.org/status_page/blocked_releases_noetic.html?q=navigation&s=6&r=1).

**Comment by mikeferguson** [comment]
I'm not sure what prompted this - we have released into noetic - on Aug 27, 2020 (so, a while ago)

 * Release: https://github.com/ros-planning/navigation/commit/e7f13251b74fb9aa00200c675e655bfa376f5a14
 * Build status (all debs are available): http://repositories.ros.org/status_page/ros_noetic_default.html

I'll be working on cutting a newer release shortly.

**Comment by sloretz** [comment]
Very strange. I wonder if I was looking at a cached blocked releases page.
