### ISSUE TITLE
Track the status of intermediate waypoints in ROS navigation

### ISSUE THREAD

**Issue by adbidwai** [ros-planning/navigation#1208]
Hi guys!

1) So a plan is composed of `start_point`, intermediate_points and `goal_point` <br>
2) When I call `move_base` with a `goal_point`, it asks `global_planner` for a plan and starts navigating to the intermediate points and eventually to the `goal_point` <br>

If my statements 1) and 2) are correct, then, <br>
3) Is there any service which can help me track the status of navigation to these "intermediate points"? As far as i know the `current_goal` topic has the `goal_point` published on it and the `status` topic has the status to the "`goal_point`" published on it, but there's no API which can help to know the status of navigation to the intermediate points. 

Any idea how do I deal with this? Thanks 😃

**Comment by mikeferguson** [comment]
The intermediate points aren't really tracked in any real sense even inside navigation - most local planners just "forget" the intermediate poses that are behind them.

The best way you could do this is to write a node that subscribes the global plan, and then monitor your current position versus this (there are some utilities inside the base_local_planner package that might help with some of this, but I think all of them assume you want to forget the older points, not figure out how far along the path you are).
