### ISSUE TITLE
Load different map/world in a sequence to evaluate navigation algorithm

### ISSUE THREAD

**Issue by Armanasq** [ros-planning/navigation#1209]
Hi all,

I want to analyze my path planner algorithm, so I must evaluate this algorithm in hundreds of situations. As a result, I need to load hundreds map in Rviz and Gazebo in a sequence and record the generated control commands. For each map, this code will record control commands for evaluating the path planning algorithm.

Is it possible to load different map/world files in a "for loop" (in a sequence)?

**Comment by DLu** [comment]
The scope of this question is outside of the specific navigation code. I would recommend asking on answers.ros.org. 

I did some work on this [back in the day](https://github.com/DLu/path_planning_metrics) but its not documented. One result was [this paper](http://wustl.probablydavid.com/entry179.html)
