### ISSUE TITLE
amcl with pointcloud source

### ISSUE THREAD

**Issue by Proxeus96** [ros-planning/navigation#1214]
hi, i know that actually amcl use laserscan, but i want krow if have a way to implement a pointcloud source to estimate pose, if not maybe use pointcloud_to_laserscan but i don't know if this is the best way to get the estimated pose.

**Comment by mikeferguson** [comment]
AMCL does not natively support point clouds - the pointcloud_to_laserscan might work (although you really want a wide FOV of the laser for good results). If you have additional questions - I'd suggest this is better suited for answers.ros.org
