### ISSUE TITLE
ROS navigation stack

### ISSUE THREAD

**Issue by federista** [ros-planning/navigation#1216]
I need a bit of assistance with ROS navigation stack. 
I am using a Bunker robot from [agilex][1]

I am working on obstacle avoidance using RPlidar.
[![enter image description here][2]][2] 
Things I have done:
1) Have mapped the environment and also saved the files.
2) Have amcl data from /tf and /odom topics. 
3) have understanding of base controller for publishing the velocities.
4) Also have the data from /scan topic of RPlidar

What I am looking for:
1) The design of the launch file will help me in autonomous navigation. 
2) How do I merge all of this data that can help me in achieving this task?

I have taken a bit of help from [this GitHub repository][3] but still I am confused a bit. Thank you and good day

  [1]: https://global.agilex.ai/products/bunker
  [2]: https://i.stack.imgur.com/5grWx.png
  [3]: https://github.com/bandasaikrishna/Autonomous_Mobile_Robot/blob/main/mobile_robot_autonomous_navigation/launch/autonomous_nav.launch

**Comment by mikeferguson** [comment]
This issue tracker is for bugs/enhancements to the navigation code itself - for configuration issues/questions, we recommend posting to answers.ros.org (there are far more people active over there)
