### ISSUE TITLE
Trouble installing navigation / map-server

### ISSUE THREAD

**Issue by Darkproduct** [ros-planning/navigation#1224]
I have Ubuntu 20.04 with ROS noetic running and I can't install `ros-noetic-navigation`.

> The following packages have unmet dependencies:
>  ros-noetic-navigation : Depends: ros-noetic-map-server but it is not going to be installed

I followed the dependency chain: `ros-noetic-navigation` → `ros-noetic-map-server` → `libsdl-image1.2-dev` → `libsdl1.2-dev` → `libcaca-dev` → `libcaca0` and ended up with the following error:

> The following packages have unmet dependencies:
>  libcaca-dev : Depends: libcaca0 (= 0.99.beta19-2.1ubuntu1) but 0.99.beta19-2.1ubuntu1.20.04.1 is to be installed

[From here](https://packages.ubuntu.com/focal/libs/libcaca0), I see that there are two different versions of `libcaca0` for amd64. I'm not sure how I can solve this issue, nor who is to blame for it. I really hope this gets resolved soon.

**Comment by khinggan** [comment]
Hi @Darkproduct, have you found some solutions? I met the same problem.

**Comment by Darkproduct** [comment]
Solved it with:
```
sudo dpkg -r --force-depends libcaca0
sudo apt install libcaca0
```

But not sure if there are any side effects with other packages.

**Comment by robotlearning123** [comment]
sudo aptitude install ros-noetic-map-server

**Comment by yhn-liu** [comment]
> sudo aptitude install ros-noetic-map-server

Thanks for sharing! This solved my problem.
