### ISSUE TITLE
Problem installation from source, error: ros/package.h: No such file or directory

### ISSUE THREAD

**Issue by alfanrizaldy** [ros-planning/navigation#1227]
fatal error: ros/package.h: No such file or directory
How to solve this when i build the package from source? problem happen in map_server
/home/pi/ros_catkin_ws/src/navigation-noetic-devel/map_server/test/rtest.cpp:35:10: fatal error: ros/package.h: No such file or directory
#include <ros/package.h>

**Comment by rosenblat** [comment]
Hi did you figure this out? I've got the same issue. I'm a ros noob trying to compile the Nav stack on raspbian. I found this Issue which seems to be the same from about a year and a half ago.

https://github.com/ros-planning/navigation/issues/1145

follow up adding roslib to Map_server cmakelists.txt as mentioned in the post worked for me.

**Comment by alfanrizaldy** [comment]
> 


Thank you for the solving, unfortunately I'm no longer using raspberry pi for my projects. Hope this help others
