### ISSUE TITLE
ryxen 9 5900hx or jetson orin for navigation stack? any recommendation which one would have better result?

### ISSUE THREAD

**Issue by ipinyulun** [ros-planning/navigation#1230]
after trying with jetson tx2 and nuc i3.
it seem not powerfull enough to handle the load.
so im currrently comparing jetson agx orin and mini forum ryzen 9 5900hx?

which one recommended?

**Comment by DLu** [comment]
I'm sorry that it does not run on the platforms you described, but I don't think we can provide a recommendation of which to use.
