### ISSUE TITLE
Using Own Localization Method with Navigation

### ISSUE THREAD

**Issue by joewong00** [ros-planning/navigation#1253]
Hi there,

I got a 3D lidar on my robot and I got navigation stack working by converting the pointcloud data from the lidar to laserscan for localizaton. However, I would like to improve the localization to a 3D ones by utilizing the pointcloud from the lidar. My question is:

I already have a localization stack that can output the robot's pose and twist topic on a 3D pointcloud map. It can provide the transform from map -> base_link. How do I use these information in navigation stack instead of using AMCL? The navigation stack is not as simple as subscribing the robot's pose topic as it is using a plugin method.

Any suggestion on how do I go about this? Thanks.

**Comment by MortezaHagh** [comment]
Hi,
As far as I know (also tested myself), if the following are set you could run the navigation stack:

- the /map topic is being published (to create global and local cost maps (costmap_2d objects))
- global_frame and robot_base_frame parameters are set 
- transform (tf) between  global_frame and robot_base_frame is being published (by your localization)
