### ISSUE TITLE
#include error doesnt seem to be fixable 

### ISSUE THREAD

**Issue by RomanOrion** [ros-planning/navigation#1259]
Hi, I've gone through multiple tutorials and the #include on multiple of the .h files still doesn't work. is there a specific way that it needs to be done with this application. its the "please update your includePath" issue 
thanks :)

**Comment by mikeferguson** [comment]
There isn't enough information to answer this question - and this really isn't the forum for debugging issues.

I'd recommend posting to https://robotics.stackexchange.com - and also including exact terminal outputs of the errors you are running into
