### ISSUE TITLE
inf_is_valid not present in Hydro layered costmaps

### ISSUE THREAD

**Issue by DLu** [ros-planning/navigation#128]
https://github.com/ros-planning/navigation/blob/groovy-devel/costmap_2d/src/costmap_2d_ros.cpp#L250

**Comment by piyushk** [comment]
@DLu I've started testing navigation code again. Is there an easy way to check your inf_is_valid code in Hydro?

I tried a couple of branches from your personal repo, but it seems like they are designed to compile in Groovy.

**Comment by DLu** [comment]
Try this branch: https://github.com/DLu/navigation/tree/inf_is_valid_hydro

On Tue, Oct 29, 2013 at 3:00 PM, Piyush Khandelwal <notifications@github.com
