### ISSUE TITLE
New Hydro Release?

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/navigation#132]
@DLu @hershwg Not sure who the maintainer here is, but can we get a new debian release? The version in debs right now lack the costmap clearing stuff and so performance is pretty bad -- I've tested the most recent trunk on our robot and seen huge improvements.

If you want, I can even run the release script to streamline this.

**Comment by DLu** [comment]
Looking into it.

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/2244

**Comment by mikeferguson** [comment]
Thanks!

**Comment by mikeferguson** [comment]
Actually, I think this is not correct, just looked at source and there is no new 1.11.4 tag, it appears you re-released the old 1.11.3 code as a new debian bump? This won't include the patches we actually want to get into hydro.

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/2250 looks good, all appears to be building on the farm too.

Thanks!
