### ISSUE TITLE
update test data url to download.ros.org

### ISSUE THREAD

**Issue by dirk-thomas** [ros-planning/navigation#133]
Please update the urls for test data from pr.willowgarage.com to download.ros.org.
- amcl/CMakeLists.txt
- carrot_planner/package.xml
- costmap_2d/CMakeLists.txt
- costmap_2d/package.xml
- move_base_msgs/package.xml
- robot_pose_ekf/CMakeLists.txt

Wiki links should point to wiki.ros.org.

**Comment by DLu** [comment]
Wiki links fixed previously with 26c5d7f8bd3c84ac1958419abd33afa63ab814e9

Test data urls fixed with #134
