### ISSUE TITLE
map_server: Please add option to also publish an Image topic

### ISSUE THREAD

**Issue by RainCT** [ros-planning/navigation#142]
Hi,

I'd be great if map_server would also publish the map as Image. That's useful for displaying it in UIs like tablets (esp. since Image also has compression support).

I can provide the code if someone agrees to review the patch.

Thanks

**Comment by DLu** [comment]
Greetings.
Is there a particular benefit for supporting Image publication in the
map_server node itself as opposed to using an intermediate node that just
does the translation from OccupancyGrid to Image?

I can review the patch eventually.

-DL!!

**Comment by RainCT** [comment]
Hi David,

I don't know that there's any special benefit, it mostly just seems cleaner. Right now we actually have a separate node doing this, but it's somewhat confusing to have both a map_server and an image_map_server (+ a million other small nodes doing things).

**Comment by DLu** [comment]
Would you create a new message type that also publishes the MapMetaData? Or
is it just a compression issue?

**Comment by RainCT** [comment]
Nope, only the image topic. It's compression, plus we are displaying the image directly in the Android application (if the raw OccupancyGrid was send compressed there'd still be the problem of making an image out of it).

**Comment by DLu** [comment]
Fair enough. Open up a patch.

**Comment by efernandez** [comment]
@RainCT Did you finally implement something? If not, I'll do it.

**Comment by RainCT** [comment]
Nope, open sourcing our relevant code turned out to be non-trivial
(dependencies on internal libraries) and also after thinking about it again
I changed my mind about there being a big benefit in having it in the same
binary.

Feel free to work on it though, it'd be nice to have something available in
ROS.

**Comment by mikeferguson** [comment]
original requester chose not to open source implementation
