### ISSUE TITLE
Recuperate costmap_2d::Costmap2DROS::updateMap()

### ISSUE THREAD

**Issue by corot** [ros-planning/navigation#143]
I cannot find this method on [Costmap2DROS API](http://docs.ros.org/api/costmap_2d/html/classcostmap__2d_1_1Costmap2DROS.html).

**Comment by acornacorn** [comment]
updateMap is a method of LayeredCostmap, not Costmap2DROS.

It is unclear what you are asking.  Can you elaborate?

**Comment by corot** [comment]
In Groovy and before, when you wanted to use navi stack costmaps in your program normally you use the costmap_2d::Costmap2DROS wrapper. In this case, makes sense to update the map when you really need it, so you call updateMap.

I tried to do the same with Hydro, but the updateMap is not there. So as you say, I should instead call

```
myCostmap.getLayeredCostmap().updateMap(origin_x, origin_y, origin_yaw)
```

right? In that case, recuperate costmap_2d::Costmap2DROS::updateMap() is trivial.

Btw, how are the origin_x, origin_y, origin_yaw parameters used? Must be the location of the robot in local map? and in global?

**Comment by DLu** [comment]
I have made a commit (reference below) that re-exposes the updateMap method. However, do you want a way to have the costmap only update when you run updateMap, thus disabling the update thread? 

https://github.com/DLu/navigation/commit/69cd4481210751f4720eac992f916a87258c81ae

**Comment by corot** [comment]
Cool! Thanks. Yes, I think that's the idea: only update when you want to
use the map so you don't spill CPU.

It's not enough setting update_frequency parameter to 0?

2013/11/7 David Lu!! notifications@github.com

**Comment by DLu** [comment]
Included in hydro now (not in debs yet)
