### ISSUE TITLE
upgrade robot_pose_ekf to conform with REP 105

### ISSUE THREAD

**Issue by tfoote** [ros-planning/navigation#15]
For @chadrockey 

Right now robot_pose_ekf is hard coded to transform from odom_combined to base_footprint, and relies on an external source to provide the tilt transform from base_footprint to base_link. 

This should be pulled into robot_pose_ekf such that it just transforms from odom -> base_link including roll and pitch.  And provides base_footprint as a backwards compatability option as a child of base_link.

**Comment by dayjaby** [comment]
This issue can be closed due to #701
