### ISSUE TITLE
navfn long plans don't start at the start

### ISSUE THREAD

**Issue by hershwg** [ros-planning/navigation#16]
When navfn is asked to make a plan which ends up being quite long, the plan that is returned starts somewhere between the start and goal and ends at the goal.  Usually such plans are not usable because they don't tell the robot which way to go from their current location.

Attached image shows start location as a yellow square in upper right and goal location as a green square on left side.  Generated path (in cyan) does not start at the start.

![navfn-bug](https://f.cloud.github.com/assets/2372515/34474/b553afc0-511f-11e2-82cf-1999f92a5711.png)

**Comment by hershwg** [comment]
Fixed by increasing the previous path length limit.  Old limit was map-width \* 4, but no indication why it was so low.  I changed it to map-area / 2, which should be enough for even the worst map.

There is a "cycle" limit in NavFn::propNavFnDijkstra() which is map-area / 20, which may be the new limiting factor on plan-able path length.  I'm not sure exactly what a single "cycle" means though, or how it relates to path length, so leaving alone for now.

**Comment by nightingale0131** [comment]
Hi, I ran into this issue again recently, on a much smaller map (see below).
The path is the cyan line, and the robot is in the lower right corner. As you can see, the path doesn't start from where the robot is, resulting in move_base aborting the goal.

The package version is 1.14.4, on kinetic.
![pathnotlongenough](https://user-images.githubusercontent.com/40846271/65543606-78f66e00-dedf-11e9-860d-52e0fc1b84ff.png)

**Comment by DLu** [comment]
That bug looks similar to the one presented here, but given the size of the map, I don't think it stems from the same problem. Can you open an answers.ros.org post with your configuration?

**Comment by nightingale0131** [comment]
Ok, I opened a question here: https://answers.ros.org/question/333873/why-does-navfn-return-a-path-that-doesnt-start-from-the-robot-location/

**Comment by fcelitok** [comment]
I also had the same problem and I solved it as increasing pathStep = 0.5 to pathStep = 1.0
