### ISSUE TITLE
Bump version for yaml-cpp compat

### ISSUE THREAD

**Issue by cottsay** [ros-planning/navigation#163]
Issue #140 was closed with a fix for yaml-cpp versions > 3, which is the default version on Fedora 20.

There were other packages which bumped versions for this issue, and this is the last one for which we need a version bump.

Thanks much.

**Comment by DLu** [comment]
Hi Scott. Thanks for the notice on this. I assume you want the bump for hydro?

**Comment by cottsay** [comment]
Yes! We're not targeting groovy on F20, and F19 has the old version of yaml-cpp.

Thanks much David Lu!!

**Comment by cottsay** [comment]
Closed via 166614ca97a637cf525c930d81fcb7b80c48d08c

Thanks!

**Comment by DLu** [comment]
Note that because of a bug, its not in the debs yet.

**Comment by cottsay** [comment]
Thanks, I'll keep that in mind. Fedora would be using the source install, so its pretty easy for me to pick up the version bump in the rosinstall.

Please close this when the bug is fixed.

Thanks @DLu!!

**Comment by bchretien** [comment]
:+1: Same problem for Arch Linux, so thanks!

**Comment by cottsay** [comment]
Current release has the fix, thanks!
