### ISSUE TITLE
Hardcoded tf frames and deprecated tf_prefix

### ISSUE THREAD

**Issue by muhrix** [ros-planning/navigation#167]
Since tf_prefix support was removed in Hydro, successfully having multiple instances of the same robot now depends on having unique literal strings of the frame_ids for each robot.

As a result, from my understanding, robots should presumably have unique `base_footprint` frames (e.g., `robot1_base_footprint`).

However, in robot_pose_ekf the tf frames are hardcoded to `odom_combined` and `base_footprint`, and hence it is not possible to have more than one `robot_pose_ekf` node running properly without using tf_prefix.

I have solved this issue already (and made sure it does not break current setups using tf_prefix), but I'm not sure whether a pull request would be welcome. Please, do let me know and I'll make a pull request explaining the changes.

This issue is related to issue #158, but note that output_frame_ is also used in line 425 of `odom_estimation_node.cpp` when broadcasting tf (with hardcoded `base_footprint`).

**Comment by mikeferguson** [comment]
Pull requests are generally welcome, and this does sound like something that should be exposed as a parameter in robot_pose_ekf.

**Comment by muhrix** [comment]
I have just made a pull request with the changes then.

**Comment by mikeferguson** [comment]
Fixed in #168 -- thanks for opening the pull request, sorry it tooks us eons to merge.
