### ISSUE TITLE
manifest.xml depends on non-exiting common_rosdeps

### ISSUE THREAD

**Issue by tkruse** [ros-planning/navigation#17]
this following the Instructions for desktop full install from source:

```
  [rosbuild] Building package map_server
  Failed to invoke /home/kruset/groovy_underlay/install_isolated/bin/rospack deps-manifests map_server
  [rospack] Error: package/stack 'map_server' depends on non-existent package 'common_rosdeps' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
```

This not just for map_server, but several other packages in the nav stack:

./stack.xml
./rotate_recovery/manifest.xml
./dwa_local_planner/manifest.xml
./costmap_2d/manifest.xml
./base_local_planner/manifest.xml
./carrot_planner/manifest.xml
./move_slow_and_clear/manifest.xml
./move_base/manifest.xml
./clear_costmap_recovery/manifest.xml
./navfn/manifest.xml

I guess just removing the dependency from manifest.xml should be okay, though I am not 100% sure about its implications.

**Comment by tfoote** [comment]
Yes common_rosdeps has been deprecated and empty for a few cycles and is
now gone.

**Comment by tkruse** [comment]
Duh, sorry. I assume this ticket can be closed now, did not see the commits.
