### ISSUE TITLE
multi robot dwa

### ISSUE THREAD

**Issue by aswinthomas** [ros-planning/navigation#195]
Hi,
I am using an omni robot and im pretty impressed with what dwa can do. Great work on the package.

I would like to extend the algorithm for a multiagent system that shares position and velocities. Could you provide any hint on what technique/algorithm I can use to extend the package? I was thinking of taking some ideas from the RVO library, but it only deals with spherical robots.

**Comment by DLu** [comment]
Can you discuss more what you mean by sharing position and velocities?

**Comment by aswinthomas** [comment]
I am sorry this was not clear. I meant that each robot communicates its own current position and velocity with others. The robots then must choose velocities that will avoid a collision with each other; in other words, mutual collision avoidance.

**Comment by aswinthomas** [comment]
Also, source code links for this package (http://wiki.ros.org/multi_robot_collision_avoidance) is no longer active. Any chance I can request for the backup from willow garage?

**Comment by DLu** [comment]
1) I cannot say precisely how such an algorithm would work, but to implement it within the dwa package, you would need another TrajectoryCostFunction. I have been developing an improved version of the dwa package to allow cost functions to use pluginlib and be compiled elsewhere. 
https://github.com/DLu/navigation/tree/groovy_plugin_planner

2) I don't know where the source for that is, but you could try contacting danielclaes@me.com
