### ISSUE TITLE
waitForTransform missing in base_local_planner/goal_functions

### ISSUE THREAD

**Issue by skohlbr** [ros-planning/navigation#196]
It appears there is a waitForTransform call missing before [transforming the plan here in L110 of goal_functions.cpp](https://github.com/ros-planning/navigation/blob/groovy/base_local_planner/src/goal_functions.cpp#L110). This pops up every once in a while on ROS Answers and users have traced the extrapolation error back to the previously mentioned transfom call. See examples: [1](http://answers.ros.org/question/63360/extrapolation-error-using-hector_mapping-move_base/), [2](http://answers.ros.org/question/106996/hydro-move_basetf2-extrapolation-error-into-the-future-errror/), [3](http://answers.ros.org/question/63360/extrapolation-error-using-hector_mapping-move_base/), [4](http://answers.ros.org/question/40541/extrapolation-error-of-local-cost-map-in-navigation/), [5](http://answers.ros.org/question/164911/move_base-and-extrapolation-errors-into-the-future/).

**Comment by bit-pirate** [comment]
:+1: 

I can confirm this. In my case this happens a lot when the robot gets stuck and replans many times. The fix provided in [5.](http://answers.ros.org/question/164911/move_base-and-extrapolation-errors-into-the-future/) works. I'll try to create PR soon.

**Comment by DLu** [comment]
:+1:

**Comment by HappySamuel** [comment]
Hi 
Is this issue really can be solved via adding waitForTransform in front of      
```
 // get plan_to_global_transform from plan frame to global_frame
      geometry_msgs::TransformStamped plan_to_global_transform = tf.lookupTransform(global_frame, ros::Time(),
          plan_pose.header.frame_id, plan_pose.header.stamp, plan_pose.header.frame_id, ros::Duration(0.5));
```
As i didn't see this solution being merged to the latest code, the waitForTransfom still remain absent in goal_functions.cpp

Best,
Samuel
