### ISSUE TITLE
Indigo doc job is failing

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/navigation#203]
http://jenkins.ros.org/job/doc-indigo-navigation/4/consoleFull

**Comment by mikeferguson** [comment]
@tfoote @dirk-thomas Any idea why this is timing out? I don't see any particular error that looks horrible, but the hydro doc job takes only ~4 minutes, and this is timing out after 60?

**Comment by dirk-thomas** [comment]
I would call all those error messages "pretty horrible":

```
error: Fatal error at line 3474740 column 9: unexpected end of file
error: Fatal error at line 3474740 column 9: error while parsing name
error: Fatal error at line 3474740 column 9: error while parsing element
error: Fatal error at line 3474740 column 9: error while parsing content
error: Fatal error at line 3474740 column 9: error while parsing element
error: Fatal error at line 3474740 column 9: error while parsing content
error: Fatal error at line 3474740 column 9: error while parsing main element
```

Running the same command locally I have exactly the same behavior - the doc build just hangs there forever.

**Comment by mikeferguson** [comment]
By horrible, I kinda meant "things aren't installing, something upstream is broken".

Any idea what is different between hydro and indigo? It looks like rosdoc_lite is the same version in both, and I'm building the same branch for both releases right now (we didn't fork for Indigo). So it's a doxygen problem then? I can't find any other doc jobs for indigo that are failing in a similar way...

**Comment by dirk-thomas** [comment]
It looks like the Indigo tag index is close to 4 GB in size - compared to 85 MB for Hydro. I would assume that this will affect all Indigo jobs. Not all might hit the timeout though.

**Comment by dirk-thomas** [comment]
E.g. http://jenkins.ros.org/view/Idoc/job/doc-indigo-ros_comm/ has the same problem.

**Comment by mikeferguson** [comment]
Do you think this is a rosdoc_lite issue then? or something else? I presume we need to open a ticket somewhere upstream...

**Comment by dirk-thomas** [comment]
I don't know yet.

**Comment by dirk-thomas** [comment]
The bloated tag files are definitely the reason why it takes so long. But we can't reproduce any increasing of size when run locally multiple times.

Since we have to get rid of the bloated files anyway I am going to wipe all Indigo docs :worried:
- https://github.com/ros-infrastructure/rosdoc_tag_index/pull/1
- as well as wipe http://docs.ros.org/indigo/tags
- trigger all Indigo doc jobs to regenerate their api doc (and getting rid of the 34 GB of data)

**Comment by mikeferguson** [comment]
Job has now succeeded. Thanks @dirk-thomas for tracking this down.
