### ISSUE TITLE
global_planner/GlobalPlanner doesn't set the orientation of the last point in the plan 

### ISSUE THREAD

**Issue by KaijenHsiao** [ros-planning/navigation#207]
TrajectoryPlannerROS (as it currently is) uses the orientation of the last point in the global plan to turn to once it reaches the goal position.  That works fine with NavFN, which copies the original goal (with orientation) onto the end of the list.  In global_planner's planner_core.cpp, however, pushing that point onto the list is commented out (line 299).  Any particular reason for that?  If you couple global_planner with TrajectoryPlannerROS the robot always turns to a yaw of 0.

**Comment by mikeferguson** [comment]
This is probably a question for @DLu

**Comment by KaijenHsiao** [comment]
So, apparently in move_base.cpp, function planService (which starts at line 392), there are the following lines:

``` C++
    p = req.goal;
    ...
        if(planner_->makePlan(start, p, global_plan)){
          if(!global_plan.empty()){
            global_plan.push_back(p);
```

which do (approximately) the same thing as line 299 in global_planner's planner_core.cpp.  

However, the equivalent does _not_ exist in move_base.cpp's makePlan function.  

@DLu, were you using planService and that's why you commented out the line in planner_core.cpp?  

It seems to me that inserting the goal as the last point in the global plan is something that should be done in individual planners, and not in move_base itself.  Also, regardless, whichever side it ought to be on, move_base's two functions should have the same behavior.  What do y'all think?  Should move_base insert it or should each global planner insert it?

**Comment by mikeferguson** [comment]
I would err on the side of "more functionality available" which means that move_base should not make assumptions about plans, and each planner should make a plan properly as it sees fit.

**Comment by KaijenHsiao** [comment]
I agree, which would argue for uncommenting the line in global_planner, which I'd be happy to submit a teensy pull request for.  But should we take out the lines in planService then, to make the two functions of move_base match?  That seems to me to be what it ought to look like, but it might break someone's code.

**Comment by mikeferguson** [comment]
So I hadn't expanded the code I was looking at when answering previously. I've now looked at the whole body of planService, and find it even more amusing.

nav_msgs/GetPlan says that tolerance is "If the goal is obstructed, how many meters the planner can relax the constraint in x and y before failing", however, if you look at how the loops are implemented, you actually start by evaluating (x-tolerance, y-tolerance, theta) and then iterating through by incrementally increasing y and x by map resolution_3.0 -- so for any tolerance not a multiple of 3_map resolution, you would never plan to the actual goal you want. Thus, I would say the proper set of fixes would be to:
- uncomment the push_back in the global planner
- update planService callback to run makePlan BEFORE the loop, and return just the exact plan that it generates if it can generate a plan -- this will make planService actually give you a plan to the desired goal if it exists even when specifying a tolerance as well as fixing the current issue, and allowing the (unreachable) goal pose to be added to plans that are generated to a goal other than the desired one when iterating up to the tolerance.

**Comment by KaijenHsiao** [comment]
Oh wow.  I hadn't looked that closely at planService before.  That's... um, interesting.  I'll send a pull request to fix it soon. :)

**Comment by KaijenHsiao** [comment]
Well, I put in a pull request like you described, with the addition of switching the search to being a widening-out-from-the-goal search.  

That includes adding the unreachable (original) goal pose to plans that are generated to a goal other than the original one.  I assumed you want that because the local planner might be able to get you there after all?  

That is, however, not the original behavior--previously the reachable goal was added to the end (for a second time, assuming the global planner already added it).  Also, if the goal is actually unreachable, it could be irritating to always feed the local planner the unreachable goal.  Let me know if you would actually prefer it not do that.

**Comment by mikeferguson** [comment]
> That is, however, not the original behavior--previously the reachable goal was added to the end (for a second time, assuming the global planner already added it).

The two identical points would probably be considered a bug, whereas I would say including the (potentially unreachable) goal is probably a design feature. The local planner might be able to get there once it gets close to the goal because whatever was obstructing the goal is gone.

**Comment by DLu** [comment]
I have no excuse for why that line was commented out of global_planner. 

One of my side goals with refactoring nav has been the ability to more intelligently handle inexact goals (go to somewhere in room 200) and some of the work I've done in refactoring move_base (https://github.com/DLu/navigation/tree/groovy_mbsplit) has been aimed at making that easier, but it hasn't been a priority for me.

**Comment by martimorta** [comment]
Hi, I've just noticed the same issue, do you know the release date for the new versions of the involved packages?
Thanks in advance!

**Comment by mikeferguson** [comment]
@martimorta I can put out a new release this afternoon, but hydro just sync'ed so it will be about 2 weeks before it ends up in the public repos (It would be in shadow-fixed within a day or so, barring any regressions that might occur with the upstream changes going on).

**Comment by martimorta** [comment]
Ok, thanks! I think I'll compile the source meanwhile, so the release follows the usual flow :)
