### ISSUE TITLE
ClearCostmapRecovery only clears children of ObstacleLayers

### ISSUE THREAD

**Issue by severin-lemaignan** [ros-planning/navigation#211]
This 'selection' is performed [here](https://github.com/ros-planning/navigation/blob/hydro-devel/clear_costmap_recovery/src/clear_costmap_recovery.cpp#L102). I'm not sure about the reason...

This makes it anyway difficult to develop custom layers that can be cleared as well (like [the sonar layer](https://github.com/DLu/navigation_layers/tree/master/sonar_layer)).

**Comment by DLu** [comment]
Would an array of layers to clear be sufficient?

**Comment by severin-lemaignan** [comment]
@DLu yes, it sounds like a good, flexible idea.

**Comment by mikeferguson** [comment]
Implemented in #230
