### ISSUE TITLE
Updates for J-Turtle

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/navigation#213]
J-turtle is more than a year away, so we are likely to forget about things. This ticket will track the things that should be done for J-turtle:
- Remove param and warning for acc_lim_th (https://github.com/ros-planning/navigation/commit/6721c998b3d1a17c224801086cccdaa2cfea0e73)
- Fix name of image_loader library (https://github.com/ros-planning/navigation/issues/208)
- Remove PCL (https://github.com/ros-planning/navigation/issues/264)

**Comment by DLu** [comment]
Should we start an actual branch to start accumulating these?

**Comment by mikeferguson** [comment]
We will, I figure around March or April. If we create a branch now, we'll have a lot of work to do keeping it in sync with bugfixes still going into indigo right now.

**Comment by mikeferguson** [comment]
As it stands, the only real improvement that has noticeable effects on folks is the base_global_planner change. We also don't have any work done towards the PCL stuff.

**Comment by DLu** [comment]
I was also thinking about some additional "breaking" changes, namely:
- Getting rid of the "footprint_layer" (which is really part of the obstacle layer)
- Changing DWA to be plugin-based.

**Comment by mikeferguson** [comment]
@DLu those both sound good. I think the best approach initially (as it sounds like those both entail some development) is to have feature branch for each of these new developments, which we can then merge in. If we have several good reasons to start the jade-devel branch earlier, we certainly can.

**Comment by mikeferguson** [comment]
Also, if you are going to modify DWA to be plugin-based, we should make sure to have a pretty significant code review of that. I can help out, and I imagine the Yujin guys would be interested in helping as well.

**Comment by mikeferguson** [comment]
Remove PCL has it's own ticket, I've handled the other items listed above in the new jade-devel branch
