### ISSUE TITLE
Could not get valid control when set to dwa_local_planner

### ISSUE THREAD

**Issue by dalishi** [ros-planning/navigation#215]
Hi guys

I dont know if here is a appropriate place to issue a question about the ros navigation package. I could not find help anywhere else. I am sorry if I am breaking some "rule" asking here.

I am using Fuerte navigation stack. Now I'm trying the dwa local planner by setting the below in move_base node
param name="base_local_planner" value="dwa_local_planner/DWAPlannerROS"

The problem is that the mova_base node warns that "Aborting because a valid control could not be found. Even after executing all recovery behaviors".

I then checked the DWAPlanner is able to publish a global_plan (according to the wiki: The portion of the global plan that the local planner is currently attempting to follow.) but no local plan published even though the goal point I put is just a small distance ahead.

Any idea about this? Thanks guys.

**Comment by mikeferguson** [comment]
Fuerte is more than 2 years old and is EOL. At this point, we cannot even release into Fuerte anymore as the build farm is torn down. A number of bugs in the local planners have been fixed since Fuerte was released, so you might take a look at those and see if any are relevant to you.

**Comment by mikeferguson** [comment]
> but no local plan published even though the goal point I put is just a small distance ahead

Just a note, if the planner failed to find a valid control, it will not have any plan to publish, so this is the expected behavior.

**Comment by dalishi** [comment]
Hi mikeferguson, thanks for the reply. We are planning to upgrade to the new version of ros. Thanks.

**Comment by asimay** [comment]
i come across this issue too, in indigo version, if I don't use recovery behavior. it still check recovery_behavior_enabled_
