### ISSUE TITLE
Wiki nav_core overview & move_base Class Diagram Google Drive

### ISSUE THREAD

**Issue by martimorta** [ros-planning/navigation#220]
Hi,
Just a couple of things from the wiki (I am not sure this is the right place to issue them but couldn't find a link in the wiki)
In http://wiki.ros.org/nav_core#Overview the image says nav_core::BaseLocaPlanner and should be nav_core::BaseLocalPlanner.
And in http://wiki.ros.org/move_base#Component_APIs the class diagram link says it is in the owners bin:
https://docs.google.com/drawings/d/1012j70nNhQJ12ol6usWmxOLPiNteOTS1Ai_qbtoObjY/edit

Thanks

**Comment by DLu** [comment]
Updated both. Thanks for the attention to detail.

**Comment by martimorta** [comment]
Thanks to you, so fast!
