### ISSUE TITLE
move_base crashes

### ISSUE THREAD

**Issue by jihoonl** [ros-planning/navigation#221]
move_base got crash. Can anyone help me to invest the problem? Where and how should I start to debug this? I was using `dwa_local_planner`.

```
[ERROR] [1404781596.512430073]: None of the points of the global plan were in the local costmap, global plan points too far from robot
[ERROR] [1404781596.512666184]: None of the 65 first of 65 (65) points of the global plan were in the local costmap and free
[ERROR] [1404781596.512841431]: None of the 65 first of 65 (65) points of the global plan were in the local costmap and free
[ERROR] [1404781596.513005453]: None of the points of the global plan were in the local costmap, global plan points too far from robot
move_base: /usr/include/pcl-1.7/pcl/conversions.h:247: void pcl::toPCLPointCloud2(const pcl::PointCloud<PointT>&, pcl::PCLPointCloud2&) [with PointT = base_local_planner::MapGridCostPoint]: Assertion `cloud.points.size () == cloud.width * cloud.height' failed.
[move_base-22] process has died [pid 26504, exit code -6, cmd /home/yujin/turtlebot/turtlebot/devel/lib/move_base/move_base cmd_vel:=navigation_velocity_smoother/raw_cmd_vel odom:=/odom __name:=move_base __log:=/home/yujin/.ros/log/8deb15ac-0638-11e4-8ad5-240a641bebf3/move_base-22.log].
log file: /home/yujin/.ros/log/8deb15ac-0638-11e4-8ad5-240a641bebf3/move_base-22*.log
```

**Comment by mikeferguson** [comment]
Whoa. That looks awesomely bad. Is this the stock turtlebot_navigation configuration on indigo?

Are you able to reproduce this at all, or was it a once off?

**Comment by jihoonl** [comment]
I saw `move_base` crashing three times in an hour.  I used [this configuration](https://github.com/yujinrobot/kobuki-x/blob/hydro-devel/waiterbot_suite/waiterbot_ctrl_cafe/param/move_base/dwa_local_planner_params.yaml) with custom kobuki which has infrared sensor array to detect local obstacles.

I have been using [our fork](https://github.com/yujinrobot/navigation) at yujinrobot repo so it would not be a problem with the current navigation stack.

Can you guide me where/how to start debugging this symptom? So I can report back later if I see this issue with current navi stack.

**Comment by DLu** [comment]
So there appears to be two separate problems here. For the first one (the points on the global plan), I would recommend inspecting the published global path visually in rviz and make sure its where you expect it. If it is, also turn on the local_costmap visualization and make sure it is around the robot and overlaps with the global path. Post screenshots if needed. 

The second problem (the point cloud based crash) is more puzzling. I suspect the problem is with publishing the ~~costmaps~~ _local planner data_, but I have no idea why.

**Comment by KaijenHsiao** [comment]
We see that crash regularly too, haven't had a chance to try to debug yet.

**Comment by jihoonl** [comment]
> So there appears to be two separate problems here. For the first one (the points on the global plan), I would recommend inspecting the published global path visually in rviz and make sure its where you expect it. If it is, also turn on the local_costmap visualization and make sure it is around the robot and overlaps with the global path. Post screenshots if needed.

alright.

> The second problem (the point cloud based crash) is more puzzling. I suspect the problem is with publishing the costmaps, but I have no idea why.

Ah now I remember @stonier mentioned about turning on `publish_traj_pc`,  `publish_cost_grid_pc` in dwa_local_planner configuration sometimes crashes the node.

**Comment by DLu** [comment]
I updated my above comment. It is the local planner data that is the problem, and not the costmap. 

Personally, I find that the data published from dwa_local_planner to not be formatted in an ideal way. There may be a better way to do get that data available if people use it.

**Comment by Karsten1987** [comment]
I've got the same issue on indigo. It happens to appear when changing the update frequency of the map via rqt_reconfigure_gui

**Comment by mikeferguson** [comment]
This is an ancient ticket, indigo is long dead.
