### ISSUE TITLE
allow_unknown setting in global_planner and navfn does not work

### ISSUE THREAD

**Issue by koenlek** [ros-planning/navigation#223]
To my knowledge, it is impossible to use the "allow_unknown" option provided by the global move_base planners navfn and global_planner.

I even made a fork and hardcorded their defaults to false, and still, if I give a goal in the unknown, it will plan a path going there. And if I give another goal in the known after that, it will pick a route through the unknown if that seems shorter than going back through the known space...

It seems like the functionality is completely broken. I use Hydro on Ubuntu 12.04, and the fork is based on a fetch of navigation a couple of months ago (I am not sure how to check what commit version I exactly forked, but all packages have version 1.11.8).

**Comment by KaijenHsiao** [comment]
If you are using an obstacle layer, you have to set its 'track_unknown_space' param to true, or else it takes all the unknown cells coming from the static layer and sets them to known (so the global planner just thinks it's planning through known space).

**Comment by koenlek** [comment]
Thanks that fixed the issue!
