### ISSUE TITLE
Example code or API

### ISSUE THREAD

**Issue by bvibhav** [ros-planning/navigation#228]
Hello,

I am not sure if i missed it somewhere while reading or not, But can someone guide to an example code to use this module.

I am trying to combine odometry from other sensor sources with IMU but can't figure out all the messages and topic I need to.

I always get error of transformation 'this frame' to 'base footprint' not done. Imu will not be used.

and there is not odom_combined.

Thank you

**Comment by DLu** [comment]
Did you work through http://wiki.ros.org/navigation/Tutorials ?
