### ISSUE TITLE
robot_pose_ekf does not install launch files

### ISSUE THREAD

**Issue by trainman419** [ros-planning/navigation#249]
As see on ROS Answers: http://answers.ros.org/question/192304/navigation-with-only-odometry/

(and confirmed by a quick read of the CMakeLists.txt for robot_pose_ekf)

**Comment by mikeferguson** [comment]
Are you planning to make a pull request for this? (I just didn't want to start one and collide with you)

**Comment by trainman419** [comment]
I have no plans to make a pull request for this.
