### ISSUE TITLE
map_sarver should be able to listen to topic names other than /map as hard coded

### ISSUE THREAD

**Issue by nrasulnrasul** [ros-planning/navigation#253]
map_save is hardcode to subscribed to topic name "map" , it should be passed from command line or roslaunch params.

https://github.com/ros-planning/navigation/blob/b384cac812381a9313d7cdc9be9eb272c4fccb38/map_server/src/map_saver.cpp#L51

**Comment by mikeferguson** [comment]
You can change the name of the map using remapping (http://wiki.ros.org/Remapping%20Arguments) for instance:

```
 rosrun map_server map_saver map:=your_other_topic_name
```

**Comment by nrasulnrasul** [comment]
What if 2 map available on different topics names map and map_other how to save both maps.

**Comment by mikeferguson** [comment]
You run map_saver twice, with two different sets of params.

**Comment by nrasulnrasul** [comment]
i mean when one topic id "map" and another is "temp_map" are available. Remapping doesnt work is saving both maps.

**Comment by mikeferguson** [comment]
I don't understand "remapping doesn't work is saving both maps".... Each running instance of the map server node listens to a single topic (named "map", but of course all ROS names can be remapped to a different name at node initialization). When it receives a message on that topic, it saves it to a file.

**Comment by nrasulnrasul** [comment]
I got it. thanks
