### ISSUE TITLE
Branch clean-up

### ISSUE THREAD

**Issue by bit-pirate** [ros-planning/navigation#255]
There a lot of branches in this repo and many of them look like test & development branches for new features. It is unclear, which are important/interesting/still in use. Also, this "noise" gets copied over, when forking. Could someone clean them up and move branches to private forks, where needed?

Also, it would be nice to have a indigo & indigo-devel branch.

**Comment by mikeferguson** [comment]
@bit-pirate I removed ~10 branches a week ago, I still have to review some of the others to decide which can/cannot go.

As for indigo -- we are for now not forking for indigo as there is currently no reason. We are able to support both Hydro and Indigo from a single branch, I imagine that we will fork when Hydro becomes EOL, but until then we are trying to maintain less overhead for people creating pull requests and the maintainers.

**Comment by bit-pirate** [comment]
> As for indigo -- we are for now not forking for indigo as there is currently no reason. We are able to support both Hydro and Indigo from a single branch, I imagine that we will fork when Hydro becomes EOL, but until then we are trying to maintain less overhead for people creating pull requests and the maintainers.

Roger. I can live with that. For newcomers it's a bit confusing though, but I agree the benefits outweight this drawback.

**Comment by mikeferguson** [comment]
I've just removed the branches that were clearly duplicated with releases. Branches we still need to clean up:
- navigation-1.8 (@hersh, @pmukherj any thoughts on this branch?)
- footprint-polygon-stamped (@hersh, seems this is not needed, and will never be merged, right?)
- costmap-plugin-layers-renamed (seems out of date, and costmap plugins have come a long way in 2 years, right @Dlu?)
- groovy (groovy-devel has everything that is groovy, is anyone using groovy branch?)

Branches that must remain:
- hydro-devel
- groovy-devel
- groovy-devel-catkinized (I think)

**Comment by hersh** [comment]
footprint-polygon-stamped is fine to abandon, probably no one wants that.  It's a small change that's easy to duplicate if someone does want it.

navigation-1.8 is the equivalent of either "electric-devel" or "fuerte-devel".  It is a relic of the previous release-branch naming scheme.

**Comment by DLu** [comment]
costmap-plugin-layers-renamed is good to disappear.

**Comment by mikeferguson** [comment]
Thanks!
