### ISSUE TITLE
Randomised variable?

### ISSUE THREAD

**Issue by stonier** [ros-planning/navigation#256]
https://github.com/ros-planning/navigation/blob/hydro-devel/base_local_planner/src/obstacle_cost_function.cpp#L139

```
double occ_cost = std::max(std::max(occ_cost, footprint_cost), double(costmap->getCost(cell_x, cell_y)));
```

This looks fishy. If not, it looks like it's compiling by accepting the reference to a not yet written variable value. 
It does rather look like it's been copied from https://github.com/ros-planning/navigation/blob/hydro-devel/base_local_planner/src/trajectory_planner.cpp#L306 where it has been properly instantiated in advance.

**Comment by DLu** [comment]
That looks pretty bad. 

A) Have you experienced problems with this?
B) Changing it to 

```
double occ_cost = std::max(std::max(0, footprint_cost), double(costmap->getCost(cell_x, cell_y)));
```

should fix it, right?

**Comment by stonier** [comment]
Haven't experienced problems with it as it seems from any tests that I did we almost always get back 0.0 as this uninitialised variable (no guarantees that this will always be true though). Only picked it up while our intern was perusing over the navigation stack parameters on an old configuration and working out what each one did and subsequently finding a few oddities.

The above fix should do the trick.
