### ISSUE TITLE
"Pause Navigation" functionality

### ISSUE THREAD

**Issue by MartinPeris** [ros-planning/navigation#259]
According to this question: http://answers.ros.org/question/193998/stoppingmoving-a-robot-during-navigation/ some users (me included) might find useful to incorporate a "pause navigation" functionality into move_base. This would allow to stop the robot during navigation using an external trigger and then continue the navigation at a later point in time without needing to cancel the current goal.

Is this something worth implementing? In such case, what would be the "smartest" way to do it? My first thought is to implement a "pause_navigation" service that would inhibit the publication of messages on the "cmd_vel" topic.

I am up for the coding task, but first I would like to know your thoughts.

**Comment by mikeferguson** [comment]
This is done on the PR2, turtlebot and several other robots by way of a mux on the cmd_vel output. The mux is used to switch between the PS3 joystick cmd_vel and the navigation cmd_vel output, so that as soon as you press the deadman on the PS3 joystick the robot stops moving and can be teleop-ed.

If all you are doing is interrupting the cmd_vel, that's probably best done outside move_base. The full solution would probably be to tell the local planner to stop updating and outputting commands, but continue returning success to move_base class.

**Comment by MartinPeris** [comment]
Hi Michael,
Thanks for your prompt reply. The mux solution is what I am currently using, but I have a question: can that cause move_base to abort the current goal?

**Comment by mikeferguson** [comment]
So, thinking it about it a bit more, I don't think any of the local planners are smart enough to realize they aren't making progress (@DLu, please correct me if that is wrong), and so the aborting part is outside the local planner.

I think the primary concern then is the "oscillation" check in the MoveBase class. If you stop the robot, then the oscillation pose/time will stop being updated (https://github.com/ros-planning/navigation/blob/hydro-devel/move_base/src/move_base.cpp#L833), which will then trigger recovery behaviors at (https://github.com/ros-planning/navigation/blob/hydro-devel/move_base/src/move_base.cpp#L917). You'll then get a series of recovery behaviors, and once those have been exhausted, it will eventually fail the goal (this can take quite a bit of time though). You could turn off the oscillation detection by setting the timeout to 0, but this could cause you to later get stuck oscillating somewhere.

The "ugly hack" fix which doesn't require any changes to navigation, would be to use the mux + a node that updates oscillation_timeout to 0.0 via dynamic reconfigure when you are "holding the robot". This node would then want to reset the timeout to its original value upon the robot being released.

A more proper fix would add a service (?) to "pause" the robot. Although, as I think about it, I'm not sure I really like the semantics of adding a service to "pause" an action. It really seems like higher-level logic that should be cooked into the application (as in, you would cancel the goal and then resend it when the issue had been resolved).

**Comment by MartinPeris** [comment]
mmmm yeah, thinking about it, cancelling the goal and resending it again seems the way to go.

I will give us a couple of days to think about this and, if no one else comes up with a good reason to implement the "pause navigation" service, I will close the issue.

**Comment by MartinPeris** [comment]
So, as no further suggestions have been received, I agree with @mikeferguson the "pause" functionality should be higher-level logic implemented outside the navigation stack by cancelling the current goal and resending it when appropriate.

Thank you for the discussion. I am closing the issue.

**Comment by positron96** [comment]
Hello. May I ask how to pause and set goal again if I use move_base_simple interface of move_base?

**Comment by mikeferguson** [comment]
The "simple" interface is just a topic, you should use the regular move_group interface, which is a ROS action, see the ROS actionlib client documentation on how to send and cancel goals

**Comment by renno-bih** [comment]
Any updates about this issue?
Is there any more elegant solution to pause navigation?

**Comment by faizansid77** [comment]
Any update yet?
