### ISSUE TITLE
allow_unknown parameter of navfn doesn't work

### ISSUE THREAD

**Issue by AlexReimann** [ros-planning/navigation#261]
The robot planes through unknown cells, no matter if the parameter is set or not.

I suspect the if  / else in line the following lin is wrong:
https://github.com/ros-planning/navigation/blob/hydro-devel/navfn/src/navfn.cpp#L244

Does if (v < COST_OBS_ROS)  also include cells with v == COST_UNKNOWN_ROS?
In this case the else part is never reached.

**Comment by mirzashah** [comment]
COST_UNKNOWN_ROS = 255, the highest value
https://github.com/ros-planning/navigation/blob/hydro-devel/navfn/include/navfn/navfn.h#L50

**Comment by KaijenHsiao** [comment]
Are you using a layered costmap from costmap_2d with an obstacle or voxel layer?  If so you have to set the param track_unknown_space for that layer to true, otherwise it's converting your map's unknown space into free space (which navfn then correctly goes quite happily through).

**Comment by jihoonl** [comment]
Thanks @KaijenHsiao. It helped to solve the problem. After setting up `track_unknown_space`, navfn does not plan a path through unknown space.

**Comment by mirzashah** [comment]
@KaijenHsiao thanks boss, i was running into the same issue! good to see you're still kicking ass :)

**Comment by KaijenHsiao** [comment]
Glad to be of help!  I added a note to the wiki under the allow_unknown param, so hopefully nobody else will get stuck in the same way.

**Comment by AlexReimann** [comment]
Thanks a lot!

**Comment by jihoonl** [comment]
FYI,
- [obstacles parameter description page](http://wiki.ros.org/costmap_2d/hydro/obstacles) is linked in allow_unknown param note.
- same note is added for [global_planner](http://wiki.ros.org/global_planner)

**Comment by Algabri** [comment]
I use track_unknown_space == true or false, didn't change for me.

**Comment by drtritm** [comment]
> I use track_unknown_space == true or false, didn't change for me.

same on me with ROS2

**Comment by DLu** [comment]
@Algabri @drtritmwin If you are having trouble with your configuration, please post on ROS Answers.

**Comment by li9i** [comment]
@Algabri @drtritmwin For ROS 1 at least, there is [this](https://answers.ros.org/question/316191/static_layer-gets-deleted-by-obstacle_layer-in-global_costmap/) link, which essentially places

```
unknown_cost_value: 0
lethal_cost_threshold: 100
```

under the `static_layer`. See also the order of layers for global and local costmap .yaml files. Typically they should be static-obstacle layer(s)-inflation. I hope this helps.

**Comment by MadhuriPatil1694** [comment]
@KaijenHsiao I also had the same issue robot was planning through unknown space and setting track_unknown_space == true did solve it. But now I can see multiple plans when the robot is close to the edge which reduces the speed of the robot. How can i avoid it.
