### ISSUE TITLE
Remove dependency on PCL

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/navigation#264]
Sensor_msgs now includes a C++ iterator for pointcloud2 messages, we should use this in costmap updater to avoid a dependency on PCL. 

As mentioned in https://github.com/ros/common_msgs/pull/16 this probably needs a tf/tf2 sensor_msgs::PointCloud2 transform to be implemented.

**Comment by vrabaud** [comment]
Hi, this has actually been implemented:
https://github.com/ros/geometry_experimental/blob/indigo-devel/tf2_sensor_msgs/include/tf2_sensor_msgs/tf2_sensor_msgs.h
Now, navigation actually needs to switch to tf2 before that happens. #298 is here for that.

**Comment by mikeferguson** [comment]
So, Jade has come and gone years ago. @DLu -- I'm planning to work on this in the next few weeks, and I'm targeting Melodic.

**Comment by mikeferguson** [comment]
Remaining PCL items:

 * navfn_ros.h/cpp uses pcl_publisher -- needs to be converted to sensor_msgs iterator
 * base_local_planner/map_grid_visualizer.h -- uses pcl_publisher
 * dwa_local_planner still depends on PCL, but I can't find any usage.

**Comment by moriarty** [comment]
> dwa_local_planner still depends on PCL, but I can't find any usage.

```
________________________________________________
Errors     << dwa_local_planner:make /home/fetch/melodic-stable/logs/dwa_local_planner/build.make.000.log                                                                                                         
In file included from /opt/ros/melodic-stable/include/base_local_planner/map_grid_visualizer.h:40:0,
                 from /home/fetch/melodic-stable/src/navigation/dwa_local_planner/include/dwa_local_planner/dwa_planner.h:47,
                 from /home/fetch/melodic-stable/src/navigation/dwa_local_planner/src/dwa_planner.cpp:37:
/opt/ros/melodic-stable/include/base_local_planner/map_grid_cost_point.h:37:10: fatal error: pcl/register_point_struct.h: No such file or directory
 #include <pcl/register_point_struct.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Your branch is probably still a work in progress but I tried to compile it and found these usages

```
fetch at fetch3 in ~/melodic-stable/src/navigation/dwa_local_planner on remove_pcl
$ grep -r pcl . -n
./src/dwa_planner.cpp:49:#include <pcl_conversions/pcl_conversions.h>
./src/dwa_planner.cpp:162:    traj_cloud_ = new pcl::PointCloud<base_local_planner::MapGridCostPoint>;
./src/dwa_planner.cpp:329:        pcl_conversions::fromPCL(traj_cloud_->header, header);
./src/dwa_planner.cpp:331:        traj_cloud_->header = pcl_conversions::toPCL(header);
./include/dwa_local_planner/dwa_planner.h:48:#include <pcl_ros/publisher.h>
./include/dwa_local_planner/dwa_planner.h:162:      pcl::PointCloud<base_local_planner::MapGridCostPoint>* traj_cloud_;
./include/dwa_local_planner/dwa_planner.h:163:      pcl_ros::Publisher<base_local_planner::MapGridCostPoint> traj_cloud_pub_;
```

**Comment by mikeferguson** [comment]
@moriarty that PR was less "work in progress" and more "wishful thinking" :)

**Comment by mikeferguson** [comment]
Boom. Done. Ship It.

Thanks @moriarty @DLu @vrabaud
