### ISSUE TITLE
Layered costmap

### ISSUE THREAD

**Issue by ndeshp2s** [ros-planning/navigation#278]
Hello,

I am a newbie to ROS and especially the 2d_nav stack. So please pardon me if my query sounds to petty.

I have been reading the literature about the Layered costmap recently. I would like to use something similar. To be precise, I would like to add one layer and use the information in this layer during the planning process.

However, I am not very clear yet how the layered costmap works. Are there different layeres existing and the information at all layers is combined to form a final layer which is basically combination of say the inflation radii at different layers? Or information about each layer is maintained and fe to the planner? Or its something else?

Please le me know if you have any information about this.

Thank you in advance.

**Comment by DLu** [comment]
This kind of question probably belongs on answers.ros.org, but I'll answer briefly here. 

By literature, I assume you mean [my paper on LayeredCostmaps](http://www.cse.wustl.edu/~dvl1/?p=200). It has all the good info in it. There's also my [ROSCon talk](http://www.cse.wustl.edu/~dvl1/?p=215). 

There are different layers that are combined to create the master ("final") layer. The master layer is the one used for planning. However, all of the information is individually maintained in the layers themselves.

**Comment by ndeshp2s** [comment]
Hello,

First of all I apologize for the delay in replying to you.

And thank you for your reply. I will go through the talk you hav ementioned about. And get to you if I have more queries?

**Comment by DLu** [comment]
Please raise additional queries through answers.ros.org.
