### ISSUE TITLE
DWA potential map flickering / costmap locking

### ISSUE THREAD

**Issue by AlexReimann** [ros-planning/navigation#287]
There is a problem with the dwa accessing the costmap throught costmap_.getCost for scoring the trajectories. [The LayeredCostmap class resets (a part of) the costmap at one point](https://github.com/ros-planning/navigation/blob/b98f1be4c99df7fe8794e009a9f6d8714ab4b6d0/costmap_2d/src/layered_costmap.cpp#L115) and it can be accessed before it is filled again.

Doesn't happen often (depends on the frequency of the costmap update) but is visible.
Our case was dwa at 8 Hz and local costmap at 10 Hz.

Also I think there are locks missing [here](https://github.com/ros-planning/navigation/blob/b98f1be4c99df7fe8794e009a9f6d8714ab4b6d0/costmap_2d/src/costmap_2d.cpp#L290), [here](https://github.com/ros-planning/navigation/blob/b98f1be4c99df7fe8794e009a9f6d8714ab4b6d0/costmap_2d/src/costmap_2d.cpp#L331) and [here](https://github.com/ros-planning/navigation/blob/b98f1be4c99df7fe8794e009a9f6d8714ab4b6d0/costmap_2d/src/costmap_2d.cpp#L470). If that stuff is even used..

@bit-pirate

**Comment by mikeferguson** [comment]
My initial impression after debugging some other move_base stuff is that much of the locking logic in the nav stack is probably in need of a review. Pull requests are certainly welcome on this.

**Comment by AlexReimann** [comment]
I guess I will make a quick and dirty fix for this issue, but I think it is a [design flaw](http://en.wikipedia.org/wiki/Law_of_Demeter) that should be addressed somewhen.. too much of giving the costmap pointer to everyone.

**Comment by AlexReimann** [comment]
Seems like this is actually a feature:
In the case that the robot is oscillating in a local minimum, using a empty obstacle map sometimes helps to get out of the minimum.
Might be just coincidence but seems to help quite noticeably.

It still should be fixed though. I was not able to find an easy solution to this. Adding a lock for the access during the time the costmap is empty gives a deadlock.

**Comment by mikeferguson** [comment]
this should be addressed by https://github.com/ros-planning/navigation/pull/334
