### ISSUE TITLE
Map server should crop unknown space

### ISSUE THREAD

**Issue by hershwg** [ros-planning/navigation#3]
[Originally reported by moesenle on kforge trac]

It happens too often that people create a really large map (e.g. 200x200m, 2.5cm resolution ~ 64mb) that mostly contain unknown space. Such large maps actually caused rviz to eat up all my memory during the PR2 workshop last week. That makes be believe that it would be best if the map server actually crops everything that doesn't really contain any information, i.e. that's unknown space.

Find a patch for cropping the map attached.. I added a ros parameter crop that allows for enabling (currently default) or disabling that functionality.

[Download link for original attachment]
https://kforge.ros.org/navigation/trac/raw-attachment/ticket/5/map-server-crop-map.patch

**Comment by DLu** [comment]
I don't think this should be implemented here (in map_server). Since the size of the global costmap is based on the size of the static map, you might want to leave unexplored regions of the map available. 

I think this would be better put into the map_saver with the (automatic) option to crop. 

Anyone feel strongly either way?

**Comment by corot** [comment]
+1 to map_saver

Another usecase is maps without defined limits (typically on simulations,
like gazebo turtlebot demo)

2013/11/8 David Lu!! notifications@github.com

**Comment by dornhege** [comment]
+1 map_server just serving the map without modification sounds the most intuitive to me.

**Comment by mikeferguson** [comment]
seems there is a consensus that we don't want to implement this feature -- and the patch has also been lost when kforge was shutdown
