### ISSUE TITLE
param to prevent updateCosts() in layer

### ISSUE THREAD

**Issue by aswinthomas** [ros-planning/navigation#302]
Currently the only way to retain information in a costmap layer, and not copy it into the master layer is to write a custom plugin with no updateCosts() method implemented. 

Could we have a parameter that prevents updateWithOverwrite() or updateWithMax()?

This is to enable the planner to behave differently for lethal obstacle in layer 1 compared to that in layer 2

**Comment by DLu** [comment]
Is the idea that you can dynamically switch between layer 1 and layer 2? Otherwise I'm not sure why you would store things in a layer in the first place.

**Comment by aswinthomas** [comment]
Lets say we have 5 layers having obstacles that you should not cross e.g. walls
and 2 layers with zones that should be avoided but not impossible to cross e.g. lane markings

In the current version, all the information in these layers are copied over to the master map. making the robot avoid obstacles in all the above layers. 
If we have a param called copy_to_master = false for the last 2 layers, then the planner will avoid only the first 5 layers. In addition to this, the planner can extract data from the last 2 layers and perform additional behaviors/costs for them.

**Comment by DLu** [comment]
Would something like this work?
https://github.com/DLu/navigation/compare/no_combine

**Comment by aswinthomas** [comment]
I think so, yes!

**Comment by mikeferguson** [comment]
Addressed by #306
