### ISSUE TITLE
robot_pose_ekf: PoseWithCovarianceStamped message hard coded to odom

### ISSUE THREAD

**Issue by hsmrs** [ros-planning/navigation#313]
Hey everyone,

I noticed that in line 393 of odom_estimation.cpp in robot_pose_ekf the PoseWithCovarianceStamped message is hard coded to the "odom" frame instead of using the output_frame_ variable. This seems to me like a bug. I am currently working around it by creating a node to publish the message with the correct frame, but it would be nice to have this fixed.

Thanks!

**Comment by mikeferguson** [comment]
It seems that maybe it should be set to "output_frame_"? I don't have any time to debug and be sure -- but tested pull requests are definitely very welcome.

**Comment by hsmrs** [comment]
That is my impression as well. Unfortunately I am also in your situation, with no time to debug and test properly if I made the change.

**Comment by protobits** [comment]
Found the same issue. I think it is a trivial change, this is just output data, so I think it couldn't really affect anything.

**Comment by emilyfy** [comment]
I found it too after wondering why the published topic is on "odom" frame. Tried changing it to output_frame_ and it fixes it and seems to work well.
