### ISSUE TITLE
move_base crashes when call clear_costmaps service

### ISSUE THREAD

**Issue by corot** [ros-planning/navigation#32]
On hydro-devel

[FATAL] [1367287395.368348831]: ASSERTION FAILED
        file = /home/turtlebot/cafe_solution/src/navigation/costmap_2d/src/voxel_costmap_2d.cpp
        line = 102
        cond = end_x > start_x && end_y > start_y
[move_base-29] process has died [pid 4576, exit code -5, cmd /home/turtlebot/cafe_solution/devel/lib/move_base/move_base cmd_vel:=navigation_velocity_smoother/raw_cmd_vel __name:=move_base __log:=/home/turtlebot/.ros/log/9bb59ce8-b139-11e2-892c-20689dee2463/move_base-29.log].

**Comment by hershwg** [comment]
Hi corot, thanks for the report.  Can you rebuild with the latest change here and close the bug if it fixes it for you?

**Comment by corot** [comment]
Perfect now.
Btw, I cannot add labels. Any idea why?

**Comment by hershwg** [comment]
Github does not allow people without "push" permission to label issues, so it's up to us, the owners of the repo, to label issues.
