### ISSUE TITLE
Publishing Rolling Costmaps Incrementally

### ISSUE THREAD

**Issue by DLu** [ros-planning/navigation#333]
[As seen here](http://answers.ros.org/question/207755/rviz-doesnt-update-rolling-window-costmap-origin/)

Using [OccupancyGridUpdate](https://github.com/ethz-asl/map_msgs/blob/master/msg/OccupancyGridUpdate.msg) will publish the data of the costmap incrementally, but there is currently no way using that message to update the [OccupancyGrid's origin pose](http://docs.ros.org/api/nav_msgs/html/msg/MapMetaData.html)

That data could also be published as a Pose message, but that makes a three-topic channel from what used to be one (bloated) channel.

**Comment by DLu** [comment]
@stephanemagnenat Thoughts?

**Comment by stephanemagnenat** [comment]
Updating the pose would imply shifting all data. What use case do you envision?
