### ISSUE TITLE
Simulation with no laser. Robot does not follow the global plan

### ISSUE THREAD

**Issue by Dio-Eraclea** [ros-planning/navigation#347]
Hello,
I am trying to run simulation in stage with navigation. I am using ROS Indigo with navigation 1.12.0. I want to run simulation without using laser scanner, as I want to try navigation with Lego Mindstorms robot, which has no laser. But when I exclude laser from observation_sources in costmap_common_params.yaml, robot stops following the global plan and starts moving strait towards the goal and hits the obstacles. With laser all works fine. With no obstacles on the map all works fine also. If the global path is long enough, robot follows it for a while, but then changes direction. 

My costmap_common_params are:

map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 9
mark_threshold: 0
transform_tolerance: 0.3
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
footprint_padding: 0.01
inflation_radius: 0.55
cost_scaling_factor: 10.0
lethal_cost_threshold: 100

My costmap_global_params are:

global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: false
  footprint_padding: 0.02

My costmap_local_params are:

local_costmap:
  publish_voxel_map: true
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0

My base_local_planner_params are:

TrajectoryPlannerROS:
  acc_lim_th: 3.2 
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  max_vel_x: 0.65
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4
  escape_vel: -0.1
  holonomic_robot: true
  y_vels: [-0.3, -0.1, 0.1, -0.3]
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true
  oscillation_reset_dist: 0.05
  prune_plan: true

I tried to change several parameters but got nothing. Please give me an advice what can I do to make it working.

**Comment by mikeferguson** [comment]
This question is really a usage question and belongs on answers.ros.org.

As for this specific question -- you need to have a static map in your local cost map in order to have the local planner not drive through the obstacles.
