### ISSUE TITLE
Is move_base's parameter clearing_rotation_allowed actually working?

### ISSUE THREAD

**Issue by corot** [ros-planning/navigation#38]
Setting clearing_rotation_allowed parameter as false doesn't prevent the robot to make in place rotations as it's supposed to do (to my understanding of the wiki documentation). In fact, it looks like the parameter value has no effect at all.

There'is any problem or I misunderstood the use of this parameter?

**Comment by hershwg** [comment]
From the wiki (and confirmed by reading the source code):

"clearing_rotation_allowed (bool, default: true): Determines whether or not the robot will attempt an in-place rotation when attempting to clear out space. _Note: This parameter is only used when the default recovery behaviors are in use, meaning the user has not set the recovery_behaviors parameter to anything custom._"

If you have a "recovery_behaviors" section in your move_base parameters, that makes clearing_rotation_allowed be ignored.  If you have such a section and it contains a recovery behavior called "rotate_recovery" then just take it out.

However, I will say that sadly there are tons of situations that can make a robot just rotate in place which are not related to rotate_recovery.  Eliminating all of them is a subject too long for this bug discussion.

**Comment by corot** [comment]
mmm....  but I'm using default recovery behaviors, and the log says "rotating to clear costmap" or something like this, so I think is a recovery behavior what makes the robot spins.

**Comment by hershwg** [comment]
Well OK then! :)  Sorry, I didn't realize how clear your situation was.

What version of move_base are you running?

**Comment by hershwg** [comment]
Looks like it is a spelling error in the code.  The code is waiting for "clearing_roatation_allowed".  Sigh.

**Comment by corot** [comment]
Cool! it will be very useful to me. Do u want me to do a pull request? 

Btw, I use hydro-devel sources.

**Comment by hershwg** [comment]
You can use it right away by misspelling the parameter in your rosparams the same way it is misspelled in the code.  I'll get a fix in later today.
