### ISSUE TITLE
Costmap2DPublisher::publishCostmap() publishing update instead of full costmap if only height changes when resized

### ISSUE THREAD

**Issue by chocolatechipcookie** [ros-planning/navigation#382]
The test for whether the complete map needs to be published is missing the condition:

```
grid_.info.height != costmap_->getSizeInCellsY()
```

This causes heap corruption (and eventually segmentation fault) in the subscriber's static layer when the costmap is resized in height, and an update is published instead of the full map.  The update bounds exceed the static layer's costmap size, and since there are no bounds checking in the update callback StaticLayer::incomingUpdate(), a section of heap memory beyond the costmap array is written to which later causes a segmentation fault (generally when the publishing costmap's width is resized and an attempt is made to free the layered costmap's array before allocating a larger array).

Setting always_send_full_costmap to true acts as a workaround.

**Comment by DLu** [comment]
This was an attempt at a minor optimization that is more problematic than intended.
