### ISSUE TITLE
Using Move_Base with Husky A200 in Gazebo 1.9 + ROS Hydro

### ISSUE THREAD

**Issue by ktiwari9** [ros-planning/navigation#387]
Hi there,
I am using ROS Hydro and Gazebo 1.9 and I want to write a simple move_base node that can move the husky from point (3,1) to (-3,1) in Gazebo. I am following the source code from https://github.com/ras-sight/hratc2015_entry_template/blob/master/examples/cpp/random_walk_navigation.cpp but the problem is, I cannot move the husky in Gazebo. I need some help with move_base. Can somebody help me with this code ?

**Comment by DLu** [comment]
Hi Kshitij, 
Please use answers.ros.org for this type of request, and only use the issue tracker for reporting specific issues. Thanks!
