### ISSUE TITLE
map_server should provide the map via an actionlib server

### ISSUE THREAD

**Issue by jonbinney** [ros-planning/navigation#39]
Since sometimes it is nice to use something based on messages instead of a service.

**Comment by jonbinney** [comment]
(you can assign this to me)

**Comment by hershwg** [comment]
Seems fine, probably the easiest way to solve your problem, and doesn't hurt map_server's design as far as I'm concerned.

**Comment by jonbinney** [comment]
It looks like the GetMap service definition is in nav_msgs; is that also the right place to put the action definition for the GetMap Action?

**Comment by hershwg** [comment]
yes.

**Comment by AchmadFathoni** [comment]
Oldest open issue

**Comment by jonbinney** [comment]
Unassigned this, since I won't have time to work on it. Shouldn't be too hard if anyone has the time.

**Comment by DLu** [comment]
I'm not sure what the advantage would be of having an action server instead of either a topic or service. If there's something that you don't want to block until the map is received, the you should probably just subscribe to the topic.
