### ISSUE TITLE
latch_xy_goal_tolerance_ is never set in latched_stop_rotate_controller

### ISSUE THREAD

**Issue by hershwg** [ros-planning/navigation#4]
[originally reported by kluessen on kforge trac]

the boolean latch_xy_goal_tolerance_, declared in Line 88 in latched_stop_rotate_controller.h,
is used a lot in the latched_stop_rotate_controller.

It is never initialized, but it is essential for the isGoalReached() function to return true.
Line 84, Line 88 in latched_stop_rotate_controller.cpp

**Comment by mikeferguson** [comment]
Fixed by #193
