### ISSUE TITLE
Non-rectangular local costmaps

### ISSUE THREAD

**Issue by makokal** [ros-planning/navigation#400]
Are there any plans to have non-rectangular local costmaps, which would reflect a more realistic state of real world robots? Something more of a semi-circle or a sector?

**Comment by mikeferguson** [comment]
There are no such plans. Non-rectangular costmaps would require a significant change to the API given the way that updates propagate through layers.

**Comment by DLu** [comment]
Such a change would change the fundamental data structure as well, in addition to the API. 

Besides the efficiency of carving off the edges of a square costmap into a circle, are there other benefits to changing the shape?

**Comment by makokal** [comment]
@DLu 
Well, when designing specific behavior, say w.r.t people in the scene, I noticed standard local planners like `DWA` or `Eband`try to react as soon at the local cost map changes. When robot moves is curves, I notice sometimes my planner reacting a change that I would not want to (or that a circular local cost map would not take into account, like stuff much far behind). So it does affect behavior design.

**Comment by DLu** [comment]
@makokal Just so I'm clear, are you seeing DWA change where it plans based on obstacles in the local costmap behind it?

**Comment by makokal** [comment]
@DLu No, that is handled by DWA theory, maybe the example for not appropriate, rather my concern is is that I want to update local behavior (read local plan) when local cost map changes (but only in some region in the front). I suppose I can use additional layer to do this, but a customisable local cost map shape would make it easier.

**Comment by DLu** [comment]
It seems as though it would be easier to write something that detected where changes happened within a rectangular layer rather than to change the underlying data structure.

**Comment by makokal** [comment]
That is what I have so far, but needed to check plans just in case

**Comment by mikeferguson** [comment]
Closing as non-rectangular local costmaps are not a feature we intend to implement
