### ISSUE TITLE
Voxel Layer Lacks Method for Changing Combination Mode

### ISSUE THREAD

**Issue by DLu** [ros-planning/navigation#402]
The obstacle layer has a combination_mode dynamic reconfigure parameter, but the voxel layer lacks this option.

**Comment by mikeferguson** [comment]
Since this breaks API, targeting melodic

**Comment by mikeferguson** [comment]
Looks like this was actually (mostly) done in https://github.com/ros-planning/navigation/commit/88e802d89a28d5dbee0ce10ab3c0ab1931830e30 -- note the parameter is called "combination_method" not mode (but that is same in both classes). The voxel layer does lack the nothing option, which I'm adding.

**Comment by mikeferguson** [comment]
Is in PR -- closing so I can keep track of what we have to actually still do before release!
