### ISSUE TITLE
Release version out of sync

### ISSUE THREAD

**Issue by rctoris** [ros-planning/navigation#418]
It looks like the released version according to the changelogs for indigo is `1.12.7` but rosdistro only knows about `1.12.6` -- https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml#L5834

**Comment by mikeferguson** [comment]
I'm looking into this... maybe I didn't finish the release...

**Comment by mikeferguson** [comment]
Not sure how I failed to finish blooming -- but fixed by https://github.com/ros/rosdistro/pull/10437
