### ISSUE TITLE
Update costmap layers wikis; they date from hydro and many parameters are not documented

### ISSUE THREAD

**Issue by corot** [ros-planning/navigation#439]
e.g. the following static layer parameters are not documented:
- first_map_only
- subscribe_to_updates
- track_unknown_space
- use_maximum
- trinary_costmap

**Comment by ledmonster** [comment]
I got very confused by old documents, until I read original source codes. I'd be very happy if documents would be updated.

**Comment by DLu** [comment]
http://wiki.ros.org/action/diff/costmap_2d/hydro/staticmap?action=diff&rev1=5&rev2=6

**Comment by mikeferguson** [comment]
Thank you David Lu!
