### ISSUE TITLE
Installation for ROS Indigo

### ISSUE THREAD

**Issue by brianzhan** [ros-planning/navigation#443]
Hi, it would be great for future users if installation instructions could be posted for ROS indigo users. The build is not smooth (for example, rosdep, the first step, doesn't work), and the sudo apt-get for this is broken

**Comment by DLu** [comment]
Hi @brianzhan. Please open an answers.ros.org post and include 
- What OS you're running
- Which installation instructions you are following
- Specific error messages. 

Thanks. If there is a bigger problem, we can reopen the ticket and take action from there.
