### ISSUE TITLE
[map_server] Improve fall-back behavior for new "mode" field in map.yaml

### ISSUE THREAD

**Issue by stwirth** [ros-planning/navigation#473]
https://github.com/ros-planning/navigation/pull/422 introduced a new variable `mode` for the interpretation of pixel values and removes the previously used `trinary` flag.
If `mode` is not set, it is simply assumed that the mode is `trinary`: https://github.com/ros-planning/navigation/blob/indigo-devel/map_server/src/main.cpp#L128-L130

I want to propose the following improvements:
1. If the `mode` flag is not set, emit a ROS_WARN that reminds the user to upgrade the map.yaml file to the new format.
2. If the `mode` flag is not set but a `trinary` field is present in the yaml, set the mode to `TRINARY` if `trinary` is true and to `SCALE` if `trinary` is false.
3. If both `mode` and `trinary` are present in the yaml, emit a ROS_WARN that the `trinary` field will be ignored (and ignore the `trinary` field).

**Comment by AchmadFathoni** [comment]
Oldest open issue

**Comment by aaronhoy** [comment]
This seems reasonable, although I could also see an argument for not ever using the "trinary" flag itself and simply warning that it is deprecated.

Also if I'm not mistaken, any fields applicable to trinary are also applicable to scale, so automatically selecting trinary based on other fields might not be what we want to do.

If you're still interested, why don't we create a PR with the proposed changes and refine it from there.

**Comment by stwirth** [comment]
I have a workaround in place for my use case, so I don't need this feature. However, I'd be happy to chime in on a PR discussion.

**Comment by DLu** [comment]
Solution in #474

**Comment by DLu** [comment]
Per discussion in #474, closing this until it becomes a problem again.
