### ISSUE TITLE
min_in_place_rotational_vel and min_in_place_vel_theta

### ISSUE THREAD

**Issue by willdzeng** [ros-planning/navigation#487]
In the source code of trajectory_planner_ros.cpp the inplace turning velocity is called

> min_in_place_rotational_vel

but in the ros package wiki it's called 

> min_in_place_vel_theta

**Comment by spmaniato** [comment]
Which wiki page(s) specifically?

Here's what I'm seeing (with a shallow search):
- http://wiki.ros.org/base_local_planner ➡️ `min_in_place_vel_theta`
- [base_local_planner / trajectory_planner](https://github.com/ros-planning/navigation/search?utf8=%E2%9C%93&q=min_in_place_vel_theta) ➡️ `min_in_place_vel_theta`
- [base_local_planner / trajectory_planner_ros](https://github.com/ros-planning/navigation/search?utf8=%E2%9C%93&q=min_in_place_rotational_vel) ➡️ `min_in_place_rotational_vel`
  - This line is interesting: 

``` cpp
private_nh.param("min_in_place_rotational_vel", min_in_place_vel_th_, 0.4);
```

So I guess there is an inconsistency. Is this what you are referring to?

## 

@DLu, did commit 6e0e3e1d07d8abbb730bb1b5fe6a25deea74deb3 from 2013 ever make it to the latest releases? (Also see discussion in #90) Among other things, I think it addresses this very issue:

``` cpp
if(private_nh.hasParam("min_in_place_rotational_vel"))
      {
        ROS_WARN("Please use min_in_place_vel_theta instead of min_in_place_rotational_vel");
        private_nh.param("min_in_place_rotational_vel", min_in_place_vel_th_, 0.4);        
      }
      else
      {
        private_nh.param("min_in_place_vel_theta", min_in_place_vel_th_, 0.4);
      }
```

I can't find a branch that contains it:

``` shell
$ git branch --contains 6e0e3e1d07d8abbb730bb1b5fe6a25deea74deb3
error: no such commit 6e0e3e1d07d8abbb730bb1b5fe6a25deea74deb3
```

**Comment by willdzeng** [comment]
yeah,

http://wiki.ros.org/base_local_planner
wiki page said the parameter's name is 

> min_in_place_vel_theta

but the parameter name is actually

> min_in_place_rotational_vel

I guess the commit you mentioned didn't get in.

Also, even when I increase the min_in_place_rotational_vel, the planner also sometime send small in place turning velocity. Do you have any idea why?

for example I have parameters:

```
  acc_lim_x: 4.0
  acc_lim_theta:  1.5

  max_vel_x: 1.0
  min_vel_x: 0.5

  max_vel_theta: 5.0
  # min_vel_theta: -5.0
  min_in_place_rotational_vel: 3.0

  holonomic_robot: false
  escape_vel: -0.4

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: true

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 25
  controller_frequency: 20.0

  # Trajectory scoring parameters
  meter_scoring: false # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
  occdist_scale:  0.1 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  pdist_scale: 0.75  #     The weighting for how much the controller should stay close to the path it was given . default 0.6
  gdist_scale: 1.0 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

  heading_lookahead: 0.2  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  heading_scoring_timestep: 0.8   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
  dwa: false #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
  simple_attractor: false
  publish_cost_grid_pc: true  

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.5 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.2
  escape_reset_theta: 0.3
```

the planner send this command when it almost reach the goal:

```
linear: 
  x: 0.0
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: -0.4

```

Seems like it reached the goal, but still sending rotational command try to match the angle

Here is the debug print:

> [DEBUG] [1466884384.619185134]: Path/Goal distance computed
> [DEBUG] [1466884384.670715376]: Trajectories created
> [DEBUG] [1466884384.677760928]: Cost PointCloud published
> [DEBUG] [1466884384.677823489]: A valid velocity command of (0.00, 0.00, 0.40) was found for this cycle.
> [DEBUG] [1466884384.711390068]: Nearest waypoint to <1.679603, -1.697871> is <1.100000, -1.000000>
> 
> [DEBUG] [1466884384.717944663]: Path/Goal distance computed
> [DEBUG] [1466884384.769394044]: Trajectories created
> [DEBUG] [1466884384.776868354]: Cost PointCloud published
> [DEBUG] [1466884384.776970709]: A valid velocity command of (0.00, 0.00, 0.40) was found for this cycle.
> [DEBUG] [1466884384.811396036]: Nearest waypoint to <1.678501, -1.700026> is <1.100000, -1.000000>

If it reaches the xy position of the goal it should print:

> ROS_DEBUG("Moving to desired goal orientation, th cmd: %.2f, valid_cmd: %d", v_theta_samp, valid_cmd);

in rotateToGoal() function.

But this is not showing in the debug print. So it's something else that commanding the robot to rotate

**Comment by mikeferguson** [comment]
Good catch -- a PR (with the backwards compatibility mentioned in the DLu commit above) could definitely be accepted into all of indigo/jade/kinetic if someone wants to go about opening them.

**Comment by mikeferguson** [comment]
Is in PR -- closing so I can keep track of what we have to actually still do before release!
