### ISSUE TITLE
cmd_vel flooded with zero-velocity commands during recovery behaviors

### ISSUE THREAD

**Issue by corot** [ros-planning/navigation#494]
This is something new, seems to me that coming with [this commit](https://github.com/ros-planning/navigation/commit/0a686c90c6f188a2731f6f88c2c08610f0ec907e). Happens when the global planner fails to produce a plan: move_base keeps publishing zero-velocity messages. This can hamper recovery behaviors that want to move the robot.
@gjc13, do you think we can remove the publishZeroVelocity(); part from your fix?

**Comment by mikeferguson** [comment]
I hadn't thought of that sort of side effect when reviewing/merging that -- @corot if you open a PR with a revert to that part (against i/j/k branches) we can get that merged and released shortly

**Comment by corot** [comment]
Sure,  i'll do later today (CET). I'll remove just the publishZeroVelocity();, as I have no idea what the other change in the commit does. Would be great if @gjc13 can seed some light on that.

**Comment by gjc13** [comment]
In our configuration we disabled the recovery behaviour, so this part is not tested. Sorry for the side effect. I think you can remove it.

**Comment by corot** [comment]
Fixed; thanks! Can be closed.
Seems like there's no problem on J/K. I didn't tried the code, but the line I removed on indigo is not there
