### ISSUE TITLE
cell size of kdtree

### ISSUE THREAD

**Issue by qh-huang** [ros-planning/navigation#514]
Hi,

in `amcl/src/amcl/pf/pf_kdtree.c`

I'm confused about the value of `size`

```
// Create a tree
pf_kdtree_t *pf_kdtree_alloc(int max_size)
{
  pf_kdtree_t *self;

  self = calloc(1, sizeof(pf_kdtree_t));

  // here, the cell size
  self->size[0] = 0.50;
  self->size[1] = 0.50;
  self->size[2] = (10 * M_PI / 180);
```

why is size[0], size[1] set to 0.5?
shouldn't it correspond to map resolution?
and for default setting, map cell is 0.05 meter, why initial size set to 0.5?

**Comment by asimay** [comment]
I think 0,1,2 is x,y,yaw.
0.5 is means half cell, and the center of a cell.
