### ISSUE TITLE
amcl rotational drift when turning

### ISSUE THREAD

**Issue by glebos** [ros-planning/navigation#521]
Hi,
I am simulating a carlike robot in gazebo and am using amcl for localization. When the robot is turning I get a rotational drift in localization like in this picture: https://postimg.org/image/8qyr67xk5/.
Please help me to solve this problem. I am happy to provide any necessary information.
Thank you in advance!

**Comment by DLu** [comment]
As this is more of a parameter tuning problem as opposed to a verifiable bug, please post this on answers.ros.org instead.
