### ISSUE TITLE
dependency issue for pcl in costmap_2d  

### ISSUE THREAD

**Issue by katanachan** [ros-planning/navigation#527]
I installed costmap_2d via apt-get. The ROS distro I'm using is Kinetic. Although I can see that PCL is already listed as a dependency on CMakeLists.txt on costmap_2d/ the folder in the navigation repository, I'm not sure why this issue is cropping up.

**/opt/ros/kinetic/include/costmap_2d/observation.h:36:29: fatal error: pcl/point_types.h: No such file or directory**

I did solve it myself by adding 
find_package (PCL REQUIRED)
include_directories(${catkin_INCLUDE_DIRS} ${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
to the CMakeLists.txt of the project I'm using.

Thanks!

**Comment by mikeferguson** [comment]
costmap_2d appears to properly export the PCL headers and dependencies -- I presume your project did not "find_package(catkin REQUIRED COMPONENTS costmap_2d)"?
