### ISSUE TITLE
min greater than max in AMCL.cfg

### ISSUE THREAD

**Issue by oscar-lima** [ros-planning/navigation#553]
In lines 27, 28 of https://github.com/ros-planning/navigation/blob/kinetic-devel/amcl/cfg/AMCL.cfg

gen.add("beam_skip_distance", double_t, 0, "Distance from a valid map point before scan is considered invalid", 0, 2, 0.5)

gen.add("beam_skip_threshold", double_t, 0, "Ratio of samples for which the scans are valid to consider as valid scan", 0, 1, 0.3)

the order of dynamic reconfigure is: name, type, level, description, default, min, max

in this two cases min is greater than max, this disables reconfiguration, see image below

![reconf](https://cloud.githubusercontent.com/assets/3973562/21551992/69c5782e-cdf6-11e6-9ac3-130bc1aca942.png)

this is either a bug or a hack ! ?

**Comment by mikeferguson** [comment]
Definitely a bug -- this is a feature that was recently added and I believe is not frequently used. It's possible the author didn't spend much/any time using dynamic reconfigure with it.
