### ISSUE TITLE
The map_server keeps the init stamp for the map so 0 in simulation.

### ISSUE THREAD

**Issue by romainreignier** [ros-planning/navigation#573]
The `map_server` uses its launch time for the stamp of the map message ([here](https://github.com/ros-planning/navigation/blob/43e9297d588276efa9868efe2ed56ac6bf08e180/map_server/src/main.cpp#L179), which makes sense).

But in case we use it with Gazebo, there is no `ros::Time::waitForValid()` statement so if they are launched at the same time, the stamp is always 0.

I do not know if it is the expected behavior but I had an issue where I was using some tf transform helpers that use the message stamp for the `lookupTransform`. So in simulation it was 0 which means, "take the latest available transform", while on the real robot it was using the loading time of the `map_server`, so it always get a timeout.

So I was wondering if it would be a good idea to add the `ros::Time::waitForValid()` in the `map_server` constructor?

Edit: fix the link to source code

**Comment by mikeferguson** [comment]
I can't think of any downside. If it makes simulation vs. robot more consistent, seems like a good idea. I'd recommend we only roll such a change out in Lunar or later at this point (not sure if there is a way that people could be leveraging that simulated behavior, would rather not break it if they are)
