### ISSUE TITLE
Additional costmap layers?

### ISSUE THREAD

**Issue by doisyg** [ros-planning/navigation#577]
Hi,
To understand better how layered costmaps work, I read the great paper describing them by David Lu!!: http://wustl.probablydavid.com/publications/IROS2014.pdf
However the paper lists layers that appears to be very useful but that i did not find anywhere: Caution Zones Layer, Claustrophobic Layer, Hallway Layer and Wagon Ruts Layer.
Are they implemented somewhere?

**Comment by DLu** [comment]
Most of them are not independently implemented, but implemented as various forms of the static or social layer.
