### ISSUE TITLE
Hitting wall when the global path is round

### ISSUE THREAD

**Issue by ytgui** [ros-planning/navigation#580]
Hi,
I used move_base for a long time with excellent results. But I get into trouble now and could not solve it.

Look at this picture, the local path could not follow global path when the global path is round, it seems that local path towards to destination directly.

![img_1](https://preview.ibb.co/kWkDyF/TIM_20170528153023.png)
![img_2](http://i.imgur.com/QNg9Jhl.png)

here's my enviroment:
Ubuntu 16.04
ROS Kinetic
move_base with base_local_planner

Is this a bug or I configured something wrong? I really need some help.
Sincerely

**Comment by DLu** [comment]
Please use ROS Answers for this sort of debugging. However, I'd start by making sure your local_costmap is configured correctly.
