### ISSUE TITLE
New Releaseses for Kinetic

### ISSUE THREAD

**Issue by jabbenseth** [ros-planning/navigation#610]
Hello,

i'm kindly asking for a new release for kinetic. Our CI breaks due to missing returns on kinetic, which were already patched by https://github.com/ros-planning/navigation/pull/535
Can we expect a kinetic release soon keeping in mind the recent lunar release?

Regards

**Comment by mikeferguson** [comment]
Should happen sometime later today -- I already tagged the release this morning, but bloom takes about half an hour on this repo.

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/15730

**Comment by jabbenseth** [comment]
Sorry for my impatience and thank you very much
