### ISSUE TITLE
move_base_msgs error

### ISSUE THREAD

**Issue by dahlan77** [ros-planning/navigation#618]
i installed with ros indigo

and i compiled it and meet some errors

anyone can suggest to me to fix this error

 +++ processing catkin package: 'simple_navigation_goals'
-- ==> add_subdirectory(simple_navigation_goals)
-- Using these message generators: gencpp;genlisp;genpy
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "move_base_msgs"
  with any of the following names:

    move_base_msgsConfig.cmake
    move_base_msgs-config.cmake

  Add the installation prefix of "move_base_msgs" to CMAKE_PREFIX_PATH or set
  "move_base_msgs_DIR" to a directory containing one of the above files.  If
  "move_base_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  simple_navigation_goals/CMakeLists.txt:7 (find_package)

-- Could not find the required component 'move_base_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "move_base_msgs"
  with any of the following names:

    move_base_msgsConfig.cmake
    move_base_msgs-config.cmake

  Add the installation prefix of "move_base_msgs" to CMAKE_PREFIX_PATH or set
  "move_base_msgs_DIR" to a directory containing one of the above files.  If
  "move_base_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  simple_navigation_goals/CMakeLists.txt:7 (find_package)

**Comment by DLu** [comment]
Please use answers.ros.org for this type of inquiry, as the problem sounds like it originates in your `simple_navigation_goals` package and not move_base.

**Comment by Napoleon-BlownApart** [comment]
What happened to the `move_base_msgs` package?  It seems to be missing in the root list of sub-packages here.
I've cloned this `navigation` repo as part of my ROSPlan demo(Stage Exploration) build. I can install it via `apt install ros-melodic-move-base-msgs` but prefer to build from source.
Where can I get current `move_base_msgs` source for `melodic`?

I found out, from the good ppl in the Freenode #ros IRC channel that the `jade-devel` branch (default) at https://github.com/ros-planning/navigation_msgs repo will work for `melodic`.  My build has just succeeded, with all (51) source packages I've selected.

Perhaps http://wiki.ros.org/move_base_msgs wiki page could be updated with this information.

**Comment by mikeferguson** [comment]
We've moved move_base_msgs into a separate repo (the navigation_msgs you mention above), so that people interacting with move_base don't need to build all of move_base locally. The jade-devel branch should work on melodic (we have not changed the message since the package split, which was done for Jade).

The wiki page you reference is up to date - in the "Package Summary" for the "Melodic" page, it tells you the repository listed above and jade-devel is the branch to use for source.
