### ISSUE TITLE
Recent version deprecates planner_frequency

### ISSUE THREAD

**Issue by lachyd** [ros-planning/navigation#623]
As above. I was on a previous version and the planner_frequency properly re-planned the global path as required. On the current kinetic-devel branch, this is no longer the case - setting planner_frequency to any value does not work.

The problem appears to be in the while loop at around line 557 of move_base.cpp. This loop waits for notification on planner_cond_, which is designed to limit the rate of the global planner. However, after exiting this loop, the state_ variable is most likely not PLANNING (assuming we have a valid plan from a previous iteration), so the global planner is never called again. Suggest adding state_=PLANNING; after wait_for_wake=false; in this while loop.

**Comment by DLu** [comment]
I think this is taken care of with https://github.com/ros-planning/navigation/pull/622
