### ISSUE TITLE
Footprint param behavior in hydro-devel not fully backwards-compatible.

### ISSUE THREAD

**Issue by hershwg** [ros-planning/navigation#63]
In groovy nav, you could put your footprint param in the costmaps and they would read it.  In hydro nav, the costmaps subscribe to the footprint as a topic.  The costmaps no longer read the rosparam.  move_base now looks for a rosparam for the footprint and publishes it if it finds one.  However it is looking in the move_base namespace and above, which misses the footprints described in the costmap namespaces.

Move the footprint-param-reading calls into costmap_2d_ros.

**Comment by hershwg** [comment]
I propose fixing this by:
- removing the footprint publication from move_base
- put the searchParam("footprint") back into Costmap2DROS
- put support for dynamic reconfigure of "footprint" param back into Costmap2DROS
- leave the subscription to "footprint" topic in Costmap2DROS

The new behavior would be that footprints would be read from rosparams initially, but could be changed either by dynamic-reconfigure or by Polygon messages published to the appropriate topic.

This would be more backwards-compatible but still leave the nice feature of footprint-via-topic.

What do you think, @DLu (and anyone else)?

Is the existing footprint publication by move_base (in hydro nav) important for anything else other than sending the footprint to the costmaps?

**Comment by DLu** [comment]
I think this is an excellent compromise.  There is no additional benefit to
having move base publish the topic that couldn't be accomplished with the
Polygon Stamped footprint.
