### ISSUE TITLE
Failed to create the global_planner/GlobalPlanner planner

### ISSUE THREAD

**Issue by ryanoldja** [ros-planning/navigation#638]
Setup: ROS Kinetic, Ubuntu 16.04

on the TurtleBot platform, when launching the `move_base` node configured for the global_planner/GlobalPlanner, I receive the following error:

`Failed to create the global_planner/GlobalPlanner planner, are you sure it is properly registered and that the containing library is built? Exception: According to the loaded plugin descriptions the class global_planner/GlobalPlanner with base class type nav_core::BaseGlobalPlanner does not exist. Declared types are  navfn/NavfnROS`

I load `move_base_params.yaml` within `move_base` as follows:

` <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen" >`
`     <rosparam file="$(find robust_navigation)/param/move_base_params.yaml" command="load" />`

where the `base_global_planner` param is defined in `move_base_params.yaml` as follows:
`base_global_planner: "global_planner/GlobalPlanner"`

I've re-installed the nav stack and re-built my workspace to no avail.

**Comment by DLu** [comment]
Please do not cross-post your questions. [answers.ros.org](https://answers.ros.org/question/276939/failed-to-create-the-global_plannerglobalplanner-planner/)

**Comment by markdole** [comment]
Can you please leave the right way to solve this problem? 
I met the same issue, and dont actually understand how to deal with the source problem.

**Comment by usmanNoor5** [comment]
same issue and didn't get the solution till now
