### ISSUE TITLE
How can i make return system??

### ISSUE THREAD

**Issue by par8057** [ros-planning/navigation#652]
Hi im working with turtlebot3

I want to make literally 'return system' which means that Turtlebot3 goes to goal position and return to the
initial position.
I already succeed to run turtlebot3_navigation package.
But i dont know how to edit a package to make 'return system'
Do you know what i mean???

Please let me know guys

**Comment by procopiostein** [comment]
We ask that you please ask questions on http://answers.ros.org following our support guidelines:
http://wiki.ros.org/Support

Github Issues is for problems and bugs related to the source code.

ROS Answers http://answers.ros.org/ provides a forum which can be filtered by tags to
make sure the relevant people can find and/or answer the question, and not
overload everyone with hundreds of posts.
