### ISSUE TITLE
Integrate navigation stack into Nvidia Jetson

### ISSUE THREAD

**Issue by Manujaya94** [ros-planning/navigation#676]
Hi, 
I am trying to integrate navigation stack into robot with Nvidia Jetson. I already implemented the slam with lidar and kinect with teleoperation and  navigation with goal poses, it only moving into different goal that i have published. it doest not have real time obstacle avoid and path planning. There for can you help me that how to integrate the navigation stack into my jetson robot. I have xv11 laser scan lidar and kinect and the arduino mega with pololu motor shield.

Thank you

**Comment by DLu** [comment]
The best place to start would be [this tutorial](http://wiki.ros.org/navigation/Tutorials/RobotSetup). If you have additional questions, please follow up on answers.ros.org
