### ISSUE TITLE
Integrate sensor_msgs/Range messages in costmap_2d

### ISSUE THREAD

**Issue by corot** [ros-planning/navigation#69]
Related discussion on SIG:
https://groups.google.com/forum/?fromgroups#!topic/ros-sig-navigation/dN3h8msTDzg

**Comment by DLu** [comment]
Check out the new [sonar_layer](https://github.com/DLu/navigation_layers/tree/master/sonar_layer) package.

**Comment by corot** [comment]
Looks good! I installed and tested it. Btw, do you plan to develop it further? I'm thinking mostly in extending it to subscribe to an arbitrary number of sensor_msgs/Range topics, so we don't need to multiply the number of layers (I have a ring of 11 sonars).
Thanks

**Comment by DLu** [comment]
No large plans for updating it, so patches are welcome!
