### ISSUE TITLE
Invalid trajectory's obstacle scoring in dwa_local_planner

### ISSUE THREAD

**Issue by pavloblindnology** [ros-planning/navigation#697]
According to next line, trajectory's obstacle score equals to score of the last point in `dwa_local_planner`.
https://github.com/ros-planning/navigation/blob/43e9297d588276efa9868efe2ed56ac6bf08e180/base_local_planner/src/obstacle_cost_function.cpp#L97
While it should be the maximum of scores for all points, as it's done in `base_local_planner`
https://github.com/ros-planning/navigation/blob/43e9297d588276efa9868efe2ed56ac6bf08e180/base_local_planner/src/trajectory_planner.cpp#L306
Otherwise, the planner just doesn't care about obstacles located far enough from the trajectory endpoint (of course if not in collision with them).

**Comment by DLu** [comment]
I'm not certain this is a bug persay, but I would support adding a parameter to add the option to get the max of all costs, since otherwise it would change the default scoring for many people. 

Are you seeing situations where not doing the max causes problems?

**Comment by pavloblindnology** [comment]
Yes, I'm seeing.
When having relatively large inflation area and relatively long trajectories, dwa_local_planner (and all local planners based on BaseLocalPlanner) just neglects inflation area around the obstacles in certain situations. Like the one at this [picture](https://drive.google.com/open?id=1wfjRi20NzUjIKUFRGRkxRVrSbV9kytQW), where the blue trajectory is selected by the planner whatever the value of `occdist_scale` is.
I believe that is completely wrong and not the behavior the user expects (at least me).
I'm developing my own local planner based on BaseLocalPlanner and is seeing that the robot tends to pass too close to the obstacle. After correcting this according to my PR the behavior has amended.
So, for me it's certainly a bug, especially taking into account that it's done correctly in `base_local_planner`.
But you're right that it may change scoring for many people, though in a proper direction.
