### ISSUE TITLE
RotateRecovery parameter names differ from TrajectoryPlannerROS parameter names

### ISSUE THREAD

**Issue by MarcoStb1993** [ros-planning/navigation#706]
The parameters specified in TrajectoryPlannerROS that according to the documentation will be accepted by RotateRecovery have different than those of RotateRecovery which leads to RotateRecovery using the default values instead of the ones specified by the user in base_local_planners.yaml.
http://wiki.ros.org/rotate_recovery
(acc_lim_th, max_rotational_vel, min_in_place_rotational_vel )
http://wiki.ros.org/base_local_planner?distro=kinetic
(acc_lim_theta, max_vel_theta, min_in_place_vel_theta)

**Comment by mikeferguson** [comment]
Adding melodic milestone to this -- since I'd like to try to address all of these random parameter issues we've found over the years in this new LTS.

**Comment by mikeferguson** [comment]
Is in PR -- closing so I can keep track of what we have to actually still do before release!
