### ISSUE TITLE
Cannot Build from source 

### ISSUE THREAD

**Issue by jediofgever** [ros-planning/navigation#707]
Hi there, 
I have try to build navigation stack with no sucess, when I do catkin_make the process hangs forever at %100 percent without any error or warning. What can cause my problem. I am on ubuntu 16 04 with ROS kinetic version.
Thanks for your help

**Comment by Huaxu-Qiu** [comment]
just wait~

**Comment by DLu** [comment]
This issue is probably more appropriate for answers.ros.org, since is likely a personal configuration issue. I would try running `catkin_make -j1` to see if that helps.
