### ISSUE TITLE
/map as OccupancyGrid is ignored by global planner

### ISSUE THREAD

**Issue by ghost** [ros-planning/navigation#724]
Hi, I am using cartographer to generate the /map topic of type OccupancyGrid.
However, the global planner is not using it properly it.

From the observations in rviz I see, that the move_base/global_planner/costmap is constructed, but with many holes:
![global_costmap](https://user-images.githubusercontent.com/90824/40188480-53404dae-59fa-11e8-8313-180bdc28cbe0.png)

The global path, with /map displayed, looks like this:
![map](https://user-images.githubusercontent.com/90824/40188538-71f58e8a-59fa-11e8-8b0d-38f7f7a228e7.png)

I assume, that the threshold to analyze the /map topic of type occupancy grid is too high, which means, that when cartographer sets the occupancy to a value 20 and the converter for costmap has 30 as threshold, then holes are appearing.

Is there a way to set the threshold for the occupancy map pixels to 1 or a least a very low value?

Thanks alot!

**Comment by mikeferguson** [comment]
Please see the wiki page for the layer - http://wiki.ros.org/costmap_2d/hydro/staticmap. The parameter you are looking for is "lethal_cost_threshold".
