### ISSUE TITLE
How to install the latest navigation

### ISSUE THREAD

**Issue by ytgcljj** [ros-planning/navigation#747]
I installed ROS with the command of sudo apt-get install ros-kinetic-desktop-full. Now I'm updating navigation. I don't know how to update it. Please help me

**Comment by mikeferguson** [comment]
This is really a question for answers.ros.org.

**Comment by subodh-malgonde** [comment]
Many beginners face this question and it does not have a very obvious answer. This question should be addressed in the documentation, which is expected to have basic instructions on setting up the navigation stack. I would be happy to open a PR.

If it helps anyone else, the way to install ROS Navigation stack is to run `apt-get install ros-<your_ros_distro>-navigation`. Eg. For the kinetic distro `apt-get install ros-kinetic-navigation`. Run `apt-get update` before this.

**Comment by mikeferguson** [comment]
The ROS wiki covers how to install packages in general -- http://wiki.ros.org/melodic/Installation/Ubuntu -- see the section on "installing an individual package". The ROS wiki also does this for ALL available platforms -- not just Ubuntu.

If you're trying to jump straight into navigation without learning how to use ROS in general, you're doing it wrong. The documentation of every individual package shouldn't include the full set of instructions for how to install on every available platform.
