### ISSUE TITLE
Melodic Release?

### ISSUE THREAD

**Issue by bochen87** [ros-planning/navigation#749]
Hi,
It seems as if the navigation stack is currently blocked from release and thus not available for bionic - only via installation from source 
http://repositories.ros.org/status_page/blocked_releases_melodic.html?s=6&r=1

**Comment by mikeferguson** [comment]
Yeah, we're a bit behind -- see the milestone for Melodic (https://github.com/ros-planning/navigation/milestone/4) -- I think we may end up pushing those remaining items (I was really hoping to have fully switched to TF2, since so many core stacks have -- but I've not yet been able to actually make it work)

**Comment by bochen87** [comment]
Oh, ok, thanks for the explanation! I was just wondering because it wasn't noted anywhere that the navigation stack was not ready yet. In the installation it even mentions that navigation get's installed with `ros-melodic-desktop-full` so I first spent half an hour looking for potential errors on my computer :-)

Unfortunately, I don't have edit rights yet, but maybe worth adding this as a disclaimer in the installation notes on the wiki? http://wiki.ros.org/action/login/melodic/Installation/Ubuntu

**Comment by mikeferguson** [comment]
Hmm, so - I think that documentation might need to be updated on more than just Melodic -- navigation hasn't been in desktop full since at least the metapackage refactor in Hydro. See also https://github.com/ros/metapackages/issues/12 -- which is apparently when they fixed the Indigo documentation,

**Comment by bochen87** [comment]
Oh, I see - well maybe also additionally mentioning in the melodic documentation that the navigation is not yet installable as package. I asked for edit rights in the wiki, will have to wait until I get that, then I can update it if you want to.

**Comment by mikeferguson** [comment]
Putting temporary notes on the release status on the Wiki is probably a bad idea -- nobody will end up removing it later on. It's better that people look at the automatically generated and always up to date [status pages](http://repositories.ros.org/status_page/ros_melodic_default.html) (which I will admit are somewhat hard to find -- which is something that should be addressed). If something isn't listed (like navigation) then it hasn't been released. Once it is released, that page makes it easy to know if it has been synced to public, or if new releases are in the pipeline.

**Comment by bochen87** [comment]
I removed the mention of the navigation stack in the desktop-full package. Can we leave this issue open so that people know the navigation stack is not available as a package on melodic as of yet?

**Comment by mikeferguson** [comment]
Yep, I’ve added this ticket to the milestone, and will leave it open

**Comment by mikeferguson** [comment]
I think we've got a TF2 solution -- in #755 + setRPY(). Once that is finished up and merged, we'll get a release out.

**Comment by mikeferguson** [comment]
I'm working on release now

**Comment by mikeferguson** [comment]
Release is tagged -- bloom is taking foreveeeeeeeer

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/18657

**Comment by mikeferguson** [comment]
Will work on the wiki changelog later tonight

**Comment by subodh-malgonde** [comment]
After going through this thread, I understand that the navigation package has been released for ROS Melodic. Am I right?

I am on Ubuntu 18.04 and I am still unable to install navigation as a package. Please correct me if I am wrong.

**Comment by mikeferguson** [comment]
It has been released, but a sync has not yet happened. We have no control over when OSRF does a sync.
