### ISSUE TITLE
How can I use navigation package on my own robots to get planning target msg

### ISSUE THREAD

**Issue by GITSHOHOKU** [ros-planning/navigation#754]
Hello everyone!
Now I use ORB-SLAM which can provides location msg and RGB-D can provide pointcloud2 msg.
I can get the tf between camera and robot, what I need is use the pointcloud2 to avoid obstacles. I have learned guidance on navigation page. But I am confused if I provide pointcloud2 and tf among each frames,and I just need the planning path to avoid obstacles ,So
             1. Can I just subscribe the position on this path as msg. How can I do it? 
             2. And if it  possible to use SLAM location msg in it?                                                      
             3. Can I simulate it use rviz ?
thank you very much

**Comment by mikeferguson** [comment]
Please post broad questions like this on answers.ros.org
