### ISSUE TITLE
Jenkins/Docker setup is slower after tf2 #752

### ISSUE THREAD

**Issue by moriarty** [ros-planning/navigation#758]
![build-time-trend](https://user-images.githubusercontent.com/55676/42740202-be703d32-8858-11e8-9e6c-b5aadd2c1014.png)

The part which has slowed down seems to be the pre-setup stages. I thought maybe it is because some template code in tf2 slows things down but it doesn't seem so. It now takes **much** loger to get to the build workspace in isolation stage.

Build 31
http://build.ros.org/job/Mpr__navigation__ubuntu_bionic_amd64/31/consoleFull#console-section-15
```
00:00:00.000 GitHub pull request #751 of commit d84d855ab344f6c1f3c8c84756fa42c326a9283e, no merge conflicts.
...
# BEGIN SUBSECTION: build workspace in isolation
00:14:39.353 Invoking '. /opt/ros/melodic/setup.sh && PYTHONIOENCODING=utf_8 PYTHONUNBUFFERED=1 catkin_make_isolated --cmake-args -DCATKIN_ENABLE_TESTING=1 -DCATKIN_SKIP_TESTING=0 -DCATKIN_TEST_RESULTS_DIR=/tmp/catkin_workspace/test_results --catkin-make-args -j1' in '/tmp/catkin_workspace'
...
00:39:10.809 Finished: SUCCESS
```

Build 32
http://build.ros.org/job/Mpr__navigation__ubuntu_bionic_amd64/32/consoleFull#console-section-15
```
00:00:00.000 GitHub pull request #752 of commit 88ada10d9129d529a373162f42fb74cd0821d649, no merge conflicts.
...
# BEGIN SUBSECTION: build workspace in isolation
01:23:08.338 Invoking '. /opt/ros/melodic/setup.sh && PYTHONIOENCODING=utf_8 PYTHONUNBUFFERED=1 catkin_make_isolated --cmake-args -DCATKIN_ENABLE_TESTING=1 -DCATKIN_SKIP_TESTING=0 -DCATKIN_TEST_RESULTS_DIR=/tmp/catkin_workspace/test_results --catkin-make-args -j1' in '/tmp/catkin_workspace'
...
01:55:13.618 Finished: SUCCESS
```

I changed the snippets to Elapsed time to make it more clear, it is now more than an hour longer to Stage 14.1 "build workspace in isolation"

**Comment by mikeferguson** [comment]
The difference in getting to build start is not actually different -- that's just how long it took for a buildslave to be available. For instance, here is a successful build from a while ago, that took 21 minutes to start as well: http://build.ros.org/job/Mpr__navigation__ubuntu_bionic_amd64/7/console

**Comment by moriarty** [comment]
Okay, and it actually looks like the restarted build for the #755 PR is already far along and should pass. http://build.ros.org/job/Mpr__navigation__ubuntu_bionic_amd64/38/consoleFull#console-section-12

Then should I close this?

**Comment by mikeferguson** [comment]
Leave it open -- we've not had this many issues until right now -- so I think something is wonky -- just not sure what yet

**Comment by mikeferguson** [comment]
And actually you are right -- I think I was looking at the wrong timestamps initially. Doing an elapsed view:

 * First 11 steps went from 4 minutes to 36 minutes
 * Takes us 1hr35min to start tests, instead of 22minutes
 * Tests take about 20 minutes in both -- but if they run a little long, we blow through the time limit.

**Comment by mikeferguson** [comment]
Build 38 appears to have started tests after 20 minutes -- so maybe this was actually a build farm issue? @tfoote -- any thoughts?

**Comment by mikeferguson** [comment]
Seems to have been intermittent on buildfarm and gone away...

**Comment by tfoote** [comment]
The buildfarm does a lot of caching of the setup. If it has run a build very similar to your build it will setup much faster.  There are also sometimes so IO bottlenecks/performance issues on the executors that we're not entirely sure what the origin is.
