### ISSUE TITLE
global planner for obstacle avoidance using mono cam !

### ISSUE THREAD

**Issue by ziggBee30** [ros-planning/navigation#776]
Hello guys

Can this anyway take information of the obstacle from my ROS node on which i am just using image_raw topic, and put the obstacle location in the map and plan the path accordingly ??

Please any suggestions !

Thanks

**Comment by DLu** [comment]
Please open a question on answers.ros.org instead of posting here. The easiest way to get the information into the costmap is converting `image_raw` data to PointClouds.

**Comment by ziggBee30** [comment]
I dont know of any way using which you can convert image_raw to point
cloud, if it was so them eventually you can have depth and which will clear
everything and make it all done easy.
i am using mono cam and just have access to image_raw, PCL will be
available using stereo cam and depth cameras.
