### ISSUE TITLE
Using my own Global and Local costmaps?

### ISSUE THREAD

**Issue by Myzhar** [ros-planning/navigation#777]
I have my own node that provides Global Map and Local Map as nav_msgs::OccupancyGrid messages. I would like to use them in the navigation stack and I cannot figure out how to do it.

Is this possible without modifying the code of costmap_2d and move_base?

Thank you
walter

**Comment by DLu** [comment]
Please do not cross post your questions. https://answers.ros.org/question/300142/navigation-how-to-use-my-own-local-and-global-costmaps/
