### ISSUE TITLE
How to reduce the density of the generated global path?

### ISSUE THREAD

**Issue by ghost** [ros-planning/navigation#782]
I would like to reduce the number of poses published in the move_base/Navfn/plan topic, which is sometimes a few thousands in my case.
Is there a way to configure this with params?
If no, can someone point me to the source code, where I might extend it?

Thank you very much!

**Comment by DLu** [comment]
Please post questions like this on answers.ros.org in the future. The easiest way to reduce the number of poses is to reduce the resolution of your costmap. Other than that, I can't think of a direct way to simplify the path.

**Comment by mikeferguson** [comment]
For the navfn planner, the publisher is located here: https://github.com/ros-planning/navigation/blob/melodic-devel/navfn/src/navfn_ros.cpp#L343 -- you could I suppose add some downsampling there (although the plan published might no longer be very true to the real plan)

**Comment by ghost** [comment]
Thanks!
