### ISSUE TITLE
How to run this package?

### ISSUE THREAD

**Issue by Umsramu93** [ros-planning/navigation#787]
Hi all,
I am new to ROS.
So kindly guide me in running this package.
i would like to pass a map via map server. After the sensor data integration i would like to get the inflated local and global cost map.

My main focus is to work with local and global costmap.

Thanks.

**Comment by DLu** [comment]
Hi. Please check out the documentation here: http://wiki.ros.org/navigation/Tutorials/RobotSetup
and in the future be sure to check out answers.ros.org
