### ISSUE TITLE
Error in fake_localization package: lookupTransform. Not enough time?

### ISSUE THREAD

**Issue by JavierLRH** [ros-planning/navigation#796]
I have a problem with the package fake_localization.

When I set a new initial_pose in rviz, I get the error ""Failed to lookup transform!"":
![imagen](https://user-images.githubusercontent.com/39495812/46245246-288f2200-c3eb-11e8-9f55-a715dd59a5e7.png)

This is my tf tree, I think that it's ok.
![imagen](https://user-images.githubusercontent.com/39495812/46245298-d0a4eb00-c3eb-11e8-9d0a-278484e66c92.png)

- I looking for a solution for the problem and I find this question with the same problem that me.
https://answers.ros.org/question/287587/lookuptransform-is-throwing-error/
The problem is that we need to wait for the transforms to become available.

- I need to wait for the tf at least 0.052 s

RESULTS: for map to base_link
Chain is: map -> odom -> base_link
Net delay     avg = 0.0262871: max = 0.0519673

- tf2 provides a tool that will wait until a transform becomes available.
![imagen](https://user-images.githubusercontent.com/39495812/46245393-2b8b1200-c3ed-11e8-8b53-dd3649d4eb95.png)

Sorry for my English.
Regards and thank you.

**Comment by guohefu** [comment]
> I have a problem with the package fake_localization.
> 
> When I set a new initial_pose in rviz, I get the error ""Failed to lookup transform!"":
> ![imagen](https://user-images.githubusercontent.com/39495812/46245246-288f2200-c3eb-11e8-9f55-a715dd59a5e7.png)
> 
> This is my tf tree, I think that it's ok.
> ![imagen](https://user-images.githubusercontent.com/39495812/46245298-d0a4eb00-c3eb-11e8-9d0a-278484e66c92.png)
> 
> * I looking for a solution for the problem and I find this question with the same problem that me.
>   https://answers.ros.org/question/287587/lookuptransform-is-throwing-error/
>   The problem is that we need to wait for the transforms to become available.
> * I need to wait for the tf at least 0.052 s
> 
> RESULTS: for map to base_link
> Chain is: map -> odom -> base_link
> Net delay avg = 0.0262871: max = 0.0519673
> 
> * tf2 provides a tool that will wait until a transform becomes available.
>   ![imagen](https://user-images.githubusercontent.com/39495812/46245393-2b8b1200-c3ed-11e8-8b53-dd3649d4eb95.png)
> 
> Sorry for my English.
> Regards and thank you.

I have the same problem, has it been resolved?

**Comment by JavierLRH** [comment]
Not yet.

**Comment by guohefu** [comment]
I change the code to the following to solve:
baseInMap = m_tfBuffer->lookupTransform(base_frame_id_, global_frame_id_, ros::Time(0));

**Comment by JavierLRH** [comment]
How do you compile the navigation package.
When I compile it with catkin the performance is much worse.

**Comment by guohefu** [comment]
What is your platform (architecture, OS & version/distro)?

**Comment by JavierLRH** [comment]
A Laptop with a Intel I5. The SO is Ubuntu 16.04 and the ROS version is Kinetic.
When I use the ROS navigation from source (apt-get install) the performance is good, but when I compile the Github version, the percentage of CPU usage rise to the 100% and I get warning messages from the package. 

Something similar to this: https://answers.ros.org/question/258139/navigation-stack-runs-slow-when-installed-from-source.
I try to change the flags but the issue is the same.

**Comment by mikeferguson** [comment]
So, it looks like the code used to use ros::Time(0) for "latest transform", rather than the actual timestamp (before the port to TF2). I'd suggest trying ros::Time(0) -- if that works, please open a PR.

**Comment by JavierLRH** [comment]
I just try the package with ros::Time(0) and works well.
I want to make the PR but I don't know how to do it. I must create a branch first?
Regards.

**Comment by mikeferguson** [comment]
If you can confirm that ros::Time(0) works, I can handle the PR.

**Comment by JavierLRH** [comment]
Hi, I made a video showing how the change works.
https://www.youtube.com/watch?v=itXlTo5CyPQ
Thanks

**Comment by DLu** [comment]
Closed in #1017
