### ISSUE TITLE
No transform available Error looking up robot pose

### ISSUE THREAD

**Issue by alfred31** [ros-planning/navigation#797]
Hi,
I am using move_base with cartographer.
It was working fine, although it crashed time to time.
The thing is that I upgraded the navigation package and now the navigation package is not working anymore. It respawns all the time and crashes.
Before crashing it displays the following error: No Transform available Error looking up robot pose.
I don't know what could be causing this.

Any help would be more than welcome.

Thanks in advance.

Kind regards.

**Comment by DLu** [comment]
Hi, please open a question on answers.ros.org for debugging this problem.
