### ISSUE TITLE
move_base has died

### ISSUE THREAD

**Issue by sweetquiet** [ros-planning/navigation#799]
hello:
  terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

 [move_base-20] process has died [pid 18315, exit code -6,

**Comment by DLu** [comment]
Please follow the [Support guidelines](http://wiki.ros.org/Support). This post is missing much of the needed info for people to be able to help you.

**Comment by sweetquiet** [comment]
👌

Best wishes
