### ISSUE TITLE
ObstacleCostFunction - scoreTrajectory()

### ISSUE THREAD

**Issue by hershwg** [ros-planning/navigation#8]
[Originally posted by kluessen to kforge trac]

In obstacle_cost_function.cpp - Line 83 et seq.

You use this for loop to score every point from the given trajectory considering the footprint of the robot. But in every loop circle you overwrite the cost variable, so in the end it just contains the cost of last point of the trajectory. 

Either you plan to integrate an aggregationType like LAST, SUM, PRODUCT as done in the MapGridCostFunction?, which is used to score trajectories (map_grid_cost_function.cpp - line 111 ). Otherwise the for loop is just a waste of computation time. Or did I get something wrong here?

**Comment by DLu** [comment]
Fixed with 2135656ea03a42b18278fa9a0c2f7beecd632528
