### ISSUE TITLE
Is there any existed local planner that can work with orientation filter in global_planner ?

### ISSUE THREAD

**Issue by bxc237** [ros-planning/navigation#804]
Hi, since the orientation filter has no effect on the DWA local planner, I'm wondering which local planner is suitable to work with the orientation filter on the omni-wheel robot. Thanks.

**Comment by reinzor** [comment]
As far as I know. There are no base local planners that support this available in the nav stack.

**Comment by DLu** [comment]
Back when I wrote the orientation filter, I believe I was using it in conjunction with [this tragically underdocumented planner](https://github.com/DLu/simple_local_planner)

**Comment by bxc237** [comment]
Thank you both @reinzor @DLu . Close issue...
