### ISSUE TITLE
DWA: is shaking as soon as it reaches the finish line.

### ISSUE THREAD

**Issue by sweetquiet** [ros-planning/navigation#809]
Hello: DWA: When approaching the target point, the back and forth vibration should be caused by re-planning the path when approaching the target point. Does it need to be locked? Can the developer give a good solution? This problem should be encountered by every user who uses DWA, and I look forward to your solution. Thank you very much!

**Comment by mikeferguson** [comment]
This sounds like a tuning issue -- please ask on answers.ros.org
