### ISSUE TITLE
DWA fails to get path after switching from source install to binary

### ISSUE THREAD

**Issue by Master-Matt** [ros-planning/navigation#810]
I wanted to edit the map_server for use with cartographer so I installed from source. After I did, Navigation ran horribly so I removed it and tried to switch back to using the binary installation. Since I'm using cartographer with Kinetic I am using ninja to make my project. I removed all install folders and re-built, but still no good.
The DWA planner is not even moving the robot at all. If I bring navigation back in from source, it works, but again it has poor performance compared to the binary install.
Am I missing steps somewhere?
This is my current output from nav. 
[ INFO] [1541431084.895501853, 23.761000000]: Got new plan
[ WARN] [1541431084.915186353, 23.780000000]: DWA planner failed to produce path.
[ INFO] [1541431085.000501373, 23.862000000]: Got new plan
[ WARN] [1541431085.028524730, 23.888000000]: DWA planner failed to produce path.
[ INFO] [1541431085.103385883, 23.961000000]: Got new plan
[ WARN] [1541431085.124919847, 23.982000000]: DWA planner failed to produce path.
[ INFO] [1541431085.210148758, 24.061000000]: Got new plan
[ WARN] [1541431085.235411133, 24.086000000]: DWA planner failed to produce path.

**Comment by SteveMacenski** [comment]
Please post issues like this to [ROS Answers](https://answers.ros.org/questions/), you'll get more feedback there. Tickets in Navigation are for features and bugs in the codebase.

**Comment by Master-Matt** [comment]
Okay. I will close this out then.
