### ISSUE TITLE
DWA:Obstacles can cause body jitter.

### ISSUE THREAD

**Issue by sweetquiet** [ros-planning/navigation#811]
1. when a car goes ahead, a sudden obstacle will cause the car to shake.
2. when a relatively narrow passageway takes place, the problem of car wobble will occur.

**Comment by reinzor** [comment]
This issue is not specific enough.

**Comment by sweetquiet** [comment]
Okay, so when there's an obstacle in front of the car, I guess DWA wants to get around it, but it can't get around it. The car can only turn left, right, and very fast, which causes it to shake (constantly turning left and right).

**Comment by SteveMacenski** [comment]
@sweetquiet these types of questions are more suited to ROS Answers . org not issues on the main repo

**Comment by sweetquiet** [comment]
@SteveMacenski ok thanks
