### ISSUE TITLE
robot_pose_ekf  only using imu_data

### ISSUE THREAD

**Issue by GITSHOHOKU** [ros-planning/navigation#814]
Hi
 I saw the tutorial here [adding gps](http://wiki.ros.org/robot_pose_ekf/Tutorials/AddingGpsSensor),the first line said it can just use one msgs with the package.
 So can I just use imu_data msgs as the only input to robot_pose_ekf to get combine_odom output?

**Comment by SteveMacenski** [comment]
robot pose ekf has been deprecated in favor of robot_localization. I would recommend looking into that. 

To answer your question: maybe, I'd just try and find out

**Comment by GITSHOHOKU** [comment]
@SteveMacenski  
Thanks anyway!
I just wonder if I can just use imu data as input or I should give it a initial pose for localization

**Comment by mikeferguson** [comment]
This is really more suited to answers.ros.org -- please ask there.
