### ISSUE TITLE
Global planner will plan through walls if laser topic is incorrect

### ISSUE THREAD

**Issue by elhayra** [ros-planning/navigation#815]
When setting the obstacle_laser param, one can make a mistake and write an incorrect laser topic. In this case, the global planner will plan through walls. I suggest adding a warning in case this param is defined but no laser messages were received within X seconds.

**Comment by DLu** [comment]
The way to get that behavior is to set the [`expected_update_rate`](http://wiki.ros.org/costmap_2d/hydro/obstacles) for the sensor to be non-zero. There is an argument that could be made that the default should not be zero, but as that would affect many people's configurations, I'm not going to tackle that question here.
