### ISSUE TITLE
A small bug in map_grid.cpp

### ISSUE THREAD

**Issue by MichaelPan0905** [ros-planning/navigation#817]
In base_local_planner/src/map_grid.cpp, line 150, here is a sentence to find "steps" which is used to smooth(I think) the global_plan we input, which is like this:
`int steps = ((sqrt(sqdist) - sqrt(min_sq_resolution)) / resolution) - 1;`
I think this sentence is wrong, it should be like this:
`int steps = ((sqrt(sqdist) - sqrt(min_sq_resolution)) / resolution) + 1;`
cause the "steps" tells us how many nodes we should add between two origin nodes in global_plan_input, and it should be positive. The old sentence may lead to less nodes that we add than we should, and in some extreme cases, like the sqrt(sqdist) equals 3 times of the resolution, it might carsh in the next two lines:
```
double deltax = (loop_x - last_x) / steps;
double deltay = (loop_y - last_y) / steps;
```
because the steps equals 0.

**Comment by DLu** [comment]
Closed via #819
