### ISSUE TITLE
Compilation error solved by add_compile_options(-std=c++11)

### ISSUE THREAD

**Issue by AntaresZhang** [ros-planning/navigation#818]
Seems like the tf2 dependency needs c++ 11 to compile correctly, solved this issue by adding 
----------------------------------------------
add_compile_options(-std=c++11)
----------------------------------------------
to  all  the CMakelists.txt of the packages with tf2 dependency
I got instruction  from this link:
https://github.com/ros/geometry2/issues/334

**Comment by DLu** [comment]
Please post 
 * The error you were getting
 * Your operating system
 * Your version of ROS
 * Which branch of the navigation repo you are on
 * The command used for compiling

**Comment by mikeferguson** [comment]
Seeing as our CI is passing on dev/PR builds, I imagine this actually some local config error (improper branch for your platform and/or rosdistro)

**Comment by AntaresZhang** [comment]
Hi thanks for the reply,
i am getting similar errors as it keeps saying array is not a member of std::
using Ubuntu 16.04
ROS kinetic
i think i am using the kinetic-devel branch
simply a catkin_make

**Comment by AntaresZhang** [comment]
i just added  the 
add_compile_options(-std=c++11)
to the cmakelists files and everything worked fine

**Comment by DLu** [comment]
Could not reproduce. I'm guessing there's something else in your pipeline that requires c++11

**Comment by ankuku** [comment]
@AntaresZhang Hey! I am a complete noob to this. Where do I have to add the line again, please? There are a lot of `CMakeLists.txt` files in `geometry2` package, and I ended up adding `add_compile_options(-std=c++11)` to every folder of the package of `geometry2` and the compilation still fails.

Thanks for your help.

**Comment by ankuku** [comment]
@DLu It doesn't. This is a fresh install of ROS and so far I have two packages other than `geometry2`, and both of them compiled alright. 
I don't know how the issue flagging works, is it the same as tickets? Can this one be reopened, please?

**Comment by ankuku** [comment]
@AntaresZhang @DLu 
Okay, it worked now.
The line had to be added to main `CMakeLists.txt` file in the `src` folder. I didn't try to write there fearing it is a "protected" file. A `sudo nano` took care of it.

Many thanks!
