### ISSUE TITLE
Orientation_filter for kinetic

### ISSUE THREAD

**Issue by inuex3** [ros-planning/navigation#820]
In melodic-devel, orientation_filter supports BACKWARD or RIGHTWARD or and so on.But Kinetic-devel has not supported yet. I just replaced `global_planner/orientation_filter.cpp` , `global_planner/include/global_planner/orientation_filter.h` and `global_planner/cfg/GlobalPlanner.cfg` in kinetic with the melodic ones, and it worked. But I want you to support as an official code.

**Comment by reinzor** [comment]
You could open a PR that merges these changes into kinetic-devel:

https://github.com/ros-planning/navigation/pull/739

**Comment by DLu** [comment]
Cherry-picked into #821

**Comment by inuex3** [comment]
Thany you!
