### ISSUE TITLE
How to slove "catkin_make Invoking "make -j6 -l6" failed" ?

### ISSUE THREAD

**Issue by flyRGB** [ros-planning/navigation#823]
:~/tutorials_ws$ catkin_make
Base path: /home/robotvision/tutorials_ws
Source space: /home/robotvision/tutorials_ws/src
Build space: /home/robotvision/tutorials_ws/build
Devel space: /home/robotvision/tutorials_ws/devel
Install space: /home/robotvision/tutorials_ws/install
####
####
####
####
[  0%] Built target nav_msgs_generate_messages_nodejs
[  0%] Built target nav_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target tf2_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target nav_msgs_generate_messages_py
[  0%] Built target nav_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target nav_msgs_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target actionlib_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target tf2_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target actionlib_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target actionlib_msgs_generate_messages_eus
[  0%] Built target actionlib_msgs_generate_messages_lisp
[  0%] Built target tf2_msgs_generate_messages_py
[  0%] Built target actionlib_msgs_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_lisp
[  0%] Built target tf2_msgs_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_py
[  2%] Built target gtest
[  2%] Built target actionlib_generate_messages_eus
[  4%] Generating dynamic reconfigure files from cfg/BaseLocalPlanner.cfg: /home/robotvision/tutorials_ws/devel/include/base_local_planner/BaseLocalPlannerConfig.h /home/robotvision/tutorials_ws/devel/lib/python3/dist-packages/base_local_planner/cfg/BaseLocalPlannerConfig.py
[  4%] Built target tf_generate_messages_cpp
[  4%] Built target pcl_msgs_generate_messages_eus
[  4%] Built target costmap_2d_generate_messages_nodejs
[  4%] Built target std_srvs_generate_messages_cpp
[  4%] Built target pcl_msgs_generate_messages_cpp
[  4%] Built target bond_generate_messages_lisp
[  4%] Built target nodelet_generate_messages_eus
[  4%] Built target topic_tools_generate_messages_eus
[  4%] Built target topic_tools_generate_messages_cpp
Traceback (most recent call last):
  File "/home/robotvision/tutorials_ws/src/navigation/base_local_planner/cfg/BaseLocalPlanner.cfg", line 7, in <module>
    from dynamic_reconfigure.parameter_generator_catkin import ParameterGenerator, double_t, int_t, bool_t, str_t
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/__init__.py", line 38, in <module>
    import roslib
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
navigation/base_local_planner/CMakeFiles/base_local_planner_gencfg.dir/build.make:63: recipe for target '/home/robotvision/tutorials_ws/devel/include/base_local_planner/BaseLocalPlannerConfig.h' failed
make[2]: *** [/home/robotvision/tutorials_ws/devel/include/base_local_planner/BaseLocalPlannerConfig.h] Error 1
CMakeFiles/Makefile2:3981: recipe for target 'navigation/base_local_planner/CMakeFiles/base_local_planner_gencfg.dir/all' failed
make[1]: *** [navigation/base_local_planner/CMakeFiles/base_local_planner_gencfg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  4%] Built target bond_generate_messages_eus
[  4%] Built target nodelet_generate_messages_py
[  4%] Built target std_srvs_generate_messages_nodejs
[  4%] Built target nodelet_generate_messages_lisp
[  4%] Built target pcl_msgs_generate_messages_nodejs
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j6 -l6" failed

**Comment by DLu** [comment]
Please follow the instructions here and post this on answers.ros.org, being sure to include the information listed in the "Always provide the following information" section.
