### ISSUE TITLE
Pointcloud formats

### ISSUE THREAD

**Issue by wezzoid** [ros-planning/navigation#827]
I may have misunderstood something, but it seems costmap_2d only accepts sensor_msgs/PointCloud (1) format, not PointCloud2. Why is this, when the old version seems to be deprecated? Even the point_cloud_converter package is EOL with a big red notice saying to use pcl2.

**Comment by DLu** [comment]
I'm not sure where you got this information, but costmap_2d accepts `sensor_msgs::LaserScan` `sensor_msgs::PointCloud` and `sensor_msgs::PointCloud2` in the default configuration.

[relevant wiki page](http://wiki.ros.org/costmap_2d/hydro/obstacles)

If you would like help configuring your costmaps, please open a query on answers.ros.org.
