### ISSUE TITLE
Error when catkin_make : ros-kinetic

### ISSUE THREAD

**Issue by tranducthuan1** [ros-planning/navigation#828]
+++ processing catkin package: 'navfn'
-- ==> add_subdirectory(navigation/navfn)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- navfn: 0 messages, 2 services
-- NAVFN_HAVE_FLTK: 1, NETPBM: 
-- FLTK orf NETPBM not found: cannot build navtest
-- +++ processing catkin package: 'global_planner'
-- ==> add_subdirectory(navigation/global_planner)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'rotate_recovery'
-- ==> add_subdirectory(navigation/rotate_recovery)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'move_base'
-- ==> add_subdirectory(navigation/move_base)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Configuring incomplete, errors occurred!
See also "/home/whill/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/whill/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

please help me

**Comment by DLu** [comment]
Please follow the [instructions here](http://wiki.ros.org/Support) and post this on answers.ros.org, being sure to include the information listed in the "Always provide the following information" section.
