### ISSUE TITLE
Extrapolation Error: Lookup would require extrapolation into the future

### ISSUE THREAD

**Issue by jaredjohansen** [ros-planning/navigation#836]
I use the cartographer package to create a map.  The map looks good.

In rviz, I give the robot a 2D Nav Goal.  Immediately, I get the following error:

```
[ INFO] [1547575547.221472297]: Got new plan
[ERROR] [1547575547.221699280]: Extrapolation Error: Lookup would require extrapolation into the future.  Requested time 1547575547.213480234 but the latest data is at time 1547575547.053247000, when looking up transform from frame [odom] to frame [map]

[ERROR] [1547575547.221715080]: Global Frame: odom Plan Frame size 37: map

[ WARN] [1547575547.221728031]: Could not transform the global plan to the frame of the controller
[ERROR] [1547575547.221739730]: Could not get local plan
```

This error is triggered from [this line of code](https://github.com/ros-planning/navigation/blob/dfa602c7d2302684b95c8e4c7293277e5ae84a99/base_local_planner/src/goal_functions.cpp#L113).

I understand what the error is saying.  I don't know how to address it.  Any help would be appreciated!

Note: in my cartographer config file, I have this setting `use_pose_extrapolator = false`.  If I enable that setting, this error occurs less frequently, but still occurs.  (I currently have it disabled because it sends conflicting odom->base_link tf messages, which causes the robot/sensors to jump around in the map.)

**Comment by ghost** [comment]
Hi, in my case the error disappeared after I synchronized the nodes (robot, move base on server (docker) and the UI via NTP.

**Comment by jaredjohansen** [comment]
thanks, @mojovski, for your idea.  I've seen other threads where users have nodes on multiple machines.  After synchronizing the clocks on the machines (using something like NTP), their problems go away.

In my case, my entire system is running on a single laptop.  Since all nodes use the same clock, I would not expect there to be a need to synchronize nodes (unless I misunderstand something).  Does that sound right?

**Comment by ghost** [comment]
Is rviz also running on the same node?
It also might be that the sensor sender uses system time instead of Ros::Time

**Comment by jaredjohansen** [comment]
Yes, rviz is running on the same machine.

I grepped for "walltime", "wall_time", and ros::time", in both the cartographer and navigation packages.  

Navigation has some instances of "walltime", but they are all benign (e.g. reporting to the user how long a certain function took to run).  It overwhelmingly uses ros::time.

Cartographer has many more instances of "walltime", "wall_time" and "ros::time".  The usages of walltime appear to be related to the duration of certain functions whereas ros::time are used in things like the timestamps in the header of messages.

From what I can tell, cartographer and move_base have this correct.  (If they didn't, I would expect there to be more online threads with similar errors.)

**Comment by jaredjohansen** [comment]
I found the root cause of this issue.  In the factory-default husky SW, I found that one of the launch files (control.launch) was starting a robot_localization node (called "ekf_localization").  This node was publishing the odom -> base_link transformation.

I commented out the launching of this node...and let cartographer supply the transformation instead.  This solved the issue for me.

**Comment by FeynH** [comment]
I have the same problem, I wonder how can I let cartographer supply the transformation instead?

**Comment by jaredjohansen** [comment]
You'll want to read up about the following cartographer options (and set them appropriately in your config file): map_frame, tracking_frame, published_frame, odom_frame, provide_odom_frame, publish_frame_projected_to_2d, use_pose_extrapolator.

For reference, here is what mine looks like:


```
include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "base_link",
  published_frame = "base_link",
  odom_frame = "odom",
  provide_odom_frame = true,
  publish_frame_projected_to_2d = true,
  use_pose_extrapolator = true,
  use_odometry = true,
  use_nav_sat = false,
  use_landmarks = false,
  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 1,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1.,
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1.,
  landmarks_sampling_ratio = 1.,
}

MAP_BUILDER.use_trajectory_builder_2d = true
TRAJECTORY_BUILDER_2D.num_accumulated_range_data = 1

-- min_z, max_z, min_range, and max_range refer to the pointcloud points.
-- we only keep points that are within the "min_z < pointcloud_point_height < max_z" range
TRAJECTORY_BUILDER_2D.min_z = 0.1
TRAJECTORY_BUILDER_2D.max_z = 2.0
-- we only keep points, whose distance are within the "min_range < pointcloud_point_distance < max_range" range.
-- all pointcloud points that fall outside of these ranges are discarded.
-- if min_range is < 1.1, it detects the support beams at the back of the robot as obstacles
TRAJECTORY_BUILDER_2D.min_range = 1.1
-- max_range is similar in function to obstacle_range (if you prefer to think of it that way).  Any obstacle that it
-- detects that is less than max_range (and bigger than min_range) will be added to the map.
TRAJECTORY_BUILDER_2D.max_range = 150.0
-- missing_data_ray_length is similar in function to ray_trace_range.  
-- ray_trace_range should ALWAYS be bigger than max_range.
-- Why?  You don't want the max_range to be able to add obstacles to your map that you can't raytrace away.
-- Suppose raytrace is 5m and obstaclerange is 10m.  Suppose a person walked in front of the robot and out of range 
-- of its sensors.  At some point, the person would be at 3m.  Then at 4m away, then 5m, then 6m, etc.
-- When they are at 3m, they will be detected as an obstacle.  At the next time step, they will be at 4m.  We will 
-- raytrace away the obstacle at 3m, and place one at 4m.  The same thing happens at 4m->5m.  Now consider what happens
-- at 6m -> 7m.  An obstacle was placed at 6m.  We now detect the person at 7m, and place an obstacle there.  But 
-- because our raytrace range is limited to 5m, we cannot raytrace away the obstacle at 6m,  It stays there forever.
-- This can leave phantom obstacles in the map.  
-- THE SOLUTION IS TO ALWAYS HAVE THE RAYTRACE_RANGE BE LARGER THAN THE OBSTACLE_RANGE  
TRAJECTORY_BUILDER_2D.missing_data_ray_length = 160.0

return options
```
