### ISSUE TITLE
Robot dies and returns, then move base struggles with TF timings

### ISSUE THREAD

**Issue by ghost** [ros-planning/navigation#840]
Hi, in my setup the robot is connected with the ros master (move base etc) on a server.
If the ros/move_base starts, then the robot connects, everything looks ok.
But after the robot is shut down and shut on again, it connects automatically, but then move_base (actually the costmap_2d plugin) fails to query for the current pose.
The error message I get is:
```sh
'[ERROR] [1547735400.705714489 /move_base] [/tmp/binarydeb/ros-kinetic-costmap-2d-1.14.4/src/costmap_2d_ros.cpp:Costmap2DROS::getRobotPose:546]: Extrapolation Error looking up robot pose: Lookup would require extrapolation into the past.  Requested time 1547728239.929969156 but the earliest data is at time 1547732700.186562100, when looking up transform from frame [base_link] to frame [map]

```
coming from this line:
https://github.com/mojovski/navigation/blob/melodic-devel/costmap_2d/src/costmap_2d_ros.cpp#L542

  I am on the develop-kinetic fork/branch: https://github.com/mojovski/navigation/blob/melodic-devel/costmap_2d/src/costmap_2d_ros.cpp

Does someone know this behaviour and can advise?
Thank you very much!

**Comment by mikeferguson** [comment]
Suggest perhaps looking at answers.ros.org - seems like an underlying TF error in your robot setup (I've seen numerous robots restart their drivers and come back just fine with move_base)
