### ISSUE TITLE
global_planner crashes when orientation mode is any of interpolation types

### ISSUE THREAD

**Issue by HarshalDawar** [ros-planning/navigation#845]
Hi,

ROS Kinetic, Ubuntu 16.04:

For the global_planner planning in the navigation stack for move_base, I am experiencing the following issue:

When an invalid (or inaccessible) goal is given to the planner with the orientation mode set to either None or Forward, the planner simply reports an error "Failed to get a plan." and continues its retries/resets, regardless of rest of the configuration.

However, with the same set of configuration, but with the orientation mode switched to either Interpolate or Forward then Interpolate, the planner reports the "Failed to get a plan." error once and then crashes the move_base node.

Thanks!

**Comment by DLu** [comment]
Thanks for pointing this out.
