### ISSUE TITLE
can map server load a map dynamically in latest version

### ISSUE THREAD

**Issue by pzy2253999075** [ros-planning/navigation#878]
I am working with map_server in my porject. I want my robot to  load a real-time generated map and use it to navigation。I have seen the issue raised by @MartinPeris .But it didn't fit my case.So I want to know whether the latest map_server stack  could apply this function. could someone give me  some advices,I will be gratefull.

**Comment by DLu** [comment]
Please comment on #279 if there is something that doesn't fit your use case.
