### ISSUE TITLE
Create Map From Bag File

### ISSUE THREAD

**Issue by DLu** [ros-planning/navigation#88]
There could easily be a script that reads a bag file and creates a map from the data within it, rather than following the steps here: http://www.ros.org/wiki/slam_gmapping/Tutorials/MappingFromLoggedData

**Comment by hershwg** [comment]
Go for it.

**Comment by mikeferguson** [comment]
This really belongs on slam_gmapping or slam_karto issue tracker. For slam_gmapping, I believe that https://github.com/ros-perception/slam_gmapping/pull/28 probably does what you are looking for.
