### ISSUE TITLE
The code of this navigation package is too old and the entire architecture needs to be redesigned?

### ISSUE THREAD

**Issue by zhengzh** [ros-planning/navigation#882]
`costmap`, `global_planning`, `local_planning`, `decision` packages are strongly coupled together in `move_base` package, they don't utilize inter-process communication mechanism which enables to design distributed systems.  There is only one main thread running all these nodes, one computationally intensive node will affect other nodes performance. The code of `global_planning` and `local_planning`  packages sacrifice code readability for optimization, and make simple algorithm difficult to understand.

**Comment by DLu** [comment]
May I recommend you take a look at https://github.com/locusrobotics/robot_navigation/

It's not an excuse for badly written code, but a lot of people rely on this code and its idiosyncrasies, so an entire architectural revamp is infeasible.
