### ISSUE TITLE
How to keep  the compare function  for the cellData in std::priority_queue<CellData> Q?

### ISSUE THREAD

**Issue by kintzhao** [ros-planning/navigation#887]
https://github.com/ros-planning/navigation/blob/66fba702f6ac79ba9386f22d4bbc1e0f50afb5f6/amcl/src/amcl/map/map_cspace.cpp#L123 
why using  priority_queue and how to compare it ?

**Comment by kintzhao** [comment]
is it just breadth-first   traversal ?

**Comment by SteveMacenski** [comment]
Yes
