### ISSUE TITLE
Extend Map Server to Handle Multiple Maps/Floors

### ISSUE THREAD

**Issue by DLu** [ros-planning/navigation#89]

**Comment by hershwg** [comment]
Does this http://ros.org/wiki/map_store do what you want?

**Comment by DLu** [comment]
Most likely. I was unaware of that package.

**Comment by hershwg** [comment]
Makes sense you were unaware of it.  It is almost completely undocumented!  I wrote it a long time ago and the project it was written for didn't go anywhere.  But it still works!
