### ISSUE TITLE
how to understand quadratic approximation in navfn package?

### ISSUE THREAD

**Issue by chennuo0125-HIT** [ros-planning/navigation#890]
https://github.com/ros-planning/navigation/blob/melodic-devel/navfn/src/navfn.cpp#L478  
float v = -0.2301*d*d + 0.5307*d + 0.7040;  
what is the mean of parameters in the link?

**Comment by DLu** [comment]
Boy are you in luck, because I've spent way too much time thinking about it. 
[Kernel derivation in dlux_global_planner documentation](https://github.com/locusrobotics/robot_navigation/tree/master/dlux_global_planner#the-kernel)

**Comment by chennuo0125** [comment]
thank you
