### ISSUE TITLE
How can I use local_planer and local costmaps to follow a target without using global_planer

### ISSUE THREAD

**Issue by HaoQChen** [ros-planning/navigation#891]
I can get target's position relate to base_link frame. I try to set that position as a goal, but it will stop when following. I try to look into movebase's code, it will stop when a goal is finished. I dont want the map which needed by global costmap.

**Comment by DLu** [comment]
Please use answers.ros.org for open ended questions such as this.

**Comment by han620** [comment]
Hi,have you solve the problem? @HaoQChen

**Comment by HaoQChen** [comment]
> Hi,have you solve the problem? @HaoQChen

I use this https://github.com/arnaud-ramey/followme_laser
