### ISSUE TITLE
New parameter to disable transform broadcasting

### ISSUE THREAD

**Issue by hershwg** [ros-planning/navigation#9]
[originally posted by corot to kforge trac]

Given that tf request a tree structure, in some cases is interesting to disable the amcl root level transforms broadcasting.
I set default value to true, so this change is innocuous for anyone not intentionally disabling transform broadcasting

[Download link for attached patch file]
https://kforge.ros.org/navigation/trac/raw-attachment/ticket/12/amcl_node.tf_bradcast.patch

**Comment by corot** [comment]
We would like to have this change in groovy asap. I did this patch from the fuerte version, so I'll make a pull request for groovy.

**Comment by hershwg** [comment]
sounds great, looking forward to it.

**Comment by corot** [comment]
This can be closed, right?

**Comment by mikeferguson** [comment]
fixed long ago
