### ISSUE TITLE
Unify parameters names for local planner (trivial change)

### ISSUE THREAD

**Issue by corot** [ros-planning/navigation#90]
Plugin dwa_local_planner uses path_distance_bias/goal_distance_bias/occdist_scale, but base_local_planner uses pdist_scale/gdist_scale/occdist_scale with the same semantics. I propose to unify using the latest on hydro.

The wiki page for base_local_planner was also wrong (I changed), as are the configuration for some robots, as Turtlebot: it uses base_local_planner but sets dwa_local_planner parameters.

Something similar happens with other parameters min_in_place_rotational_vel/min_in_place_vel_theta or max_rotational_vel/max_vel_theta: the dynamic parameter and the (old?) name differs.

**Comment by felix-kolbe** [comment]
+1 
Having such differences there is really bad, fiddling with the navigation configuration is puzzling itself. Could it be you changed the wiki page for every distro? A note (or distro-branching) would be good to prevent pre-hydro users hit their computers or robots.

**Comment by DLu** [comment]
I made a change for this in my layered-groovy code. I can port to Hydro if it all looks good.

**Comment by mikeferguson** [comment]
A little late to do this to either hydro or indigo, propose we do this in Jade.

**Comment by mikeferguson** [comment]
@corot -- any chance you could put together a Pull Request to fulfill this in Jade?

**Comment by corot** [comment]
mmm....  I'm horribly busy these days, so I cannot promise anything.

**Comment by corot** [comment]
Another worse case of duplicated parameters: base local planner uses both max/min_vel_theta and max/min_vel_x. So you must set both!
:+1: to keep only max/min_vel_x.  Would be great to do it before Kinetic release

**Comment by mikeferguson** [comment]
Attacking this for Melodic

**Comment by mikeferguson** [comment]
The defaults for path_distance_bias and pdist_scale in the two dynamic reconfigurations are vastly different (32 vs 0.6) -- are these really "the same thing"?

**Comment by DLu** [comment]
Closed in #725
