### ISSUE TITLE
Comments on navfn about neutral_cost

### ISSUE THREAD

**Issue by EwingKang** [ros-planning/navigation#901]
In [navfn.h#L54](https://github.com/ros-planning/navigation/blob/melodic-devel/navfn/include/navfn/navfn.h#L54)

```C++
// navfn cost values are set to
// COST_NEUTRAL + COST_FACTOR * costmap_cost_value.
// Incoming costmap cost values are in the range 0 to 252.
// With COST_NEUTRAL of 50, the COST_FACTOR needs to be about 0.8 to
// ensure the input values are spread evenly over the output range, 50
// to 253.  If COST_FACTOR is higher, cost values will have a plateau
// around obstacles and the planner will then treat (for example) the
// whole width of a narrow hallway as equally undesirable and thus
// will not plan paths down the center.
```
However, conceptually, since the COST_NEUTRAL is added equally to all cell, I think it should be:
```C++
//If COST_NEUTRAL is higher, cost values will have a plateau
// around obstacles
```
My reason is that COST_FACTOR is a multiplier for `costmap_cost_value`, which is an exponential decaying shape. OTOH, the COST_NEUTRAL is evenly added to all the cells, which resembles the "plateau" more closely IMO.

**Comment by DLu** [comment]
I think its fine as written, but the truth is that if either COST_FACTOR or COST_NEUTRAL are higher, you can get a resulting plateau.
