### ISSUE TITLE
--run-from-bag option not working

### ISSUE THREAD

**Issue by lucabonamini** [ros-planning/navigation#904]
When running AMCL with --run-from-bag option 
`rosrun amcl amcl --run-from-bag <bagfile>`
`/tf` and `/scan` are correctly published, but `/amcl_pose` is not. The output is just 

> [ INFO] [1563208802.415123654]: Bag complete, took 0.1 seconds to process, shutting down
[ INFO] [1563208802.415150114]: Final location 0.000, 0.000, -nan with stamp=0.000000

I tried to log a message when entering `laserReceived` method, and it never gets there as if the callbacks are not called properly.

Any idea? Is this option maintained?

**Comment by mikeferguson** [comment]
If you take a look at the code, it's hard coded for "base_scan" -- so it's probably not picking up your scan topic.

This feature really isn't maintained, but if somoene wanted to parameterize that the laser scan topic name, that'd be accepted as a PR.
