### ISSUE TITLE
test_robot_pose_ekf

### ISSUE THREAD

**Issue by 863217373** [ros-planning/navigation#906]
I can't find "$(find robot_pose_ekf)/test/ekf_test2_indexed.bag", when I launched "test_robot_pose_ekf.launch". Someone can provide the bag file. Thanks very much.

**Comment by DLu** [comment]
These files are [downloaded when you compile the code](https://github.com/ros-planning/navigation/blob/lunar/robot_pose_ekf/CMakeLists.txt#L101). You can also use the URL to grab them directly.

**Comment by 863217373** [comment]
Thank you for your assistance, I have solve the problem with your methods.
