### ISSUE TITLE
Map saver service call

### ISSUE THREAD

**Issue by amrp1** [ros-planning/navigation#909]
I want to be able to save a given map via a service call in order to be able to trigger it it from a gui.Is there a particular reason it has not been implemented as a service but as a node instead? Would it be a good idea to use this [saved_map_](https://github.com/ros-planning/navigation/blob/d99320a5ff8c05f3a6246810b044ccbd00524107/map_server/src/map_saver.cpp#L121) flag to return the status of such a service? i would like to be able to set the name of the map in the service request and be able to get a response informing me of the completion of the saving procedure.

**Comment by mikeferguson** [comment]
The map_saver node is simply saving from a topic, you could certainly implement such a node that runs continuously and has a service to save the map.
