### ISSUE TITLE
How to understand the role of potential array played in the Dijkstra and A*  algorithm in global planner module?

### ISSUE THREAD

**Issue by lisilin013** [ros-planning/navigation#911]
Hi, when reading the navigation source code I am having a bit of trouble understanding why using potential array in both dijkstra and a star algorithm.

[This is the link of this part of code](url)

Actually, the function of potential array in A* is that  
>the number stored in this array can be regarded as the level of the terrain. According to this, the optimal path can be found by backtracking the array.

But, the function of potential array in Dijkstra, I don't understand.

Is there any papers or blogs, or any useful materials can help me understand?

Thank you! 
I am looking forward to your reply!

**Comment by DLu** [comment]
I have documented my [entire understanding of the global planner calculations on the robot_navigation repo](https://github.com/locusrobotics/robot_navigation/tree/master/dlux_global_planner). If you have follow up questions, please post on answers.ros.org.
