### ISSUE TITLE
Path is made very close to obstacles

### ISSUE THREAD

**Issue by fayyazpocker** [ros-planning/navigation#922]
Global planner makes the path very close to the obstacles as a result of which the robot hits the obstacles. Following are the configuration used for move_base.

Global planner: global_planner/GlobalPlanner

**costmap_common_param**
```
obstacle_range: 8
raytrace_range: 15
 footprint: [[-0.9, -0.7], [-0.9, 0.7], [0.9, 0.7], [0.9, -0.7]]
inflation_radius: 1
....
```

**global_costmap_param**
```
Global planner:
 lethal cost: 253
 neutral cost: 66
 cost_factor: 0.55

global_costmap:
  global_frame: map 
  robot_base_frame: base_link 
  update_frequency: 3.0
  static_map: true

```

![Path](https://user-images.githubusercontent.com/26159275/64518028-09915380-d30f-11e9-81af-8efde7df37b9.png)

Increasing inflation radius is one probable solution but because of that every region gets affected which i don't want.
I tried increasing footprint expecting that the global planner will make the path away from the obstacle. However, i could not find much change either.

I tried playing around with lethal cost, neutral cost and cost_factor but still i am not able to get the path accordingly.

**Comment by DLu** [comment]
A) How big is your robot? 
B) What is your [inscribed_radius](http://wiki.ros.org/costmap_2d#Inflation) set to?

**Comment by fayyazpocker** [comment]
The robot is of rectangle shape. It has a length of 1.5m and a width of 1.12m. I have added an extra footprint as shown in the figure in case of safety.

![Screenshot from 2019-09-10 09-52-18](https://user-images.githubusercontent.com/26159275/64584468-6a259c80-d3b2-11e9-98a3-1e25412a2337.png)

I have not set inscribed_radius manually as i thought given the footprint, the inscribed and circumscribed radius is calculated automatically. However, following a [query](https://answers.ros.org/question/62277/inscribed-and-circumscribed-radii-of-the-robot-used-despite-footprint-being-set/) in discourse, inflation radius was also set above 1.14 (sqrt(0.9^2 + 0.7^2)). I am not able to get better result despite of that as well.

**Comment by DLu** [comment]
Since this is more of a configuration problem than an actual bug, please open your own post on [answers.ros.org](answers.ros.org) so that we can iterate a bit more. Please include your full costmap settings, including the resolution.
