### ISSUE TITLE
costmap 2d : symbol lookup error

### ISSUE THREAD

**Issue by ayush-j9** [ros-planning/navigation#931]
When I am trying work on a the teb local planner tutorial. I get a error saying:

symbol lookup error: /opt/ros/kinetic/lib//libteb_local_planner.so: undefined symbol: _ZNK10costmap_2d12Costmap2DROS12getRobotPoseERN2tf7StampedINS1_9TransformEEE

on c++filt, it gives:
costmap_2d::Costmap2DROS::getRobotPose(tf::Stamped<tf::Transform>&) const

**Comment by mikeferguson** [comment]
The teb_local_planner isn't part of this repo -- I'm guessing you need to either use a different branch of teb_local_planner or apply some code changes since we moved navigation to TF2 (hence getRobotPose now takes a geometry_msgs::PoseStamped).
