### ISSUE TITLE
Catkin_make error

### ISSUE THREAD

**Issue by RPFey** [ros-planning/navigation#932]
Hello, when i try to catkin_make the entire project, i receive following error :

 /usr/bin/env: ‘python\r’: No such file or directory
navigation/amcl/CMakeFiles/amcl_gencfg.dir/build.make:63: recipe for target '/home/yuaner/lbs_px4/week3_ws/devel/include/amcl/AMCLConfig.h' failed
make[2]: *** [/home/yuaner/lbs_px4/week3_ws/devel/include/amcl/AMCLConfig.h] Error 127
CMakeFiles/Makefile2:4331: recipe for target 'navigation/amcl/CMakeFiles/amcl_gencfg.dir/all' failed
make[1]: *** [navigation/amcl/CMakeFiles/amcl_gencfg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

what's wrong?

**Comment by mikeferguson** [comment]
It looks like you maybe don't have python installed? Regardless, this isn't a bug in navigation - please post on answer.ros.org
