### ISSUE TITLE
Unnecessary/confusing input - global_plan

### ISSUE THREAD

**Issue by mfinean** [ros-planning/navigation#933]
Within execute_cb() you define global_plan and then pass it to execute_cycle(). But execute_cycle doesn't use this variable, instead it looks to get the plan from the private member latest_plan_.

https://github.com/ros-planning/navigation/blob/d60209b348add7db379a50aaac3de8af3c7716e7/move_base/src/move_base.cpp#L757

**Comment by mikeferguson** [comment]
Now would be a good time to fix this for noetic (since it breaks ABI).
