### ISSUE TITLE
cmd_vel not been published

### ISSUE THREAD

**Issue by GusGoliath96** [ros-planning/navigation#934]
Hello, i'm trying to perform autonomous navigation using realsense camera, rtabmap and move_base nodes.
I've already got an great 2D map from rtabmap node. But when I drop an goal, i can see the goal on rostopic echo /move_base/goal. But nothing is been posted to the cmd_vel. 

This is my launch file:

<launch>

    
    <include file="$(find realsense2_camera)/launch/rs_camera.launch">
        <arg name="align_depth"           value="true" />
        <arg name="unite_imu_method"      value="linear_interpolation" />
    </include>
    
    
    <node name="imu_filter_node" pkg="imu_filter_madgwick" type="imu_filter_node">
        <param name="_use_mag"            value="false" />
        <param name="_publish_tf"         value="false" />
        <param name="_world_frame"        value="enu" />
        <remap from="/imu/data_raw"       to="/camera/imu" />
        <remap from="/imu/data"           to="/rtabmap/imu" />
    </node>

    
    <include file="/home/gus/Documents/humble_ros/src/rtabmap_ros/launch/rtabmap.launch">
        <arg name="rtabmap_args"        value="--Optimizer/GravitySigma 0.3" />
        <arg name="depth_topic"         value="/camera/aligned_depth_to_color/image_raw" />
        <arg name="rgb_topic"           value="/camera/color/image_raw" />
        <arg name="camera_info_topic"   value="/camera/color/camera_info" />
        <arg name="approx_sync"         value="false" />
        <arg name="imu_topic"           value="/rtabmap/imu" />
    </include>

    
    <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">
        <rosparam file="/home/gus/Documents/humble_ros/launch/param/costmap_common_params.yaml" command="load" ns="global_costmap" />
        <rosparam file="/home/gus/Documents/humble_ros/launch/param/costmap_common_params.yaml" command="load" ns="local_costmap" />
        <rosparam file="/home/gus/Documents/humble_ros/launch/param/local_costmap_params.yaml" command="load" />
        <rosparam file="/home/gus/Documents/humble_ros/launch/param/global_costmap_params.yaml" command="load" />
        <rosparam file="/home/gus/Documents/humble_ros/launch/param/base_local_planner_params.yaml" command="load" />
  </node>

</launch>

**Comment by mikeferguson** [comment]
I'd suggest moving this to answers.ros.org since it looks like a configuration issue most likely
