### ISSUE TITLE
How to improve the detection of obstacles

### ISSUE THREAD

**Issue by alliansmover** [ros-planning/navigation#937]
dear,
Why the obstacles have already gone away, the path of the robot has begun to be planned, how to improve the path lag?

controller_frequency: 10.0
controller_patience: 15.0
planner_patience: 3.0
planner_frequency: 3.0

thanks

**Comment by mikeferguson** [comment]
Since this is more of a configuration thing - please post to answers.ros.org. Also, please be advised that you'll likely need to provide more information to get any reasonable answers.
