### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by hoferdan** [ros-planning/navigation#938]
I am trying to get move_base in the public Tiago simulation up and running.
However, i get the following error:
```bash
/opt/ros/melodic/lib/move_base/move_base: symbol lookup error: 
/opt/ros/melodic/lib//librange_sensor_layer.so: undefined symbol: 
_ZN3tf212getTimestampIN13geometry_msgs13PointStamped_ISaIvEEEEERKN3ros4TimeERKT_
[move_base-21] process has died [pid 22677, exit code 127, 
cmd /opt/ros/melodic/lib/move_base/move_base odom:=
mobile_base_controller/odom cmd_vel:=nav_vel __name:=
move_base __log:=/root/.ros/log/d0ac4e92-f1ab-11e9-971d-983b8f10ca9d/move_base-21.log].
log file: /root/.ros/log/d0ac4e92-f1ab-11e9-971d-983b8f10ca9d/move_base-21*.log
```

If i run `c++filt` on the undefined symbol i get:
```bash
ros::Time const& tf2::getTimestamp<geometry_msgs::PointStamped_<std::allocator<void> > >(geometry_msgs::PointStamped_<std::allocator<void> > const&)
```

Am i missing a dependency?

Regards

**Comment by hoferdan** [comment]
I built this repo from scratch and it solved the problem.

**Comment by madgrizzle** [comment]
I had this problem just recently as well.  Why is this missing from the release?  I also solved it by building it from scratch..

**Comment by mikeferguson** [comment]
@madgrizzle looking at the debug message above, it would appear to be a linking issue in the librange_sensor_layer - which isn't a part of this repository.

**Comment by madgrizzle** [comment]
Thanks @mikeferguson .. there's a lot I don't understand about all of this, but cloning this library into my catkin workspace and then issuing catkin_make resolved the problem... /shrug.. its not the only weird thing I'm dealing with.

**Comment by mikeferguson** [comment]
If adding navigation to the buildspace fixes the error, it's probably because catkin is globbing a bunch of the dependencies together from navigation and the librange_sensor_layer (unless you are doing an isolated build, which I then cannot explain..)

**Comment by Mr-Tony921** [comment]
In my costmap layer plugin, I encountered the same issue, but I resolved it by adding 'include <tf2/utils.h>'.

**Comment by Evintjh** [comment]
Hey guys, may I know how did you build move_base repo from scratch? @hoferdan @madgrizzle
