### ISSUE TITLE
base_local_planner fails to build in isolation without --install

### ISSUE THREAD

**Issue by dirk-thomas** [ros-planning/navigation#94]
The headers use angles/angles.h but the CMakeLists.txt does neither find_package() nor CATKIN_DEPENDS it.

**Comment by dirk-thomas** [comment]
It needs to be added in those two places:
- https://github.com/ros-planning/navigation/blob/hydro-devel/base_local_planner/CMakeLists.txt#L15
- https://github.com/ros-planning/navigation/blob/hydro-devel/base_local_planner/CMakeLists.txt#L64

**Comment by jonbinney** [comment]
Closed, since dirk just yelled at me until i fixed it.
