### ISSUE TITLE
Can map_server load different maps from code

### ISSUE THREAD

**Issue by lzyang2000** [ros-planning/navigation#943]
We are doing a project involving multiple floors, and I have read #279 and the numerous PRs. Is there a definitive answer to loading different maps with code and which service/topic is used? If there is not a way yet we will just have to create a huge map and teleport the robot between floors, but it would be great to have such a feature.

Thank you!

**Comment by mikeferguson** [comment]
The map server as it exists today doesn't really support this yet. I'd suggest asking this on answers.ros.org as some folks may have other solutions outside the navigation stack.
