### ISSUE TITLE
/move_base_/global_costmap/costmap could not change with map used command "rosrun map_server map_server map.yaml"

### ISSUE THREAD

**Issue by shanpenghui** [ros-planning/navigation#951]
After update the ros and teb, it do not work. When i start navigation stack at the beginning, global_costmap is matched with the static map. But after change map with map_server, global_costmap is not matched with the static map. What is the problem?See the pictures bellow.
[1](https://user-images.githubusercontent.com/35164786/71439630-5e799e00-2735-11ea-9b91-8c3f0c31eb87.png)
[2](https://user-images.githubusercontent.com/35164786/71439639-66d1d900-2735-11ea-9b1b-80d5053e57d4.png)

**Comment by imutkarshpatil** [comment]
Hi @shanpenghui,

If you are using RViz for visualization purpose, try unchecking and checking the checkbox for display of global_costmap in the display tab, after you update the map with map_server. This will cause RViz to make new request to fetch an updated global_costmap.

**Comment by mikeferguson** [comment]
Pretty sure this is another case of #959 - which should be fixed by https://github.com/ros-planning/navigation/commit/37a979f7bbf3316196fe95646b6d75f9a79fd135
