### ISSUE TITLE
Mapping error 

### ISSUE THREAD

**Issue by benjamin1203** [ros-planning/navigation#954]
Hi all , I had just picked up ROS recently for a project that I am currently working on regarding autonomous robots. So I was trying to get the mapping process going , I have with me a UPsqaured connected to a RPlidar A1 and I am accessing the UPsquared through my computer. I launched the rplidar launch file first , then the gmapping launch file from another terminal. On the gmapping.launch terminal I got this error message :
[ WARN] [1577691725.782039473]: MessageFilter [target=odom ]: Dropped 100.00% of messages so far. Please turn the [ros.gmapping.message_notifier] rosconsole logger to DEBUG for more information.
I do not know how to solve this error and am stuck , please help.

**Comment by SteveMacenski** [comment]
Please redirect your question to ROS Answers, they'll be able to help you better configure gmapping
