### ISSUE TITLE
Error during installation on Raspberry Pi with ROS Kinetic due to YAML

### ISSUE THREAD

**Issue by antoninovara** [ros-planning/navigation#960]
Hello everybody!

I'm installing ROS Kinetic on Raspberry Pi 3 b+ following this tutorial.
http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi

My software version of Raspbian is this.
https://photos.app.goo.gl/PDkqA5t4tihD6RV5A

When I try to install "map_server" I get this error.
https://photos.app.goo.gl/rq4LSG4zSKA8sTU36

And this is a video with the complete proccess.
https://youtu.be/WxnyF_9ugiw

I don't know how to solve the problem. Can someone help me?

Thank you very much and regards

**Comment by SteveMacenski** [comment]
Please post the actual compiler error. Images (or links to images) are not searchable.

**Comment by antoninovara** [comment]
> Hello everybody!

I'm installing ROS Kinetic on Raspberry Pi 3 b+ following this tutorial. http://wiki.ros.org/ROSberryPi/Instal...

My software version of Raspbian is this. https://photos.app.goo.gl/PDkqA5t4tih...

When I try to install "map_server" I get this error.

/usr/include/yaml-cpp/node/detail/node.h:113:39: error: ‘shared_memory_holder’ has not been declared
   void insert(node& key, node& value, shared_memory_holder pMemory) {
                                       ^
/usr/include/yaml-cpp/node/detail/node.h:121:29: error: ‘shared_memory_holder’ has not been declared
   node* get(const Key& key, shared_memory_holder pMemory) const {
                             ^
/usr/include/yaml-cpp/node/detail/node.h:128:29: error: ‘shared_memory_holder’ has not been declared
   node& get(const Key& key, shared_memory_holder pMemory) {
                             ^
/usr/include/yaml-cpp/node/detail/node.h:134:31: error: ‘shared_memory_holder’ has not been declared
   bool remove(const Key& key, shared_memory_holder pMemory) {
                               ^
/usr/include/yaml-cpp/node/detail/node.h:138:24: error: ‘shared_memory_holder’ has not been declared
   node* get(node& key, shared_memory_holder pMemory) const {
                        ^
/usr/include/yaml-cpp/node/detail/node.h:144:24: error: ‘shared_memory_holder’ has not been declared
   node& get(node& key, shared_memory_holder pMemory) {
                        ^
/usr/include/yaml-cpp/node/detail/node.h:150:26: error: ‘shared_memory_holder’ has not been declared
   bool remove(node& key, shared_memory_holder pMemory) {
                          ^
/usr/include/yaml-cpp/node/detail/node.h:157:21: error: ‘shared_memory_holder’ has not been declared
                     shared_memory_holder pMemory) {
                     ^
/usr/include/yaml-cpp/node/detail/node.h:162:3: error: ‘shared_node_ref’ does not name a type
   shared_node_ref m_pRef;
   ^
/usr/include/yaml-cpp/node/detail/node.h: In constructor ‘YAML::detail::node::node()’:
/usr/include/yaml-cpp/node/detail/node.h:21:12: error: class ‘YAML::detail::node’ does not have any field named ‘m_pRef’
   node() : m_pRef(new node_ref) {}
            ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘bool YAML::detail::node::is(const YAML::detail::node&) const’:
/usr/include/yaml-cpp/node/detail/node.h:25:43: error: ‘m_pRef’ was not declared in this scope
   bool is(const node& rhs) const { return m_pRef == rhs.m_pRef; }
                                           ^
/usr/include/yaml-cpp/node/detail/node.h:25:57: error: ‘const class YAML::detail::node’ has no member named ‘m_pRef’
   bool is(const node& rhs) const { return m_pRef == rhs.m_pRef; }
                                                         ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘const YAML::detail::node_ref* YAML::detail::node::ref() const’:
/usr/include/yaml-cpp/node/detail/node.h:26:40: error: ‘m_pRef’ was not declared in this scope
   const node_ref* ref() const { return m_pRef.get(); }
                                        ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘bool YAML::detail::node::is_defined() const’:
/usr/include/yaml-cpp/node/detail/node.h:28:36: error: ‘m_pRef’ was not declared in this scope
   bool is_defined() const { return m_pRef->is_defined(); }
                                    ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘const YAML::Mark& YAML::detail::node::mark() const’:
/usr/include/yaml-cpp/node/detail/node.h:29:37: error: ‘m_pRef’ was not declared in this scope
   const Mark& mark() const { return m_pRef->mark(); }
                                     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::NodeType::value YAML::detail::node::type() const’:
/usr/include/yaml-cpp/node/detail/node.h:30:41: error: ‘m_pRef’ was not declared in this scope
   NodeType::value type() const { return m_pRef->type(); }
                                         ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘const string& YAML::detail::node::scalar() const’:
/usr/include/yaml-cpp/node/detail/node.h:32:46: error: ‘m_pRef’ was not declared in this scope
   const std::string& scalar() const { return m_pRef->scalar(); }
                                              ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘const string& YAML::detail::node::tag() const’:
/usr/include/yaml-cpp/node/detail/node.h:33:43: error: ‘m_pRef’ was not declared in this scope
   const std::string& tag() const { return m_pRef->tag(); }
                                           ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::EmitterStyle::value YAML::detail::node::style() const’:
/usr/include/yaml-cpp/node/detail/node.h:34:46: error: ‘m_pRef’ was not declared in this scope
   EmitterStyle::value style() const { return m_pRef->style(); }
                                              ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::mark_defined()’:
/usr/include/yaml-cpp/node/detail/node.h:44:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->mark_defined();
     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::set_ref(const YAML::detail::node&)’:
/usr/include/yaml-cpp/node/detail/node.h:61:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef = rhs.m_pRef;
     ^
/usr/include/yaml-cpp/node/detail/node.h:61:18: error: ‘const class YAML::detail::node’ has no member named ‘m_pRef’
     m_pRef = rhs.m_pRef;
                  ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::set_data(const YAML::detail::node&)’:
/usr/include/yaml-cpp/node/detail/node.h:66:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->set_data(*rhs.m_pRef);
     ^
/usr/include/yaml-cpp/node/detail/node.h:66:27: error: ‘const class YAML::detail::node’ has no member named ‘m_pRef’
     m_pRef->set_data(*rhs.m_pRef);
                           ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::set_mark(const YAML::Mark&)’:
/usr/include/yaml-cpp/node/detail/node.h:69:37: error: ‘m_pRef’ was not declared in this scope
   void set_mark(const Mark& mark) { m_pRef->set_mark(mark); }
                                     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::set_type(YAML::NodeType::value)’:
/usr/include/yaml-cpp/node/detail/node.h:74:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->set_type(type);
     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::set_null()’:
/usr/include/yaml-cpp/node/detail/node.h:78:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->set_null();
     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::set_scalar(const string&)’:
/usr/include/yaml-cpp/node/detail/node.h:82:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->set_scalar(scalar);
     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::set_tag(const string&)’:
/usr/include/yaml-cpp/node/detail/node.h:86:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->set_tag(tag);
     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::set_style(YAML::EmitterStyle::value)’:
/usr/include/yaml-cpp/node/detail/node.h:92:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->set_style(style);
     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘std::size_t YAML::detail::node::size() const’:
/usr/include/yaml-cpp/node/detail/node.h:96:37: error: ‘m_pRef’ was not declared in this scope
   std::size_t size() const { return m_pRef->size(); }
                                     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::detail::const_node_iterator YAML::detail::node::begin() const’:
/usr/include/yaml-cpp/node/detail/node.h:99:42: error: ‘m_pRef’ was not declared in this scope
     return static_cast<const node_ref&>(*m_pRef).begin();
                                          ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::detail::node_iterator YAML::detail::node::begin()’:
/usr/include/yaml-cpp/node/detail/node.h:101:34: error: ‘m_pRef’ was not declared in this scope
   node_iterator begin() { return m_pRef->begin(); }
                                  ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::detail::const_node_iterator YAML::detail::node::end() const’:
/usr/include/yaml-cpp/node/detail/node.h:104:42: error: ‘m_pRef’ was not declared in this scope
     return static_cast<const node_ref&>(*m_pRef).end();
                                          ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::detail::node_iterator YAML::detail::node::end()’:
/usr/include/yaml-cpp/node/detail/node.h:106:32: error: ‘m_pRef’ was not declared in this scope
   node_iterator end() { return m_pRef->end(); }
                                ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::push_back(YAML::detail::node&, int)’:
/usr/include/yaml-cpp/node/detail/node.h:110:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->push_back(input, pMemory);
     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::insert(YAML::detail::node&, YAML::detail::node&, int)’:
/usr/include/yaml-cpp/node/detail/node.h:114:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->insert(key, value, pMemory);
     ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::detail::node* YAML::detail::node::get(const Key&, int) const’:
/usr/include/yaml-cpp/node/detail/node.h:125:42: error: ‘m_pRef’ was not declared in this scope
     return static_cast<const node_ref&>(*m_pRef).get(key, pMemory);
                                          ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::detail::node& YAML::detail::node::get(const Key&, int)’:
/usr/include/yaml-cpp/node/detail/node.h:129:19: error: ‘m_pRef’ was not declared in this scope
     node& value = m_pRef->get(key, pMemory);
                   ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘bool YAML::detail::node::remove(const Key&, int)’:
/usr/include/yaml-cpp/node/detail/node.h:135:12: error: ‘m_pRef’ was not declared in this scope
     return m_pRef->remove(key, pMemory);
            ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::detail::node* YAML::detail::node::get(YAML::detail::node&, int) const’:
/usr/include/yaml-cpp/node/detail/node.h:142:42: error: ‘m_pRef’ was not declared in this scope
     return static_cast<const node_ref&>(*m_pRef).get(key, pMemory);
                                          ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘YAML::detail::node& YAML::detail::node::get(YAML::detail::node&, int)’:
/usr/include/yaml-cpp/node/detail/node.h:145:19: error: ‘m_pRef’ was not declared in this scope
     node& value = m_pRef->get(key, pMemory);
                   ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘bool YAML::detail::node::remove(YAML::detail::node&, int)’:
/usr/include/yaml-cpp/node/detail/node.h:151:12: error: ‘m_pRef’ was not declared in this scope
     return m_pRef->remove(key, pMemory);
            ^
/usr/include/yaml-cpp/node/detail/node.h: In member function ‘void YAML::detail::node::force_insert(const Key&, const Value&, int)’:
/usr/include/yaml-cpp/node/detail/node.h:158:5: error: ‘m_pRef’ was not declared in this scope
     m_pRef->force_insert(key, value, pMemory);
     ^
In file included from /usr/include/yaml-cpp/yaml.h:17:0,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:47:
/usr/include/yaml-cpp/node/impl.h: In constructor ‘YAML::Node::Node(YAML::NodeType::value)’:
/usr/include/yaml-cpp/node/impl.h:22:7: error: class ‘YAML::Node’ does not have any field named ‘m_pMemory’
       m_pMemory(new detail::memory_holder),
       ^
/usr/include/yaml-cpp/node/impl.h:23:16: error: ‘m_pMemory’ was not declared in this scope
       m_pNode(&m_pMemory->create_node()) {
                ^
/usr/include/yaml-cpp/node/impl.h: In constructor ‘YAML::Node::Node(const T&)’:
/usr/include/yaml-cpp/node/impl.h:30:7: error: class ‘YAML::Node’ does not have any field named ‘m_pMemory’
       m_pMemory(new detail::memory_holder),
       ^
/usr/include/yaml-cpp/node/impl.h:31:16: error: ‘m_pMemory’ was not declared in this scope
       m_pNode(&m_pMemory->create_node()) {
                ^
/usr/include/yaml-cpp/node/impl.h: In constructor ‘YAML::Node::Node(const YAML::detail::iterator_value&)’:
/usr/include/yaml-cpp/node/impl.h:37:7: error: class ‘YAML::Node’ does not have any field named ‘m_pMemory’
       m_pMemory(rhs.m_pMemory),
       ^
/usr/include/yaml-cpp/node/impl.h:37:21: error: ‘const struct YAML::detail::iterator_value’ has no member named ‘m_pMemory’
       m_pMemory(rhs.m_pMemory),
                     ^
/usr/include/yaml-cpp/node/impl.h: In copy constructor ‘YAML::Node::Node(const YAML::Node&)’:
/usr/include/yaml-cpp/node/impl.h:42:7: error: class ‘YAML::Node’ does not have any field named ‘m_pMemory’
       m_pMemory(rhs.m_pMemory),
       ^
/usr/include/yaml-cpp/node/impl.h:42:21: error: ‘const class YAML::Node’ has no member named ‘m_pMemory’
       m_pMemory(rhs.m_pMemory),
                     ^
/usr/include/yaml-cpp/node/impl.h: At global scope:
/usr/include/yaml-cpp/node/impl.h:47:47: error: ‘YAML::detail::shared_memory_holder’ has not been declared
 inline Node::Node(detail::node& node, detail::shared_memory_holder pMemory)
                                               ^
/usr/include/yaml-cpp/node/impl.h: In constructor ‘YAML::Node::Node(YAML::detail::node&, int)’:
/usr/include/yaml-cpp/node/impl.h:48:24: error: class ‘YAML::Node’ does not have any field named ‘m_pMemory’
     : m_isValid(true), m_pMemory(pMemory), m_pNode(&node) {}
                        ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘void YAML::Node::EnsureNodeExists() const’:
/usr/include/yaml-cpp/node/impl.h:56:5: error: ‘m_pMemory’ was not declared in this scope
     m_pMemory.reset(new detail::memory_holder);
     ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘void YAML::Node::reset(const YAML::Node&)’:
/usr/include/yaml-cpp/node/impl.h:208:3: error: ‘m_pMemory’ was not declared in this scope
   m_pMemory = rhs.m_pMemory;
   ^
/usr/include/yaml-cpp/node/impl.h:208:19: error: ‘const class YAML::Node’ has no member named ‘m_pMemory’
   m_pMemory = rhs.m_pMemory;
                   ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘void YAML::Node::AssignData(const YAML::Node&)’:
/usr/include/yaml-cpp/node/impl.h:257:3: error: ‘m_pMemory’ was not declared in this scope
   m_pMemory->merge(*rhs.m_pMemory);
   ^
/usr/include/yaml-cpp/node/impl.h:257:25: error: ‘const class YAML::Node’ has no member named ‘m_pMemory’
   m_pMemory->merge(*rhs.m_pMemory);
                         ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘void YAML::Node::AssignNode(const YAML::Node&)’:
/usr/include/yaml-cpp/node/impl.h:267:5: error: ‘m_pMemory’ was not declared in this scope
     m_pMemory = rhs.m_pMemory;
     ^
/usr/include/yaml-cpp/node/impl.h:267:21: error: ‘const class YAML::Node’ has no member named ‘m_pMemory’
     m_pMemory = rhs.m_pMemory;
                     ^
/usr/include/yaml-cpp/node/impl.h:272:3: error: ‘m_pMemory’ was not declared in this scope
   m_pMemory->merge(*rhs.m_pMemory);
   ^
/usr/include/yaml-cpp/node/impl.h:272:25: error: ‘const class YAML::Node’ has no member named ‘m_pMemory’
   m_pMemory->merge(*rhs.m_pMemory);
                         ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘YAML::const_iterator YAML::Node::begin() const’:
/usr/include/yaml-cpp/node/impl.h:286:53: error: ‘m_pMemory’ was not declared in this scope
   return m_pNode ? const_iterator(m_pNode->begin(), m_pMemory)
                                                     ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘YAML::iterator YAML::Node::begin()’:
/usr/include/yaml-cpp/node/impl.h:293:47: error: ‘m_pMemory’ was not declared in this scope
   return m_pNode ? iterator(m_pNode->begin(), m_pMemory) : iterator();
                                               ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘YAML::const_iterator YAML::Node::end() const’:
/usr/include/yaml-cpp/node/impl.h:299:51: error: ‘m_pMemory’ was not declared in this scope
   return m_pNode ? const_iterator(m_pNode->end(), m_pMemory) : const_iterator();
                                                   ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘YAML::iterator YAML::Node::end()’:
/usr/include/yaml-cpp/node/impl.h:305:45: error: ‘m_pMemory’ was not declared in this scope
   return m_pNode ? iterator(m_pNode->end(), m_pMemory) : iterator();
                                             ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘void YAML::Node::push_back(const YAML::Node&)’:
/usr/include/yaml-cpp/node/impl.h:322:36: error: ‘m_pMemory’ was not declared in this scope
   m_pNode->push_back(*rhs.m_pNode, m_pMemory);
                                    ^
/usr/include/yaml-cpp/node/impl.h:323:25: error: ‘const class YAML::Node’ has no member named ‘m_pMemory’
   m_pMemory->merge(*rhs.m_pMemory);
                         ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘const YAML::Node YAML::Node::operator[](const Key&) const’:
/usr/include/yaml-cpp/node/impl.h:378:57: error: ‘m_pMemory’ was not declared in this scope
                             .get(detail::to_value(key), m_pMemory);
                                                         ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘YAML::Node YAML::Node::operator[](const Key&)’:
/usr/include/yaml-cpp/node/impl.h:390:61: error: ‘m_pMemory’ was not declared in this scope
   detail::node& value = m_pNode->get(detail::to_value(key), m_pMemory);
                                                             ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘bool YAML::Node::remove(const Key&)’:
/usr/include/yaml-cpp/node/impl.h:399:49: error: ‘m_pMemory’ was not declared in this scope
   return m_pNode->remove(detail::to_value(key), m_pMemory);
                                                 ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘const YAML::Node YAML::Node::operator[](const YAML::Node&) const’:
/usr/include/yaml-cpp/node/impl.h:407:3: error: ‘m_pMemory’ was not declared in this scope
   m_pMemory->merge(*key.m_pMemory);
   ^
/usr/include/yaml-cpp/node/impl.h:407:25: error: ‘const class YAML::Node’ has no member named ‘m_pMemory’
   m_pMemory->merge(*key.m_pMemory);
                         ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘YAML::Node YAML::Node::operator[](const YAML::Node&)’:
/usr/include/yaml-cpp/node/impl.h:421:3: error: ‘m_pMemory’ was not declared in this scope
   m_pMemory->merge(*key.m_pMemory);
   ^
/usr/include/yaml-cpp/node/impl.h:421:25: error: ‘const class YAML::Node’ has no member named ‘m_pMemory’
   m_pMemory->merge(*key.m_pMemory);
                         ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘bool YAML::Node::remove(const YAML::Node&)’:
/usr/include/yaml-cpp/node/impl.h:431:40: error: ‘m_pMemory’ was not declared in this scope
   return m_pNode->remove(*key.m_pNode, m_pMemory);
                                        ^
/usr/include/yaml-cpp/node/impl.h: In member function ‘void YAML::Node::force_insert(const Key&, const Value&)’:
/usr/include/yaml-cpp/node/impl.h:441:25: error: ‘m_pMemory’ was not declared in this scope
                         m_pMemory);
                         ^
In file included from /usr/include/yaml-cpp/yaml.h:18:0,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:47:
/usr/include/yaml-cpp/node/convert.h: At global scope:
/usr/include/yaml-cpp/node/convert.h:166:29: error: ‘>>’ should be ‘> >’ within a nested template argument list
 struct convert<std::map<K, V>> {
                             ^
/usr/include/yaml-cpp/node/convert.h:193:29: error: ‘>>’ should be ‘> >’ within a nested template argument list
 struct convert<std::vector<T>> {
                             ^
/usr/include/yaml-cpp/node/convert.h:220:27: error: ‘>>’ should be ‘> >’ within a nested template argument list
 struct convert<std::list<T>> {
                           ^
/usr/include/yaml-cpp/node/convert.h:247:16: error: ‘array’ is not a member of ‘std’
 struct convert<std::array<T, N>> {
                ^
/usr/include/yaml-cpp/node/convert.h:247:16: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/message.h:38:0,
                 from /opt/ros/kinetic/include/ros/publisher.h:33,
                 from /opt/ros/kinetic/include/ros/node_handle.h:32,
                 from /opt/ros/kinetic/include/ros/ros.h:45,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:43:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /usr/include/yaml-cpp/yaml.h:18:0,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:47:
/usr/include/yaml-cpp/node/convert.h:247:16: error: ‘array’ is not a member of ‘std’
 struct convert<std::array<T, N>> {
                ^
/usr/include/yaml-cpp/node/convert.h:247:16: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/message.h:38:0,
                 from /opt/ros/kinetic/include/ros/publisher.h:33,
                 from /opt/ros/kinetic/include/ros/node_handle.h:32,
                 from /opt/ros/kinetic/include/ros/ros.h:45,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:43:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /usr/include/yaml-cpp/yaml.h:18:0,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:47:
/usr/include/yaml-cpp/node/convert.h:247:31: error: spurious ‘>>’, use ‘>’ to terminate a template argument list
 struct convert<std::array<T, N>> {
                               ^
/usr/include/yaml-cpp/node/convert.h:247:31: error: wrong number of template arguments (2, should be 1)
In file included from /usr/include/yaml-cpp/yaml.h:16:0,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:47:
/usr/include/yaml-cpp/node/node.h:142:8: note: provided for ‘template<class T> struct YAML::convert’
 struct convert;
        ^
In file included from /usr/include/yaml-cpp/yaml.h:18:0,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:47:
/usr/include/yaml-cpp/node/convert.h:280:30: error: ‘>>’ should be ‘> >’ within a nested template argument list
 struct convert<std::pair<T, U>> {
                              ^
In file included from /usr/include/yaml-cpp/yaml.h:20:0,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:47:
/usr/include/yaml-cpp/node/detail/impl.h:19:42: error: ‘shared_memory_holder’ has not been declared
                    const Key& /* key */, shared_memory_holder /* pMemory */) {
                                          ^
/usr/include/yaml-cpp/node/detail/impl.h:26:30: error: ‘enable_if’ in namespace ‘std’ does not name a template type
                typename std::enable_if<std::is_unsigned<Key>::value &&
                              ^
/usr/include/yaml-cpp/node/detail/impl.h:26:39: error: expected template-argument before ‘<’ token
                typename std::enable_if<std::is_unsigned<Key>::value &&
                                       ^
/usr/include/yaml-cpp/node/detail/impl.h:26:39: error: expected ‘>’ before ‘<’ token
/usr/include/yaml-cpp/node/detail/impl.h:27:78: error: template argument 2 is invalid
                                        !std::is_same<Key, bool>::value>::type> {
                                                                              ^
/usr/include/yaml-cpp/node/detail/impl.h:27:80: error: expected ‘::’ before ‘{’ token
                                        !std::is_same<Key, bool>::value>::type> {
                                                                                ^
/usr/include/yaml-cpp/node/detail/impl.h:27:80: error: expected identifier before ‘{’ token
/usr/include/yaml-cpp/node/detail/impl.h:27:80: error: qualified name does not name a class before ‘{’ token
/usr/include/yaml-cpp/node/detail/impl.h:44:35: error: ‘enable_if’ in namespace ‘std’ does not name a template type
 struct get_idx<Key, typename std::enable_if<std::is_signed<Key>::value>::type> {
                                   ^
/usr/include/yaml-cpp/node/detail/impl.h:44:44: error: expected template-argument before ‘<’ token
 struct get_idx<Key, typename std::enable_if<std::is_signed<Key>::value>::type> {
                                            ^
/usr/include/yaml-cpp/node/detail/impl.h:44:44: error: expected ‘>’ before ‘<’ token
/usr/include/yaml-cpp/node/detail/impl.h:44:78: error: template argument 2 is invalid
 struct get_idx<Key, typename std::enable_if<std::is_signed<Key>::value>::type> {
                                                                              ^
/usr/include/yaml-cpp/node/detail/impl.h:44:80: error: expected ‘::’ before ‘{’ token
 struct get_idx<Key, typename std::enable_if<std::is_signed<Key>::value>::type> {
                                                                                ^
/usr/include/yaml-cpp/node/detail/impl.h:44:80: error: expected identifier before ‘{’ token
/usr/include/yaml-cpp/node/detail/impl.h:44:80: error: qualified name does not name a class before ‘{’ token
/usr/include/yaml-cpp/node/detail/impl.h:60:40: error: ‘shared_memory_holder’ has not been declared
 inline bool node::equals(const T& rhs, shared_memory_holder pMemory) {
                                        ^
/usr/include/yaml-cpp/node/detail/impl.h:68:43: error: ‘shared_memory_holder’ has not been declared
 inline bool node::equals(const char* rhs, shared_memory_holder pMemory) {
                                           ^
/usr/include/yaml-cpp/node/detail/impl.h:75:29: error: ‘shared_memory_holder’ has not been declared
                             shared_memory_holder pMemory) const {
                             ^
/usr/include/yaml-cpp/node/detail/impl.h:100:45: error: ‘shared_memory_holder’ has not been declared
 inline node& node_data::get(const Key& key, shared_memory_holder pMemory) {
                                             ^
/usr/include/yaml-cpp/node/detail/impl.h: In member function ‘YAML::detail::node& YAML::detail::node_data::get(const Key&, int)’:
/usr/include/yaml-cpp/node/detail/impl.h:125:20: error: base operand of ‘->’ is not a pointer
   node& v = pMemory->create_node();
                    ^
/usr/include/yaml-cpp/node/detail/impl.h: At global scope:
/usr/include/yaml-cpp/node/detail/impl.h:131:47: error: ‘shared_memory_holder’ has not been declared
 inline bool node_data::remove(const Key& key, shared_memory_holder pMemory) {
                                               ^
/usr/include/yaml-cpp/node/detail/impl.h: In member function ‘bool YAML::detail::node_data::remove(const Key&, int)’:
/usr/include/yaml-cpp/node/detail/impl.h:137:29: error: ‘next’ is not a member of ‘std’
     kv_pairs::iterator jt = std::next(it);
                             ^
/usr/include/yaml-cpp/node/detail/impl.h:137:29: note: suggested alternatives:
In file included from /usr/include/boost/utility.hpp:18:0,
                 from /usr/include/boost/range/size.hpp:25,
                 from /usr/include/boost/range/functions.hpp:20,
                 from /usr/include/boost/range/iterator_range_core.hpp:38,
                 from /usr/include/boost/lexical_cast.hpp:30,
                 from /opt/ros/kinetic/include/ros/transport_hints.h:34,
                 from /opt/ros/kinetic/include/ros/subscribe_options.h:33,
                 from /opt/ros/kinetic/include/ros/node_handle.h:42,
                 from /opt/ros/kinetic/include/ros/ros.h:45,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:43:
/usr/include/boost/next_prior.hpp:149:10: note:   ‘boost::next’
 inline T next(T x, Distance n)
          ^
In file included from /usr/include/boost/mpl/next.hpp:17:0,
                 from /usr/include/boost/mpl/list/aux_/push_front.hpp:18,
                 from /usr/include/boost/mpl/list/list0.hpp:19,
                 from /usr/include/boost/mpl/list/list10.hpp:18,
                 from /usr/include/boost/mpl/list/list20.hpp:18,
                 from /usr/include/boost/mpl/list.hpp:36,
                 from /usr/include/boost/math/policies/policy.hpp:9,
                 from /usr/include/boost/math/policies/error_handling.hpp:19,
                 from /usr/include/boost/math/special_functions/round.hpp:14,
                 from /opt/ros/kinetic/include/ros/time.h:58,
                 from /opt/ros/kinetic/include/ros/ros.h:38,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:43:
/usr/include/boost/mpl/next_prior.hpp:29:8: note:   ‘boost::mpl::next’
 struct next
        ^
In file included from /usr/include/yaml-cpp/yaml.h:20:0,
                 from /home/pi/ros_catkin_ws/src/navigation/map_server/src/main.cpp:47:
/usr/include/yaml-cpp/node/detail/impl.h: At global scope:
/usr/include/yaml-cpp/node/detail/impl.h:156:37: error: ‘shared_memory_holder’ has not been declared
                                     shared_memory_holder pMemory) {
                                     ^
/usr/include/yaml-cpp/node/detail/impl.h:176:41: error: ‘shared_memory_holder’ has not been declared
                                         shared_memory_holder pMemory) {
                                         ^
/usr/include/yaml-cpp/node/detail/impl.h: In static member function ‘static YAML::detail::node& YAML::detail::node_data::convert_to_node(const T&, int)’:
/usr/include/yaml-cpp/node/detail/impl.h:179:10: error: base operand of ‘->’ is not a pointer
   pMemory->merge(*value.m_pMemory);
          ^
/usr/include/yaml-cpp/node/detail/impl.h:179:25: error: ‘class YAML::Node’ has no member named ‘m_pMemory’
   pMemory->merge(*value.m_pMemory);
                         ^
make[2]: *** [CMakeFiles/map_server.dir/build.make:63: CMakeFiles/map_server.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1658: CMakeFiles/map_server.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
<== Failed to process package 'map_server': 
  Command '['/opt/ros/kinetic/env.sh', 'make', '-j1']' returned non-zero exit status 2

> Reproduce this error by running:
==> cd /home/pi/ros_catkin_ws/build_isolated/map_server && /opt/ros/kinetic/env.sh make -j1

Command failed, exiting.

**Comment by ryangswin** [comment]
Have you solved the problem? I meet the same problem when I install 'camera_calibration_parsers'. My raspbian version is Buster.

**Comment by mikeferguson** [comment]
This looks like a version incompatibility - I don't think any of the Navigation folks here are RPi users, so I'd suggest posting to answers.ros.org to hopefully get some help from other RPi users.
