### ISSUE TITLE
NavFn publishes empty plans for visualization

### ISSUE THREAD

**Issue by nickswalker** [ros-planning/navigation#963]
NavFn [will publish empty plans for visualization](https://github.com/ros-planning/navigation/blob/0f6b9f152cb9317da526f883fc154810fc4e9af0/navfn/src/navfn_ros.cpp#L364), but because these paths don't have a frame id, they'll just make tools like RViz yell because they aren't going visualize something that doesn't have a frame (`Invalid argument passed to canTransform argument source_frame in tf2 frame_ids cannot be empty`).

It was changed to be this way in 46db461a98a1832a2d but there was no rationale, so I don't understand why this behavior is important. It seems to me that it'll just cause confusion.

**Comment by SteveMacenski** [comment]
That looks reasonable to me. Go ahead and submit a PR
