### ISSUE TITLE
Question about setting up a custom move_base

### ISSUE THREAD

**Issue by seanxu112** [ros-planning/navigation#968]
Hello,

I just recently cloned kinetic-devel branch. I am just wondering how do I make sure that this custom move_base package is not clashing with ros-kinetic-move-base? I only change project name in CMakeLists.txt and package.xml (also the dependency packages to our custom prefix). Somehow when I call move_base it is calling our custom version of the move_base.

Is there anything else that I have to change?

Sincerely,
Sean

**Comment by DLu** [comment]
This type of question is better suited for answers.ros.org. 

I would start by also changing the folder name and making sure you have a clean build with freshly sourced paths.
