### ISSUE TITLE
move_base: make_plan service is clearing costmaps

### ISSUE THREAD

**Issue by nxdefiant** [ros-planning/navigation#980]
Hi,

When using the the make_plan service of the move_base node the global costmap around the robot is cleared.

The global costmap before the service call:
![image](https://user-images.githubusercontent.com/885742/77850282-aa732d80-71d1-11ea-9f67-c64846b2e573.png)

The global costmap after the service call:
![image](https://user-images.githubusercontent.com/885742/77850298-d1316400-71d1-11ea-8ec5-1aa3645387f2.png)
As one can see all obstacles close to the robot are removed.

This is probably done by the call of clearCostmapWindows() in move_base.cpp:planService().

Since my global costmap consists only of a static and inflation layer there is no way to reinsert the obstacles. I don't think that clearing the global costmap is a good idea but at least there should be a way to disable clearing.

**Comment by mikeferguson** [comment]
Yeah, not sure why that clearing is there (blame says it has been there for 11 years, since the initial repo creation). I agree that this should probably be put behind a feature flag which can be toggled from a ROS param.

**Comment by nxdefiant** [comment]
Or how about disabling this with a boolean passed as an input to the service? Because the effect is limited to the service.

Also later in this function there is
```
//adding the (unreachable) original goal to the end of the global plan, in case the local planner can get you there
//(the reachable goal should have been added by the global planner)
global_plan.push_back(req.goal);
```

is it also ok to disable with option?

**Comment by mikeferguson** [comment]
You can't change the service definition without breaking the message API - so that can't happen in Melodic or earlier at this point. Adding ROS params (as long as their defaults don't change behavior) is acceptable in any release.
