### ISSUE TITLE
I cannot specify the odom topic of base_local_planner

### ISSUE THREAD

**Issue by LiuLimingCode** [ros-planning/navigation#986]
Hi, I cannot specify the odom topic of base_local_planner. my odom topic is "/racecar/odom" and I find out that base_local_planner initialized odom topic with "odom". there is no way to change it. What's worse, if the local_planner can't receive odom data, it will act in a wrong way, and there is no warn to tell you about that. 

However, the code showed below in dwa_planner_ros.cpp enables the user to change the the topic of odom by changing the param "odom_topic".

    if( private_nh.getParam( "odom_topic", odom_topic_ ))
    {
    odom_helper_.setOdomTopic( odom_topic_ );
    }

Maybe the developer can simply add this code to trajectory_planner_ros.cpp to fix this problem.

Best Wish.

**Comment by mikeferguson** [comment]
ROS topics can be remapped - since nothing else in move_base is using the odom topic, you can simply remap odom to your topic. If you need help with remapping, please ask on answers.ros.org
