### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by WLwind** [ros-planning/navigation#989]
I'm using a robot with apt installed navigation package, but move_base doesn't work with dwa properly.
/opt/ros/kinetic/lib/move_base/move_base: symbol lookup error: /opt/ros/kinetic/lib//libdwa_local_planner.so: undefined symbol: _ZN18base_local_planner27LatchedStopRotateControllerC1Ev

**Comment by mikeferguson** [comment]
This is most likely incompatible debians installed - I'd suggest doing a "apt-get update" and then reinstalling move_base, and the dwa planner (I would suggest "apt-get install --only-upgrade ros-kinetic-*).
