### ISSUE TITLE
MoveBase.action should be moved out of the stack

### ISSUE THREAD

**Issue by ahornung** [ros-planning/navigation#99]
MoveBase.action is a useful ROS interface to adhere to with any kind of navigation algorithm. Unfortunately even lightweight implementations need to depend on the "heavy" navigation stack for only the message / action declaration.

Ideally MoveBase.action would reside in common_msgs/nav_msgs so that it can be used without a large dependency (or even compilation) overhead.

**Comment by hershwg** [comment]
This is fixed in Hydro by the catkin-ization.  Under catkin, every package is independent, there are no stacks.  Just depend on ros-hydro-move-base-msgs.
