### ISSUE TITLE
Changing the static map over time

### ISSUE THREAD

**Issue by amrehab410** [ros-planning/navigation#990]
Hello, I have been trying to publish a map more than once but the trick is that the map image file is overwritten over time so I need map server to publish the new map and I did that by changing the source code of the map server node and now it keeps publishing as I wanted but rviz fails to show the map published. I tried to change the frequency of publishing and nothing worked. So how can I make it work? I attached a pic of the freq of publishing.
![Screenshot from 2020-04-30 05-33-13](https://user-images.githubusercontent.com/48420272/80669291-509da600-8aa4-11ea-861d-2636f843a063.png)

**Comment by mikeferguson** [comment]
Please ask usage questions on answers.ros.org - the issue tracker is for bug reports. Thanks.
