### ISSUE TITLE
ROS-Noetic python3-PyKDL

### ISSUE THREAD

**Issue by murtazabasu** [ros-planning/navigation#994]
Just installed ROS-Noetic and ran into this bug I suspect
![image](https://user-images.githubusercontent.com/54032524/82844779-11ffdd80-9ee2-11ea-8e5c-0dddeb944b5a.png)

It seems that PyKDL.Tree() method is not working because of a segmentation fault.
This error never used to occur on ROS/Melodic with Python 2.7. Can someone please provide a solution?

**Comment by mikeferguson** [comment]
So, the very little bit of PyKDL we use in navigation seems to be working (it's mostly just in test scripts). I don't think this is the right place for this ticket, unless something in navigation is not working right. I'm not sure where PyKDL errors should go, but I'd start with answers.ros.org

**Comment by MatthijsBurgh** [comment]
@Murtaza786-oss I think this,https://github.com/foolyc/PyKDL,  is the repo of python3-PyKDL, which is completely outdated compared to the original repo, https://github.com/orocos/orocos_kinematics_dynamics

Update: The provided package is the one maintained by debian, https://salsa.debian.org/science-team/orocos-kdl

**Comment by MatthijsBurgh** [comment]
![Screenshot from 2020-05-26 14-22-59](https://user-images.githubusercontent.com/18014833/82900208-78c1dd00-9f5c-11ea-8e66-15e0b8a2dc07.png)

Original PyKDL based on PyBind11. Sidemark, not yet released on any platform.

**Comment by murtazabasu** [comment]
Hello @MatthisBurgh thank you for your answer. The thing is I didn't install the repo you have mentioned above. PyKDL gets installed by default when I installed ros-noetic. and after installing I ran into this trouble. The same didn't happen with melodic.
Also is the original repo compatible with Python 3.8.2?
The path to PyKDL in my case is,
![image](https://user-images.githubusercontent.com/54032524/82904811-47004480-9f63-11ea-85be-ae5c3431e317.png)

**Comment by MatthijsBurgh** [comment]
I can't promise as CI runs 3.6, but 3.8 should work. It is changed compared to melodic, see https://github.com/ros/rosdistro/pull/23841/files

**Comment by murtazabasu** [comment]
Okay so I tried to build the repo you mentioned from source. But I land up with these errors can you please help me?

![image](https://user-images.githubusercontent.com/54032524/82908602-81201500-9f68-11ea-8299-7fbd5e13c74c.png)

**Comment by MatthijsBurgh** [comment]
@Murtaza786-oss please open an issue in the original repo
